<a href="https://colab.research.google.com/github/jonasknoll57/Bachelorarbeit_Demand-AD/blob/main/V20d_multicity_ready.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# V17b — Transfer-Pipeline Sanity Check: HD → MA

**Zweck:** Debug-/Sanity-Notebook für die Transfer-Pipeline.
Prüft ob das Setup mit den finalen Anomalietypen (ohne Contextuals) methodisch plausibel funktioniert.

**Experimente:**
1. MA Oracle (Target-only 100%)
2. HD → MA Zero-Shot (Strict Pure)
3. HD → MA Zero-Shot (Calibrated / Target-Stats)
4. HD → MA Fine-Tune (5% Target-Train)

**Modelle:** Forecaster (LSTM dir+ZNorm) als Hauptmodell, AE (ZNorm Hour×Station) als Vergleich.

**Anomalietypen:** point_spike, point_drop, collective (keine contextuals).

In [1]:
# ══════════════════════════════════════════════════════════════
# 0a — Colab Setup
# ══════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

Mounted at /content/drive

In [2]:
# ══════════════════════════════════════════════════════════════
# 0b — Imports
# ══════════════════════════════════════════════════════════════
import os, math, json, random, warnings, time, re, glob, copy, pickle
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import poisson
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import (
    roc_auc_score, average_precision_score, f1_score,
    precision_score, recall_score, precision_recall_curve,
    classification_report
)
from numpy.lib.stride_tricks import sliding_window_view

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

warnings.filterwarnings("ignore")
print(f"TF {tf.__version__}, GPU: {tf.config.list_physical_devices('GPU')}")

TF 2.19.0, GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
# ══════════════════════════════════════════════════════════════
# 0c — V20d Config
# ══════════════════════════════════════════════════════════════
DATA_BASE    = '/content/drive/MyDrive/BA_Colab/data'
CLEANED_BASE = '/content/drive/MyDrive/BA_Colab/cleaned'

RUN_NAME    = 'v20d_spike_only'
RESULTS_DIR = f'{DATA_BASE}/{RUN_NAME}'
MODELS_DIR  = f'{RESULTS_DIR}/models'
PRELOAD_MODELS_DIR = MODELS_DIR

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

# Paths
geo_path           = f'{CLEANED_BASE}/geo_information/geo_information.parquet'
station_names_path = f'{DATA_BASE}/station_names/station_names.parquet'

# City-specific demand paths
CITY_DEMAND = {
    "Mannheim":   f'{CLEANED_BASE}/demand/Mannheim/demand_cleaned.parquet',
    "Heidelberg": f'{CLEANED_BASE}/demand/Heidelberg/demand_cleaned.parquet',
}

@dataclass
class V17bConfig:
    aggregation_minutes: int = 60
    train_ratio: float = 0.67
    val_ratio: float = 0.82
    min_events_per_day: float = 3.0
    rolling_days: int = 56
    min_context_obs: int = 20

    # Model architecture
    ae_window_size: int = 24
    ae_latent_dim: int = 32
    ae_layers: int = 2
    ae_dropout: float = 0.10
    ae_epochs: int = 50
    ae_batch_size: int = 2048
    ae_lr: float = 1e-3
    ae_early_stop: int = 8
    eval_batch_size: int = 2048

    # Regime thresholds
    low_demand_q: float = 0.33
    high_demand_q: float = 0.67

    require_contiguous: bool = True
    use_bidirectional: bool = False

    # Features
    ae_features: List[str] = field(default_factory=lambda: [
        "n_lends", "n_returns",
        "hour_sin", "hour_cos", "dow_sin", "dow_cos",
        "month_sin", "month_cos", "is_weekend"
    ])
    ae_score_features: List[str] = field(default_factory=lambda: ["n_lends", "n_returns"])

    # Injection
    injection_rate: float = 0.015
    injection_seed: int = 42

    # Fine-tune
    finetune_ratio: float = 0.05

cfg = V17bConfig()
print(cfg)
print(f"\nResults: {RESULTS_DIR}")
print(f"Models : {MODELS_DIR}")

V17bConfig(aggregation_minutes=60, train_ratio=0.67, val_ratio=0.82, min_events_per_day=3.0, rolling_days=56, min_context_obs=20, ae_window_size=24, ae_latent_dim=32, ae_layers=2, ae_dropout=0.1, ae_epochs=50, ae_batch_size=2048, ae_lr=0.001, ae_early_stop=8, eval_batch_size=2048, low_demand_q=0.33, high_demand_q=0.67, require_contiguous=True, use_bidirectional=False, ae_features=['n_lends', 'n_returns', 'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos', 'month_sin', 'month_cos', 'is_weekend'], ae_score_features=['n_lends', 'n_returns'], injection_rate=0.015, injection_seed=42, finetune_ratio=0.05)

Results: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only
Models : /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/models

---
## Shared Functions (aus V17 übernommen)

In [4]:
# ══════════════════════════════════════════════════════════════
# 1 — Aggregation
# ══════════════════════════════════════════════════════════════
def aggregate_station_level(df: pd.DataFrame, minutes: int = 60,
                            add_relative: bool = False) -> pd.DataFrame:
    out = df.copy()
    freq = f"{minutes}min"
    out["time_bin"] = out["timestamp"].dt.floor(freq)

    agg = (
        out.groupby(
            ["station_id", "station_name_id", "station_name", "location_id", "time_bin"],
            as_index=False
        )
        .agg({
            "n_lends": "sum",
            "n_returns": "sum",
            "latitude": "first",
            "longitude": "first"
        })
        .rename(columns={"time_bin": "hour_ts"})
    )

    agg["total_demand"] = agg["n_lends"] + agg["n_returns"]
    agg["net_flow"] = agg["n_returns"] - agg["n_lends"]
    agg["abs_net_flow"] = agg["net_flow"].abs()

    agg["hour"] = agg["hour_ts"].dt.hour
    agg["dow"] = agg["hour_ts"].dt.dayofweek
    agg["month"] = agg["hour_ts"].dt.month
    agg["is_weekend"] = agg["dow"].isin([5, 6]).astype(int)

    agg["hour_sin"] = np.sin(2 * np.pi * agg["hour"] / 24)
    agg["hour_cos"] = np.cos(2 * np.pi * agg["hour"] / 24)
    agg["dow_sin"]  = np.sin(2 * np.pi * agg["dow"] / 7)
    agg["dow_cos"]  = np.cos(2 * np.pi * agg["dow"] / 7)
    agg["month_sin"] = np.sin(2 * np.pi * (agg["month"] - 1) / 12)
    agg["month_cos"] = np.cos(2 * np.pi * (agg["month"] - 1) / 12)

    agg = agg.sort_values(["station_id", "hour_ts"]).reset_index(drop=True)
    return agg

In [5]:
# ══════════════════════════════════════════════════════════════
# 2 — Gap-Fill
# ══════════════════════════════════════════════════════════════
def fill_missing_time_bins(x: pd.DataFrame, minutes: int = 60) -> pd.DataFrame:
    freq = f"{minutes}min"
    parts = []
    x = x.copy().sort_values(["station_id", "hour_ts"])
    x = (
        x.groupby(["station_id", "hour_ts"], as_index=False)
         .agg({
             "station_name_id": "first", "station_name": "first",
             "location_id": "first", "latitude": "first",
             "longitude": "first", "n_lends": "sum", "n_returns": "sum",
         })
    )
    key_cols = ["station_id", "station_name_id", "station_name",
                "location_id", "latitude", "longitude"]

    for sid, g in x.groupby("station_id", sort=False):
        g = g.sort_values("hour_ts").copy()
        full_idx = pd.date_range(g["hour_ts"].min(), g["hour_ts"].max(), freq=freq)
        g = g.set_index("hour_ts").reindex(full_idx)
        g.index.name = "hour_ts"
        g["n_lends"]   = g["n_lends"].fillna(0).astype(int)
        g["n_returns"] = g["n_returns"].fillna(0).astype(int)
        for col in key_cols:
            g[col] = g[col].ffill().bfill()
        parts.append(g.reset_index())

    result = pd.concat(parts, ignore_index=True)
    result["total_demand"] = result["n_lends"] + result["n_returns"]
    result["net_flow"]     = result["n_returns"] - result["n_lends"]
    result["abs_net_flow"] = result["net_flow"].abs()

    result["hour"] = result["hour_ts"].dt.hour
    result["dow"]  = result["hour_ts"].dt.dayofweek
    result["month"] = result["hour_ts"].dt.month
    result["is_weekend"] = result["dow"].isin([5, 6]).astype(int)

    result["hour_sin"]  = np.sin(2 * np.pi * result["hour"] / 24)
    result["hour_cos"]  = np.cos(2 * np.pi * result["hour"] / 24)
    result["dow_sin"]   = np.sin(2 * np.pi * result["dow"] / 7)
    result["dow_cos"]   = np.cos(2 * np.pi * result["dow"] / 7)
    result["month_sin"] = np.sin(2 * np.pi * (result["month"] - 1) / 12)
    result["month_cos"] = np.cos(2 * np.pi * (result["month"] - 1) / 12)

    return result.sort_values(["station_id", "hour_ts"]).reset_index(drop=True)

In [6]:
# ══════════════════════════════════════════════════════════════
# 3 — Station-Filter, Demand-Regime, Train/Val/Test Split
# ══════════════════════════════════════════════════════════════
def prepare_stations_and_splits(df: pd.DataFrame, cfg, city_name=""):
    n_days = (df["hour_ts"].max() - df["hour_ts"].min()).days + 1
    min_events = int(n_days * cfg.min_events_per_day)

    station_volume = df.groupby("station_id")["total_demand"].sum()
    active_ids = station_volume[station_volume >= min_events].index.tolist()
    df = df[df["station_id"].isin(active_ids)].copy()

    station_profile = (
        df.groupby(["station_id", "station_name"], as_index=False)
          .agg(
              avg_total_demand_h=("total_demand", "mean"),
              avg_lends_h=("n_lends", "mean"),
              avg_returns_h=("n_returns", "mean"),
              latitude=("latitude", "first"),
              longitude=("longitude", "first")
          )
    )
    q1 = station_profile["avg_total_demand_h"].quantile(cfg.low_demand_q)
    q2 = station_profile["avg_total_demand_h"].quantile(cfg.high_demand_q)
    station_profile["demand_regime"] = station_profile["avg_total_demand_h"].apply(
        lambda x: "low" if x <= q1 else ("mid" if x <= q2 else "high")
    )
    df = df.merge(
        station_profile[["station_id", "demand_regime", "avg_total_demand_h"]],
        on="station_id", how="left"
    )

    t_min = df["hour_ts"].min()
    t_max = df["hour_ts"].max()
    total_h = (t_max - t_min).total_seconds() / 3600

    train_end = t_min + pd.Timedelta(hours=int(total_h * cfg.train_ratio))
    val_end   = t_min + pd.Timedelta(hours=int(total_h * cfg.val_ratio))

    cn = f" ({city_name})" if city_name else ""
    print(f"  Aktive Stationen{cn}: {df['station_id'].nunique()}")
    print(f"  Regime: {station_profile['demand_regime'].value_counts().to_dict()}")
    print(f"  Zeitraum: {t_min.date()} bis {t_max.date()} ({n_days} Tage)")
    print(f"  Split: Train < {train_end.date()}, Val < {val_end.date()}, Test ab {val_end.date()}")

    return df, station_profile, train_end, val_end

In [7]:
# ══════════════════════════════════════════════════════════════
# 4 — Rolling Context z-Scores + Poisson + ECDF + Labels
# ══════════════════════════════════════════════════════════════
TARGETS = ["n_lends", "n_returns", "net_flow", "total_demand"]
COUNT_TARGETS = ["n_lends", "n_returns", "total_demand"]

def add_context_keys(x: pd.DataFrame) -> pd.DataFrame:
    x = x.copy()
    x["ctx_hour"] = x["hour_ts"].dt.hour
    x["ctx_dow"]  = x["hour_ts"].dt.dayofweek
    return x

def rolling_context_scores_vectorized(
    full_df: pd.DataFrame, target: str,
    rolling_days: int = 56, min_obs: int = 20
) -> pd.DataFrame:
    x = full_df.copy().sort_values(["station_id", "hour_ts"]).reset_index(drop=True)
    mu_col    = f"{target}_mu_ctx_roll"
    sd_col    = f"{target}_sd_ctx_roll"
    score_col = f"{target}_z_ctx_roll"

    n_slots = max(rolling_days // 7, 4)
    main_window = n_slots
    main_minp   = min(min_obs, main_window)

    grouped = x.groupby(["station_id", "ctx_hour", "ctx_dow"])[target]
    rolling_mean = grouped.transform(
        lambda s: s.shift(1).rolling(window=main_window, min_periods=main_minp).mean()
    )
    rolling_std = grouped.transform(
        lambda s: s.shift(1).rolling(window=main_window, min_periods=main_minp).std(ddof=0)
    )

    fb1_window = n_slots * 2
    fb1_minp   = min(min_obs, fb1_window)
    grouped_sh = x.groupby(["station_id", "ctx_hour"])[target]
    fb1_mean = grouped_sh.transform(
        lambda s: s.shift(1).rolling(window=fb1_window, min_periods=fb1_minp).mean()
    )
    fb1_std = grouped_sh.transform(
        lambda s: s.shift(1).rolling(window=fb1_window, min_periods=fb1_minp).std(ddof=0)
    )

    fb2_window = n_slots * 4
    fb2_minp   = min(min_obs, fb2_window)
    grouped_s = x.groupby(["station_id"])[target]
    fb2_mean = grouped_s.transform(
        lambda s: s.shift(1).rolling(window=fb2_window, min_periods=fb2_minp).mean()
    )
    fb2_std = grouped_s.transform(
        lambda s: s.shift(1).rolling(window=fb2_window, min_periods=fb2_minp).std(ddof=0)
    )

    mu = rolling_mean.copy()
    sd = rolling_std.copy()
    mask1 = mu.isna()
    mu = mu.where(~mask1, fb1_mean)
    sd = sd.where(~mask1, fb1_std)
    mask2 = mu.isna()
    mu = mu.where(~mask2, fb2_mean)
    sd = sd.where(~mask2, fb2_std)
    sd = sd.clip(lower=1e-6)
    z = (x[target] - mu) / sd

    x[mu_col]    = mu
    x[sd_col]    = sd
    x[score_col] = z
    return x


def add_rolling_poisson_scores_vectorized(
    full_df: pd.DataFrame, target: str,
    rolling_days: int = 56, min_obs: int = 20
) -> pd.DataFrame:
    x = full_df.copy().sort_values(["station_id", "hour_ts"]).reset_index(drop=True)
    lam_col       = f"{target}_lambda_ctx_roll"
    score_col     = f"{target}_poisson_upper_score"
    score_low_col = f"{target}_poisson_lower_score"
    mu_col        = f"{target}_mu_ctx_roll"

    if mu_col not in x.columns:
        raise ValueError(f"{mu_col} muss zuerst berechnet werden")

    x[lam_col] = x[mu_col].clip(lower=1e-6)
    vals = x[target].values
    lams = x[lam_col].values

    with np.errstate(divide='ignore', invalid='ignore'):
        tail_p = poisson.sf(vals.astype(float) - 1, lams.astype(float))
        score  = -np.log10(np.clip(tail_p, 1e-12, None))
        lower_p   = poisson.cdf(vals.astype(float), lams.astype(float))
        score_low = -np.log10(np.clip(lower_p, 1e-12, None))

    mask_nan = np.isnan(lams)
    score[mask_nan]     = np.nan
    score_low[mask_nan] = np.nan

    x[score_col]     = score
    x[score_low_col] = score_low
    return x


def percentile_score(train_vals: np.ndarray, values: np.ndarray) -> np.ndarray:
    train_vals = np.asarray(train_vals, dtype=float)
    values     = np.asarray(values, dtype=float)
    train_vals = train_vals[np.isfinite(train_vals)]
    if len(train_vals) == 0:
        return np.full(len(values), np.nan, dtype=float)
    train_sorted = np.sort(train_vals)
    ranks = np.searchsorted(train_sorted, values, side="right")
    return ranks / len(train_sorted)

def calibrate_scores_by_station(
    full_df: pd.DataFrame, train_mask: pd.Series, raw_score_cols: List[str]
) -> pd.DataFrame:
    x = full_df.copy()
    for col in raw_score_cols:
        if col not in x.columns:
            continue
        pct_col = f"{col}_pct_station"
        x[pct_col] = np.nan
        for sid, grp in x.groupby("station_id", sort=False):
            idx_all   = grp.index
            idx_train = grp.index[train_mask.loc[idx_all]]
            train_vals = x.loc[idx_train, col].to_numpy(dtype=float) if len(idx_train) > 0 else np.array([])
            vals       = x.loc[idx_all, col].to_numpy(dtype=float)
            x.loc[idx_all, pct_col] = percentile_score(train_vals, vals)
    return x

def build_eval_labels_calibrated(x: pd.DataFrame) -> pd.DataFrame:
    y = x.copy()
    y["label_eval"] = "normal"

    z_up = "total_demand_score_upper_pct_station"
    z_low = "total_demand_score_lower_pct_station"
    p_up  = "total_demand_poisson_upper_score_pct_station"
    p_low = "total_demand_poisson_lower_score_pct_station"

    required = [z_up, z_low, p_up, p_low]
    missing = [c for c in required if c not in y.columns]
    if missing:
        raise ValueError(f"Fehlende Spalten: {missing}")

    td = y["total_demand"].fillna(0)
    mu = y["total_demand_mu_ctx_roll"]

    abs_min_high    = np.maximum(5, np.ceil(mu + 2)).fillna(5)
    abs_min_low_ref = np.maximum(3, np.ceil(mu)).fillna(3)

    high_strong    = ((y[z_up] >= 0.995) | (y[p_up] >= 0.995)) & (td >= abs_min_high)
    high_consensus = ((y[z_up] >= 0.99) & (y[p_up] >= 0.99)) & (td >= abs_min_high)
    cond_high = high_strong | high_consensus

    low_possible  = mu >= abs_min_low_ref
    low_strong    = ((y[z_low] >= 0.999) | (y[p_low] >= 0.999)) & low_possible
    low_consensus = ((y[z_low] >= 0.995) & (y[p_low] >= 0.995)) & low_possible
    cond_low = (low_strong | low_consensus) & ~cond_high

    grau_high = ((y[z_up] >= 0.99) | (y[p_up] >= 0.99)) & ~cond_high & ~cond_low
    grau_low  = ((y[z_low] >= 0.99) | (y[p_low] >= 0.99)) & ~cond_high & ~cond_low & ~grau_high

    y.loc[grau_high, "label_eval"] = "grauzone_high"
    y.loc[grau_low,  "label_eval"] = "grauzone_low"
    y.loc[cond_high, "label_eval"] = "anomal_high"
    y.loc[cond_low,  "label_eval"] = "anomal_low"
    return y


def run_statistical_pipeline(df: pd.DataFrame, cfg, train_end):
    print("  [1/5] Kontext-Keys...")
    df = add_context_keys(df)
    print("  [2/5] Rolling z-Scores...")
    for tgt in TARGETS:
        df = rolling_context_scores_vectorized(
            df, target=tgt,
            rolling_days=cfg.rolling_days, min_obs=cfg.min_context_obs
        )
    for tgt in TARGETS:
        zc = f"{tgt}_z_ctx_roll"
        df[f"{tgt}_score_upper"] = df[zc]
        df[f"{tgt}_score_lower"] = -df[zc]

    print("  [3/5] Poisson-Tail-Scores...")
    for tgt in COUNT_TARGETS:
        df = add_rolling_poisson_scores_vectorized(
            df, target=tgt,
            rolling_days=cfg.rolling_days, min_obs=cfg.min_context_obs
        )

    print("  [4/5] ECDF-Kalibrierung...")
    raw_score_cols = []
    for tgt in TARGETS:
        raw_score_cols += [f"{tgt}_score_upper", f"{tgt}_score_lower"]
    for tgt in COUNT_TARGETS:
        raw_score_cols += [f"{tgt}_poisson_upper_score", f"{tgt}_poisson_lower_score"]

    train_mask = df["hour_ts"] < train_end
    df = calibrate_scores_by_station(df, train_mask, raw_score_cols)

    print("  [5/5] Labels...")
    df = build_eval_labels_calibrated(df)

    anomaly_rate = df["label_eval"].isin(["anomal_high", "anomal_low"]).mean()
    print(f"  Label-Verteilung:")
    print(f"    {df['label_eval'].value_counts().to_dict()}")
    print(f"    Anomalie-Rate: {anomaly_rate:.4f} ({anomaly_rate*100:.2f}%)")
    return df

In [8]:
# ══════════════════════════════════════════════════════════════
# 5 — Sequenzbuilder (Window-Level Labels)
# ══════════════════════════════════════════════════════════════
def make_sequences_with_window_labels(
    x: pd.DataFrame, feature_cols: List[str], window_size: int,
    synth_label_col: str = "synth_label",
    synth_type_col: str = "synth_type",
    require_contiguous: bool = True,
    agg_minutes: int = 60
) -> Tuple[np.ndarray, pd.DataFrame]:
    X_parts, meta_parts = [], []
    expected_ns = pd.Timedelta(minutes=agg_minutes).value

    for sid, g in x.groupby("station_id", sort=False):
        g = g.sort_values("hour_ts").reset_index(drop=True)
        n = len(g)
        if n < window_size:
            continue

        vals = g[feature_cols].to_numpy(dtype=np.float32)
        win  = sliding_window_view(vals, window_shape=window_size, axis=0)
        win  = np.moveaxis(win, -1, 1)

        valid_mask = np.ones(n - window_size + 1, dtype=bool)

        if require_contiguous:
            ts_int = pd.to_datetime(g["hour_ts"]).astype("int64").to_numpy()
            diffs  = np.diff(ts_int)
            step_ok = (diffs == expected_ns).astype(np.int8)
            if window_size > 1:
                ok_sums = np.convolve(step_ok, np.ones(window_size-1, dtype=np.int32), mode="valid")
                valid_mask = (ok_sums == (window_size - 1))

        if not valid_mask.any():
            continue

        end_indices = np.arange(window_size - 1, n)[valid_mask]
        X_parts.append(win[valid_mask])

        meta_chunk = g.iloc[end_indices].copy()

        synth_arr = g[synth_label_col].to_numpy()
        type_arr  = g[synth_type_col].to_numpy()

        window_labels, window_types, window_counts = [], [], []
        for end_idx in end_indices:
            start_idx = end_idx - window_size + 1
            window_synth = synth_arr[start_idx:end_idx + 1]
            window_type  = type_arr[start_idx:end_idx + 1]

            has_synth = int(window_synth.max())
            n_synth   = int(window_synth.sum())

            if has_synth:
                synth_positions = np.where(window_synth == 1)[0]
                wtype = window_type[synth_positions[-1]]
            else:
                wtype = "none"

            window_labels.append(has_synth)
            window_types.append(wtype)
            window_counts.append(n_synth)

        meta_chunk["window_synth_label"] = window_labels
        meta_chunk["window_synth_type"]  = window_types
        meta_chunk["n_synth_in_window"]  = window_counts
        meta_parts.append(meta_chunk)

    if X_parts:
        X    = np.concatenate(X_parts, axis=0)
        meta = pd.concat(meta_parts, axis=0).reset_index(drop=True)
    else:
        X    = np.empty((0, window_size, len(feature_cols)), dtype=np.float32)
        meta = pd.DataFrame()

    return X, meta

In [9]:
# ══════════════════════════════════════════════════════════════
# 6 — Model Builders (AE + Forecaster)
# ══════════════════════════════════════════════════════════════
def build_lstm_autoencoder(
    n_input_features: int,
    window_size: int,
    latent_dim: int = 32,
    n_layers: int = 2,
    dropout: float = 0.1,
    bidirectional: bool = False,
    n_output_features: Optional[int] = None,
) -> keras.Model:
    n_output_features = n_output_features or n_input_features
    inputs = keras.Input(shape=(window_size, n_input_features), name="encoder_input")
    x = inputs
    for i in range(n_layers):
        return_sequences = (i < n_layers - 1)
        lstm = layers.LSTM(
            latent_dim, return_sequences=return_sequences,
            dropout=dropout, name=f"encoder_lstm_{i+1}"
        )
        x = layers.Bidirectional(lstm, name=f"encoder_bi_{i+1}")(x) if bidirectional else lstm(x)
    latent = x
    x = layers.RepeatVector(window_size, name="repeat_vector")(latent)
    for i in range(n_layers):
        lstm = layers.LSTM(
            latent_dim, return_sequences=True,
            dropout=dropout, name=f"decoder_lstm_{i+1}"
        )
        x = layers.Bidirectional(lstm, name=f"decoder_bi_{i+1}")(x) if bidirectional else lstm(x)
    outputs = layers.TimeDistributed(
        layers.Dense(n_output_features), name="output_dense"
    )(x)
    return keras.Model(inputs, outputs, name="lstm_autoencoder")


def build_lstm_forecaster(
    n_input_features: int,
    n_output_features: int,
    context_steps: int = 23,
    latent_dim: int = 32,
    n_layers: int = 2,
    dropout: float = 0.1,
) -> keras.Model:
    inputs = keras.Input(shape=(context_steps, n_input_features), name="forecast_input")
    x = inputs
    for i in range(n_layers):
        return_sequences = (i < n_layers - 1)
        x = layers.LSTM(
            latent_dim, return_sequences=return_sequences,
            dropout=dropout, name=f"forecast_lstm_{i+1}"
        )(x)
    outputs = layers.Dense(n_output_features, name="forecast_output")(x)
    return keras.Model(inputs, outputs, name="lstm_forecaster")


def train_model_generic(model, X_train, Y_train, X_val, Y_val,
                        epochs, lr, batch_size, early_stop, verbose=1):
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr, clipnorm=1.0),
        loss="mse"
    )
    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=early_stop,
            restore_best_weights=True, verbose=1
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=4, verbose=1
        )
    ]
    history = model.fit(
        X_train, Y_train,
        validation_data=(X_val, Y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=verbose
    )
    return model, history

In [10]:
# ══════════════════════════════════════════════════════════════
# 7 — Scoring Helpers (AE + Forecaster)
# ══════════════════════════════════════════════════════════════
def predict_in_batches(model, X, batch_size=2048):
    preds = []
    for i in range(0, len(X), batch_size):
        preds.append(model.predict(X[i:i + batch_size], verbose=0))
    return np.concatenate(preds, axis=0) if preds else np.empty((0, 0, 0), dtype=np.float32)


def compute_reconstruction_scores(X, X_hat, input_features, score_features,
                                  mode="last_step_mean"):
    score_idx = [input_features.index(c) for c in score_features]
    err = (X - X_hat) ** 2
    err_score = err[:, :, score_idx]
    if mode == "last_step_mean":
        return err_score[:, -1, :].mean(axis=1)
    elif mode == "window_mean":
        return err_score.mean(axis=(1, 2))
    elif mode == "max_over_features":
        return err_score[:, -1, :].max(axis=1)
    else:
        raise ValueError(f"Unbekannter mode: {mode}")


def compute_forecast_scores(model, X_input, X_actual_last_step, score_features,
                            ae_features, mode="directional"):
    X_pred = predict_in_batches(model, X_input, batch_size=2048)
    score_idx = [ae_features.index(f) for f in score_features]
    X_actual = X_actual_last_step[:, score_idx]
    err = (X_pred - X_actual) ** 2
    if mode == "mean":
        return err.mean(axis=1)
    elif mode == "max":
        return err.max(axis=1)
    elif mode == "directional":
        abs_err = np.abs(X_pred - X_actual)
        denom = np.maximum(np.maximum(np.abs(X_actual), np.abs(X_pred)), 1e-6)
        rel_err = abs_err / denom
        return 0.5 * abs_err.mean(axis=1) + 0.5 * rel_err.mean(axis=1)
    else:
        raise ValueError(f"Unbekannter mode: {mode}")

In [11]:
# ══════════════════════════════════════════════════════════════
# 8 — Z-Normalisierung (Hour + Hour×Station)
# ══════════════════════════════════════════════════════════════
def znorm_score_by_hour(meta_df, raw_score_col, val_start, test_start,
                        new_col="score_znorm_hour"):
    meta = meta_df.copy()
    val_normal = (
        (meta["hour_ts"] >= val_start) &
        (meta["hour_ts"] < test_start) &
        (meta["synth_label"] == 0)
    )
    hour_col = meta["hour_ts"].dt.hour
    mu_per_hour = {}
    std_per_hour = {}
    for h in range(24):
        vals = meta.loc[val_normal & (hour_col == h), raw_score_col].dropna()
        mu_per_hour[h]  = vals.mean() if len(vals) > 0 else 0.0
        std_per_hour[h] = vals.std()  if len(vals) > 1 else 1.0

    hours = hour_col.values
    raw   = meta[raw_score_col].values
    znorm = np.zeros_like(raw)
    for i in range(len(raw)):
        h = hours[i]
        znorm[i] = (raw[i] - mu_per_hour[h]) / max(std_per_hour[h], 1e-8)
    meta[new_col] = znorm
    return meta, mu_per_hour, std_per_hour


def znorm_score_by_hour_station(meta_df, raw_score_col, val_start, test_start,
                                new_col="score_znorm_hour_station"):
    meta = meta_df.copy()
    val_normal = (
        (meta["hour_ts"] >= val_start) &
        (meta["hour_ts"] < test_start) &
        (meta["synth_label"] == 0)
    )
    hour_col = meta["hour_ts"].dt.hour
    meta["_hour_tmp"] = hour_col

    stats = (
        meta[val_normal]
        .groupby(["station_id", "_hour_tmp"])[raw_score_col]
        .agg(["mean", "std", "count"])
        .reset_index()
    )
    global_stats = (
        meta[val_normal]
        .groupby("_hour_tmp")[raw_score_col]
        .agg(["mean", "std"])
        .reset_index()
        .rename(columns={"mean": "g_mean", "std": "g_std"})
    )
    stats = stats.merge(global_stats, on="_hour_tmp", how="left")
    stats["use_mean"] = np.where(stats["count"] >= 10, stats["mean"], stats["g_mean"])
    stats["use_std"]  = np.where(stats["count"] >= 10, stats["std"],  stats["g_std"])
    stats["use_std"]  = stats["use_std"].clip(lower=1e-8)

    meta = meta.merge(
        stats[["station_id", "_hour_tmp", "use_mean", "use_std"]],
        on=["station_id", "_hour_tmp"], how="left"
    )
    meta["use_mean"] = meta["use_mean"].fillna(0.0)
    meta["use_std"]  = meta["use_std"].fillna(1.0).clip(lower=1e-8)
    meta[new_col] = (meta[raw_score_col] - meta["use_mean"]) / meta["use_std"]
    meta = meta.drop(columns=["_hour_tmp", "use_mean", "use_std"])
    return meta

In [12]:
# ══════════════════════════════════════════════════════════════
# 9 — Synthetic Injection (V17b: OHNE Contextuals)
# ══════════════════════════════════════════════════════════════
# Original V17 balanced probs: [spike=0.35, drop=0.30, ctx=0.25, coll=0.10]
# Ohne contextuals, renormiert auf 3 Typen:
# spike = 0.35/(0.35+0.30+0.10) = 0.467
# drop  = 0.30/(0.35+0.30+0.10) = 0.400
# coll  = 0.10/(0.35+0.30+0.10) = 0.133

V17B_INJECTION_PROBS = {
    "point_spike": 1.0
}
V17B_COLLECTIVE_BLOCK_LEN = (2, 4)

def inject_synthetic_anomalies_v17b(
    df: pd.DataFrame,
    inject_start: pd.Timestamp,
    injection_rate: float = 0.015,
    seed: int = 42,
    verbose: bool = True
) -> pd.DataFrame:
    """
    Injection ohne contextuals.
    Gibt zusätzlich requested vs actually injected counts zurück.
    """
    probs = list(V17B_INJECTION_PROBS.values())
    type_names = list(V17B_INJECTION_PROBS.keys())
    block_min, block_max = V17B_COLLECTIVE_BLOCK_LEN

    rng = np.random.RandomState(seed)
    out = df.copy()

    out["original_n_lends"]   = out["n_lends"].copy()
    out["original_n_returns"] = out["n_returns"].copy()
    out["synth_label"] = 0
    out["synth_type"]  = "none"

    inject_mask = out["hour_ts"] >= inject_start
    inject_idx  = out[inject_mask].index.to_numpy()

    if len(inject_idx) == 0:
        print("  WARNUNG: Keine Daten ab inject_start!")
        return out

    n_inject = max(1, int(len(inject_idx) * injection_rate))
    inject_df = out.loc[inject_idx]
    has_demand = inject_df[inject_df["total_demand"] > 0].index.to_numpy()

    if len(has_demand) < n_inject:
        n_inject = len(has_demand)

    chosen_idx = rng.choice(has_demand, size=n_inject, replace=False)
    types = rng.choice(type_names, size=n_inject, p=probs)

    injected_indices = set()

    # Track requested vs actually injected
    requested_counts = {t: 0 for t in type_names}
    injected_counts  = {t: 0 for t in type_names}

    for idx, anom_type in zip(chosen_idx, types):
        requested_counts[anom_type] += 1
        if idx in injected_indices:
            continue

        row = out.loc[idx]

        if anom_type == "point_spike":
            factor = rng.uniform(2.0, 4.0)
            out.loc[idx, "n_lends"]   = int(row["n_lends"] * factor) + rng.randint(1, 4)
            out.loc[idx, "n_returns"] = int(row["n_returns"] * factor) + rng.randint(1, 4)
            out.loc[idx, "synth_label"] = 1
            out.loc[idx, "synth_type"]  = "point_spike"
            injected_indices.add(idx)
            injected_counts["point_spike"] += 1

        elif anom_type == "point_drop":
            regime = row.get("demand_regime", "low")
            if regime == "high" and row["total_demand"] >= 8:
                do_drop = True
            elif regime == "mid" and row["total_demand"] >= 5:
                do_drop = True
            else:
                do_drop = False

            if do_drop:
                out.loc[idx, "n_lends"]   = rng.randint(0, 2)
                out.loc[idx, "n_returns"] = rng.randint(0, 2)
                out.loc[idx, "synth_label"] = 1
                out.loc[idx, "synth_type"]  = "point_drop"
                injected_indices.add(idx)
                injected_counts["point_drop"] += 1

        elif anom_type == "collective":
            block_len = rng.randint(block_min, block_max + 1)
            sid = row["station_id"]
            station_inject = out[
                (out["station_id"] == sid) & inject_mask
            ].sort_values("hour_ts")

            if idx in station_inject.index:
                pos = station_inject.index.get_loc(idx)
                if pos + block_len <= len(station_inject):
                    block_idx = station_inject.index[pos:pos + block_len]
                    factor = rng.uniform(2.5, 5.0)
                    block_actually = 0
                    for bidx in block_idx:
                        if bidx not in injected_indices:
                            out.loc[bidx, "n_lends"]   = int(out.loc[bidx, "original_n_lends"] * factor) + rng.randint(1, 5)
                            out.loc[bidx, "n_returns"] = int(out.loc[bidx, "original_n_returns"] * factor) + rng.randint(1, 5)
                            out.loc[bidx, "synth_label"] = 1
                            out.loc[bidx, "synth_type"]  = "collective"
                            injected_indices.add(bidx)
                            block_actually += 1
                    injected_counts["collective"] += block_actually

    # Update derived columns
    out["total_demand"]  = out["n_lends"] + out["n_returns"]
    out["net_flow"]      = out["n_returns"] - out["n_lends"]
    out["abs_net_flow"]  = out["net_flow"].abs()

    n_injected = out["synth_label"].sum()
    inject_total = inject_mask.sum()

    if verbose:
        print(f"\n  Synthetic Injection (V17b — ohne Contextuals):")
        print(f"    Inject-Zeilen gesamt:  {inject_total:,}")
        print(f"    Injizierte Punkte:     {n_injected:,} ({n_injected/inject_total*100:.2f}%)")
        print(f"\n    Requested vs Actually Injected:")
        for t in type_names:
            print(f"      {t:15s}  requested={requested_counts[t]:5d}  injected={injected_counts[t]:5d}")
        print(f"\n    Effective rates (of inject region):")
        for t in type_names:
            rate = injected_counts[t] / inject_total * 100
            print(f"      {t:15s}  {rate:.3f}%")

    return out

In [13]:
# ══════════════════════════════════════════════════════════════
# 10 — City Data Pipeline
# ══════════════════════════════════════════════════════════════
def prepare_city_data(demand_path: str, geo_path: str, station_names_path: str,
                      cfg, city_name: str):
    print(f"\n{'='*70}")
    print(f"  DATEN-PIPELINE: {city_name}")
    print(f"{'='*70}")

    demand = pd.read_parquet(demand_path)
    geo    = pd.read_parquet(geo_path)
    snames = pd.read_parquet(station_names_path)
    snames = snames.rename(columns={'id': 'station_name_id', 'name': 'station_name'})

    demand = demand.merge(snames[['station_name_id', 'station_name']], on='station_name_id', how='left')
    demand = demand.merge(geo[['location_id', 'latitude', 'longitude']], on='location_id', how='left')
    demand['timestamp'] = pd.to_datetime(demand['timestamp'], utc=True)

    print(f"  Roh: {len(demand):,} Zeilen, {demand['station_id'].nunique()} Stationen")
    print(f"  Zeitraum: {demand['timestamp'].min().date()} bis {demand['timestamp'].max().date()}")

    print("\n  [1] Aggregation...")
    df = aggregate_station_level(demand, minutes=cfg.aggregation_minutes)
    print(f"      Shape: {df.shape}")

    print("  [2] Gap-Fill...")
    n_before = len(df)
    df = fill_missing_time_bins(df, minutes=cfg.aggregation_minutes)
    print(f"      {n_before:,} -> {len(df):,} (+{len(df)-n_before:,})")

    print("  [3] Stationen, Regime, Splits...")
    df, station_profile, train_end, val_end = prepare_stations_and_splits(df, cfg, city_name)

    print("  [4] Statistische Scoring-Pipeline...")
    df = run_statistical_pipeline(df, cfg, train_end)

    return df, station_profile, train_end, val_end

In [14]:
# ══════════════════════════════════════════════════════════════
# 11 — V17b Unified Evaluation (erweitert um Regime×Type Matrix)
# ══════════════════════════════════════════════════════════════
ANOM_TYPES = ["point_spike"]  # V20d: only spikes
REGIMES    = ["high", "mid", "low"]

def evaluate_v17b(
    meta: pd.DataFrame,
    score_col: str,
    experiment_name: str,
    val_start: pd.Timestamp,
    test_start: pd.Timestamp,
    verbose: bool = True
) -> Dict:
    meta = meta.copy()
    meta["split_eval"] = np.where(
        meta["hour_ts"] < val_start, "train",
        np.where(meta["hour_ts"] < test_start, "val", "test")
    )

    val_m  = meta[meta["split_eval"] == "val"].copy()
    test_m = meta[meta["split_eval"] == "test"].copy()

    if len(val_m) == 0 or len(test_m) == 0:
        print(f"  [{experiment_name}] WARNUNG: Keine VAL/TEST-Daten!")
        return {}

    results = {"experiment": experiment_name, "n_val": len(val_m), "n_test": len(test_m)}

    # --- Anomaly Rates ---
    n_test_total = len(test_m)
    n_test_anom  = (test_m["synth_label"] == 1).sum()
    results["anomaly_rate_total"] = n_test_anom / n_test_total

    for atype in ANOM_TYPES:
        n_t = (test_m["synth_type"] == atype).sum()
        results[f"rate_{atype}"] = n_t / n_test_total
        results[f"n_{atype}"] = int(n_t)

    # --- VAL: Threshold bestimmen ---
    y_val = val_m["synth_label"].astype(int).values
    s_val = val_m[score_col].values

    threshold = None
    if len(np.unique(y_val)) > 1:
        prec_v, rec_v, thr_v = precision_recall_curve(y_val, s_val)
        results["val_pr_auc"] = average_precision_score(y_val, s_val)
        if len(thr_v) > 0:
            f1_v = 2 * prec_v[:-1] * rec_v[:-1] / (prec_v[:-1] + rec_v[:-1] + 1e-12)
            best_idx = np.argmax(f1_v)
            threshold = float(thr_v[best_idx])
            results["val_best_f1"] = float(f1_v[best_idx])
            results["val_threshold"] = threshold

    if threshold is None:
        val_norm = val_m[val_m["synth_label"] == 0][score_col]
        if len(val_norm) > 0:
            threshold = float(val_norm.quantile(0.99))
        else:
            threshold = float(test_m[score_col].quantile(0.99))
        results["val_threshold"] = threshold
        results["threshold_source"] = "fallback_99pct"

    # --- TEST: Global Metriken ---
    y_test = test_m["synth_label"].astype(int).values
    s_test = test_m[score_col].values
    p_test = (s_test >= threshold).astype(int)

    if len(np.unique(y_test)) > 1:
        results["test_pr_auc"]  = average_precision_score(y_test, s_test)
        results["test_roc_auc"] = roc_auc_score(y_test, s_test)
        results["test_f1"]      = f1_score(y_test, p_test, zero_division=0)
        results["test_prec"]    = precision_score(y_test, p_test, zero_division=0)
        results["test_recall"]  = recall_score(y_test, p_test, zero_division=0)

    # --- TEST: Per-Type ---
    for atype in ANOM_TYPES:
        type_mask = test_m["synth_type"] == atype
        normal_mask = test_m["synth_label"] == 0
        sub = test_m[type_mask | normal_mask].copy()
        n_anom = int(type_mask.sum())

        if n_anom > 0 and len(sub) > 0:
            y_t = (sub["synth_type"] == atype).astype(int).values
            y_s = sub[score_col].values
            if len(set(y_t)) > 1:
                results[f"pr_{atype}"] = average_precision_score(y_t, y_s)
            type_seqs = test_m[type_mask]
            detected = (type_seqs[score_col] >= threshold).sum()
            results[f"dr_{atype}"] = detected / len(type_seqs) if len(type_seqs) > 0 else 0.0
        else:
            results[f"pr_{atype}"] = None
            results[f"dr_{atype}"] = None

    # --- TEST: Per-Type x Per-Regime (3x3 Matrix) ---
    regime_rows = []
    for atype in ANOM_TYPES:
        for regime in REGIMES:
            rm = test_m["demand_regime"] == regime
            tm = test_m["synth_type"] == atype
            nm = test_m["synth_label"] == 0
            n_a = int((rm & tm).sum())
            n_n = int((rm & nm).sum())
            pr, f1_val, dr = None, None, None
            if n_a > 0 and n_n > 0:
                sub = test_m[(rm & tm) | (rm & nm)]
                y_t = (sub["synth_type"] == atype).astype(int).values
                y_s = sub[score_col].values
                pr = average_precision_score(y_t, y_s) if len(set(y_t)) > 1 else None
                p_sub = (y_s >= threshold).astype(int)
                f1_val = f1_score(y_t, p_sub, zero_division=0)
                detected = (test_m[rm & tm][score_col] >= threshold).sum()
                dr = detected / n_a
            regime_rows.append({
                "type": atype, "regime": regime,
                "n_anom": n_a, "pr_auc": pr, "f1": f1_val, "dr": dr
            })
    results["regime_detail"] = pd.DataFrame(regime_rows)

    if verbose:
        print(f"\n  [{experiment_name}]")
        print(f"    Anomaly Rate: {results['anomaly_rate_total']:.4f} ({results['anomaly_rate_total']*100:.2f}%)")
        for at in ANOM_TYPES:
            print(f"      {at:15s}: n={results[f'n_{at}']:5d}, rate={results[f'rate_{at}']:.4f}")
        print(f"    Threshold: {threshold:.6f}")
        print(f"    TEST PR-AUC={results.get('test_pr_auc', 'N/A'):.4f}, "
              f"F1={results.get('test_f1', 'N/A'):.4f}, "
              f"Prec={results.get('test_prec', 'N/A'):.4f}, "
              f"Recall={results.get('test_recall', 'N/A'):.4f}")
        print(f"    Per-Type PR-AUC:")
        for at in ANOM_TYPES:
            v = results.get(f'pr_{at}')
            print(f"      {at:15s}: {v:.4f}" if v is not None else f"      {at:15s}: N/A")
        print(f"\n    Type × Regime Matrix (PR-AUC / F1):")
        rd = results["regime_detail"]
        for regime in REGIMES:
            vals = []
            for atype in ANOM_TYPES:
                row = rd[(rd["type"] == atype) & (rd["regime"] == regime)].iloc[0]
                pr_s = f"{row['pr_auc']:.3f}" if row['pr_auc'] is not None else "  N/A"
                f1_s = f"{row['f1']:.3f}" if row['f1'] is not None else "  N/A"
                vals.append(f"{pr_s}/{f1_s}")
            print(f"      {regime:4s}: " + "  |  ".join(vals))
        print(f"            {'spike':>11s}  |  {'drop':>11s}  |  {'collective':>11s}")

    return results

---
## Schritt 1: Städte laden

In [ ]:
# ══════════════════════════════════════════════════════════════
# 12 — Mannheim (Target) laden
# ══════════════════════════════════════════════════════════════
df_ma, profile_ma, train_end_ma, val_end_ma = prepare_city_data(
    CITY_DEMAND["Mannheim"], geo_path, station_names_path, cfg, "Mannheim"
)

print(f"\n{'='*70}")
print("  ZUSAMMENFASSUNG")
print(f"{'='*70}")
print(f"  MA: {df_ma.shape}, Stationen: {df_ma['station_id'].nunique()}")

======================================================================
  DATEN-PIPELINE: Mannheim
======================================================================
  Roh: 2,547,242 Zeilen, 123 Stationen
  Zeitraum: 2023-03-31 bis 2026-02-02

  [1] Aggregation...
      Shape: (1036182, 22)
  [2] Gap-Fill...
      1,036,182 -> 2,297,523 (+1,261,341)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Mannheim): 88
  Regime: {'mid': 31, 'high': 31, 'low': 31}
  Zeitraum: 2023-03-31 bis 2026-02-02 (1040 Tage)
  Split: Train < 2025-02-25, Val < 2025-07-30, Test ab 2025-07-30
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 2122687, 'grauzone_low': 46485, 'grauzone_high': 32007, 'anomal_high': 5640, 'anomal_low': 631}
    Anomalie-Rate: 0.0028 (0.28%)

======================================================================
  ZUSAMMENFASSUNG
======================================================================
  MA: (2207450, 70), Stationen: 88

---
## Schritt 2: Injection (V17b — ohne Contextuals)

In [ ]:
# ══════════════════════════════════════════════════════════════
# 13 — Injection: MA (ab train_end)
# ══════════════════════════════════════════════════════════════
df_ma_inj = inject_synthetic_anomalies_v17b(
    df_ma,
    inject_start=train_end_ma,
    injection_rate=cfg.injection_rate,
    seed=cfg.injection_seed + 1,
    verbose=True
)

vm = (df_ma_inj["hour_ts"] >= train_end_ma) & (df_ma_inj["hour_ts"] < val_end_ma)
tm = df_ma_inj["hour_ts"] >= val_end_ma
print(f"\nMA: VAL-Anomalien={df_ma_inj.loc[vm, 'synth_label'].sum():,}, "
      f"TEST-Anomalien={df_ma_inj.loc[tm, 'synth_label'].sum():,}")

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  748,728
    Injizierte Punkte:     11,230 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested=11230  injected=11230

    Effective rates (of inject region):
      point_spike      1.500%

MA: VAL-Anomalien=5,484, TEST-Anomalien=5,746

---
## Schritt 3: Scaler + Sequenzen

In [22]:
# ══════════════════════════════════════════════════════════════
# 14 — Scaler + Sequenzen für BEIDE Städte
# ══════════════════════════════════════════════════════════════
ae_features = cfg.ae_features
score_features = cfg.ae_score_features
context_steps = cfg.ae_window_size - 1   # 23

def build_sequences_for_city(df_clean, df_inj, train_end, val_end, city_name, scaler_ext=None):
    """
    Build sequences for a city. If scaler_ext is provided, use it (transfer scenario).
    Returns: X_all, meta_all, scaler, X_train_normal, Y_train_normal, etc.
    """
    df_c = df_clean.copy().sort_values(["station_id", "hour_ts"]).reset_index(drop=True)
    df_c = df_c.dropna(subset=ae_features)
    train_mask_sc = df_c["hour_ts"] < train_end

    if scaler_ext is None:
        scaler = StandardScaler()
        scaler.fit(df_c.loc[train_mask_sc, ae_features])
        print(f"  [{city_name}] Scaler gefittet auf {train_mask_sc.sum():,} Train-Zeilen")
    else:
        scaler = scaler_ext
        print(f"  [{city_name}] Externer Scaler verwendet (Transfer)")

    df_inj_s = df_inj.copy().sort_values(["station_id", "hour_ts"]).reset_index(drop=True)
    df_inj_s = df_inj_s.dropna(subset=ae_features)

    df_inj_scaled = df_inj_s.copy()
    df_inj_scaled[ae_features] = scaler.transform(df_inj_s[ae_features])

    for col in ["synth_label", "synth_type", "original_n_lends", "original_n_returns",
                "demand_regime", "label_eval"]:
        if col in df_inj_s.columns:
            df_inj_scaled[col] = df_inj_s[col].values

    X_all, meta_all = make_sequences_with_window_labels(
        df_inj_scaled,
        feature_cols=ae_features,
        window_size=cfg.ae_window_size,
        synth_label_col="synth_label",
        synth_type_col="synth_type",
        require_contiguous=cfg.require_contiguous,
        agg_minutes=cfg.aggregation_minutes
    )

    meta_all["split_eval"] = np.where(
        meta_all["hour_ts"] < train_end, "train",
        np.where(meta_all["hour_ts"] < val_end, "val", "test")
    )

    print(f"  [{city_name}] Sequenzen: {X_all.shape}")
    print(f"  [{city_name}] Split: {meta_all['split_eval'].value_counts().to_dict()}")

    # Train normal + Val normal
    train_normal = (meta_all["split_eval"] == "train") & (meta_all["label_eval"] == "normal")
    val_normal   = (meta_all["split_eval"] == "val") & (meta_all["synth_label"] == 0) & (meta_all["label_eval"] == "normal")

    X_train = X_all[train_normal.values]
    X_val_c = X_all[val_normal.values]

    print(f"  [{city_name}] X_train (normal): {X_train.shape}, X_val (normal): {X_val_c.shape}")

    return {
        "X_all": X_all, "meta_all": meta_all, "scaler": scaler,
        "X_train": X_train, "X_val_clean": X_val_c,
        "train_normal_mask": train_normal, "val_normal_mask": val_normal,
        "train_end": train_end, "val_end": val_end,
    }


print("\n--- Mannheim (Target) ---")
ma_data = build_sequences_for_city(df_ma, df_ma_inj, train_end_ma, val_end_ma, "MA")

--- Mannheim (Target) ---

NameError: name 'df_ma' is not defined

---
## Experiment 1: MA Oracle (Target-Only 100%)

In [ ]:

# ══════════════════════════════════════════════════════════════
# X — V20d-Modelle laden (nur aus V20d-Pfad)
# ══════════════════════════════════════════════════════════════
from tensorflow import keras
import os

def try_load_city_models(models_dir, city_name):
    city_key = city_name.lower()
    fc_path = os.path.join(models_dir, f"{city_key}_oracle_forecaster.keras")
    ae_path = os.path.join(models_dir, f"{city_key}_oracle_autoencoder.keras")

    fc_model = keras.models.load_model(fc_path, compile=False) if os.path.exists(fc_path) else None
    ae_model = keras.models.load_model(ae_path, compile=False) if os.path.exists(ae_path) else None

    print(f"[{city_name}] FC:", "geladen" if fc_model is not None else "nicht gefunden", "→", fc_path)
    print(f"[{city_name}] AE:", "geladen" if ae_model is not None else "nicht gefunden", "→", ae_path)
    return fc_model, ae_model, fc_path, ae_path

ma_fc_loaded, ma_ae_loaded, ma_fc_path, ma_ae_path = try_load_city_models(PRELOAD_MODELS_DIR, "MA")
hd_fc_loaded, hd_ae_loaded, hd_fc_path, hd_ae_path = try_load_city_models(PRELOAD_MODELS_DIR, "HD")

[MA] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/models/ma_oracle_forecaster.keras
[MA] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/models/ma_oracle_autoencoder.keras
[HD] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/models/hd_oracle_forecaster.keras
[HD] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/models/hd_oracle_autoencoder.keras

In [ ]:
# ══════════════════════════════════════════════════════════════
# 15 — MA Oracle: Train + Evaluate Forecaster + AE on full MA Train
# ══════════════════════════════════════════════════════════════

def evaluate_fixed_threshold_v17b(
    meta: pd.DataFrame,
    score_col: str,
    experiment_name: str,
    val_start: pd.Timestamp,
    test_start: pd.Timestamp,
    fixed_threshold: float,
    threshold_source: str = "external_fixed",
    verbose: bool = True
) -> Dict:
    meta = meta.copy()
    meta["split_eval"] = np.where(
        meta["hour_ts"] < val_start, "train",
        np.where(meta["hour_ts"] < test_start, "val", "test")
    )

    val_m  = meta[meta["split_eval"] == "val"].copy()
    test_m = meta[meta["split_eval"] == "test"].copy()

    results = {
        "experiment": experiment_name,
        "n_val": len(val_m),
        "n_test": len(test_m),
        "val_threshold": float(fixed_threshold),
        "threshold_source": threshold_source,
    }

    if len(test_m) == 0:
        print(f"  [{experiment_name}] WARNUNG: Keine TEST-Daten!")
        return results

    n_test_total = len(test_m)
    n_test_anom  = int((test_m["synth_label"] == 1).sum())
    results["anomaly_rate_total"] = n_test_anom / n_test_total if n_test_total > 0 else np.nan

    for atype in ANOM_TYPES:
        n_t = int((test_m["synth_type"] == atype).sum())
        results[f"rate_{atype}"] = n_t / n_test_total if n_test_total > 0 else np.nan
        results[f"n_{atype}"] = n_t

    y_test = test_m["synth_label"].astype(int).values
    s_test = test_m[score_col].values
    p_test = (s_test >= fixed_threshold).astype(int)

    if len(np.unique(y_test)) > 1:
        results["test_pr_auc"]  = average_precision_score(y_test, s_test)
        results["test_roc_auc"] = roc_auc_score(y_test, s_test)
        results["test_f1"]      = f1_score(y_test, p_test, zero_division=0)
        results["test_prec"]    = precision_score(y_test, p_test, zero_division=0)
        results["test_recall"]  = recall_score(y_test, p_test, zero_division=0)

    for atype in ANOM_TYPES:
        type_mask = test_m["synth_type"] == atype
        normal_mask = test_m["synth_label"] == 0
        sub = test_m[type_mask | normal_mask].copy()
        n_anom = int(type_mask.sum())

        if n_anom > 0 and len(sub) > 0:
            y_t = (sub["synth_type"] == atype).astype(int).values
            y_s = sub[score_col].values
            if len(set(y_t)) > 1:
                results[f"pr_{atype}"] = average_precision_score(y_t, y_s)
            detected = int((test_m.loc[type_mask, score_col] >= fixed_threshold).sum())
            results[f"dr_{atype}"] = detected / n_anom if n_anom > 0 else 0.0
        else:
            results[f"pr_{atype}"] = None
            results[f"dr_{atype}"] = None

    regime_rows = []
    for atype in ANOM_TYPES:
        for regime in REGIMES:
            rm = test_m["demand_regime"] == regime
            tm = test_m["synth_type"] == atype
            nm = test_m["synth_label"] == 0
            n_a = int((rm & tm).sum())
            n_n = int((rm & nm).sum())
            pr, f1_val, dr = None, None, None
            if n_a > 0 and n_n > 0:
                sub = test_m[(rm & tm) | (rm & nm)]
                y_t = (sub["synth_type"] == atype).astype(int).values
                y_s = sub[score_col].values
                pr = average_precision_score(y_t, y_s) if len(set(y_t)) > 1 else None
                p_sub = (y_s >= fixed_threshold).astype(int)
                f1_val = f1_score(y_t, p_sub, zero_division=0)
                detected = int((test_m.loc[rm & tm, score_col] >= fixed_threshold).sum())
                dr = detected / n_a if n_a > 0 else None
            regime_rows.append({
                "type": atype, "regime": regime,
                "n_anom": n_a, "pr_auc": pr, "f1": f1_val, "dr": dr
            })
    results["regime_detail"] = pd.DataFrame(regime_rows)

    if verbose:
        print(f"\n  [{experiment_name}]")
        print(f"    Fixed threshold: {fixed_threshold:.6f} ({threshold_source})")
        print(f"    TEST PR-AUC: {results.get('test_pr_auc')}")
        print(f"    TEST F1:     {results.get('test_f1')}")
        print(f"    TEST Recall: {results.get('test_recall')}")

    return results


def run_oracle_experiment(city_data, cfg, city_name, models_dir,
                          fc_model_preloaded=None, ae_model_preloaded=None):
    """Train or load both FC and AE on full city training data, then evaluate."""
    X_train = city_data["X_train"]
    X_val_c = city_data["X_val_clean"]
    X_all   = city_data["X_all"]
    meta    = city_data["meta_all"].copy()
    train_end = city_data["train_end"]
    val_end   = city_data["val_end"]

    score_idx = [ae_features.index(f) for f in score_features]
    results = {}

    # --- Forecaster ---
    if fc_model_preloaded is not None:
        print(f"\n  [{city_name}] Verwende vorgeladenen Forecaster.")
        fc_model = fc_model_preloaded
    else:
        print(f"\n  [{city_name}] Training Forecaster (Oracle)...")
        fc_model = build_lstm_forecaster(
            n_input_features=len(ae_features),
            n_output_features=len(score_features),
            context_steps=context_steps,
            latent_dim=cfg.ae_latent_dim,
            n_layers=2,
            dropout=cfg.ae_dropout,
        )

        X_fc_train = X_train[:, :context_steps, :]
        Y_fc_train = X_train[:, -1, :][:, score_idx]
        X_fc_val   = X_val_c[:, :context_steps, :]
        Y_fc_val   = X_val_c[:, -1, :][:, score_idx]

        fc_model, _ = train_model_generic(
            fc_model, X_fc_train, Y_fc_train, X_fc_val, Y_fc_val,
            epochs=cfg.ae_epochs, lr=cfg.ae_lr,
            batch_size=cfg.ae_batch_size, early_stop=cfg.ae_early_stop,
            verbose=0
        )
        fc_model.save(f"{models_dir}/{city_name.lower()}_oracle_forecaster.keras")
        print(f"  [{city_name}] Forecaster gespeichert.")

    X_fc_input = X_all[:, :context_steps, :]
    X_actual_last = X_all[:, -1, :]
    meta["score_fc_raw"] = compute_forecast_scores(
        fc_model, X_fc_input, X_actual_last,
        score_features, ae_features, mode="directional"
    )
    meta = znorm_score_by_hour_station(
        meta, "score_fc_raw", train_end, val_end,
        new_col="score_fc_znorm_hs"
    )
    results["FC_Oracle"] = evaluate_v17b(
        meta, "score_fc_znorm_hs", f"{city_name}_Oracle_FC",
        val_start=train_end, test_start=val_end
    )

    # --- Autoencoder ---
    if ae_model_preloaded is not None:
        print(f"\n  [{city_name}] Verwende vorgeladenen Autoencoder.")
        ae_model = ae_model_preloaded
    else:
        print(f"\n  [{city_name}] Training Autoencoder (Oracle)...")
        ae_model = build_lstm_autoencoder(
            n_input_features=len(ae_features),
            window_size=cfg.ae_window_size,
            latent_dim=cfg.ae_latent_dim,
            n_layers=cfg.ae_layers,
            dropout=cfg.ae_dropout,
            bidirectional=cfg.use_bidirectional,
        )

        ae_model, _ = train_model_generic(
            ae_model, X_train, X_train, X_val_c, X_val_c,
            epochs=cfg.ae_epochs, lr=cfg.ae_lr,
            batch_size=cfg.ae_batch_size, early_stop=cfg.ae_early_stop,
            verbose=0
        )
        ae_model.save(f"{models_dir}/{city_name.lower()}_oracle_autoencoder.keras")
        print(f"  [{city_name}] Autoencoder gespeichert.")

    X_hat = predict_in_batches(ae_model, X_all)
    meta["score_ae_raw"] = compute_reconstruction_scores(
        X_all, X_hat, ae_features, score_features, mode="last_step_mean"
    )
    meta = znorm_score_by_hour_station(
        meta, "score_ae_raw", train_end, val_end,
        new_col="score_ae_znorm_hs"
    )
    results["AE_Oracle"] = evaluate_v17b(
        meta, "score_ae_znorm_hs", f"{city_name}_Oracle_AE",
        val_start=train_end, test_start=val_end
    )

    return results, fc_model, ae_model, meta

# Run MA Oracle
oracle_results, ma_fc_oracle, ma_ae_oracle, ma_meta = run_oracle_experiment(
    ma_data, cfg, "MA", MODELS_DIR,
    fc_model_preloaded=ma_fc_loaded,
    ae_model_preloaded=ma_ae_loaded,
)

  [MA] Training Forecaster (Oracle)...

Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 33: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 45: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Restoring model weights from the end of the best epoch: 48.
  [MA] Forecaster gespeichert.

  [MA_Oracle_FC]
    Anomaly Rate: 0.0136 (1.36%)
      point_spike    : n= 4988, rate=0.0136
    Threshold: 3.384629
    TEST PR-AUC=0.4484, F1=0.5121, Prec=0.5056, Recall=0.5188
    Per-Type PR-AUC:
      point_spike    : 0.4484

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.498/0.514
      mid : 0.515/0.544
      low : 0.371/0.470
                  spike  |         drop  |   collective

  [MA] Training Autoencoder (Oracle)...

Epoch 45: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 50.
  [MA] Autoencoder gespeichert.

  [MA_Oracle_AE]
    Anomaly Rate: 0.0136 (1.36%)
      point_spike    : n= 4988, rate=0.0136
    Threshold: 7.552816
    TEST PR-AUC=0.4686, F1=0.5053, Prec=0.5720, Recall=0.4525
    Per-Type PR-AUC:
      point_spike    : 0.4686

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.456/0.448
      mid : 0.511/0.515
      low : 0.494/0.575
                  spike  |         drop  |   collective

---
## Schritt 4: HD Source-Modelle trainieren

In [ ]:
# ══════════════════════════════════════════════════════════════
# 16 — HD Source Models: Train FC + AE on full HD Train
# ══════════════════════════════════════════════════════════════
print("\n--- HD Source Model Training ---")
hd_oracle_results, hd_fc_model, hd_ae_model, hd_meta = run_oracle_experiment(
    hd_data, cfg, "HD", MODELS_DIR,
    fc_model_preloaded=hd_fc_loaded,
    ae_model_preloaded=hd_ae_loaded,
)

hd_meta_copy = hd_meta.copy()
print("\nHD Source-Modelle trainiert/geladen und gespeichert.")

--- HD Source Model Training ---

  [HD] Training Forecaster (Oracle)...

Epoch 28: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 45: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 49: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 49: early stopping
Restoring model weights from the end of the best epoch: 41.
  [HD] Forecaster gespeichert.

  [HD_Oracle_FC]
    Anomaly Rate: 0.0128 (1.28%)
      point_spike    : n= 1245, rate=0.0063
      point_drop     : n=  149, rate=0.0008
      collective     : n= 1138, rate=0.0058
    Threshold: 4.018925
    TEST PR-AUC=0.3811, F1=0.4483, Prec=0.4587, Recall=0.4384
    Per-Type PR-AUC:
      point_spike    : 0.2721
      point_drop     : 0.0034
      collective     : 0.2704

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.340/0.404  |  0.011/0.005  |  0.398/0.445
      mid : 0.293/0.366  |  0.002/0.000  |  0.293/0.370
      low : 0.233/0.344  |  nan/nan  |  0.165/0.261
                  spike  |         drop  |   collective

  [HD] Training Autoencoder (Oracle)...

Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 49.
  [HD] Autoencoder gespeichert.

  [HD_Oracle_AE]
    Anomaly Rate: 0.0128 (1.28%)
      point_spike    : n= 1245, rate=0.0063
      point_drop     : n=  149, rate=0.0008
      collective     : n= 1138, rate=0.0058
    Threshold: 8.662125
    TEST PR-AUC=0.3326, F1=0.4106, Prec=0.4681, Recall=0.3657
    Per-Type PR-AUC:
      point_spike    : 0.2302
      point_drop     : 0.0015
      collective     : 0.2195

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.230/0.335  |  0.004/0.000  |  0.277/0.381
      mid : 0.259/0.346  |  0.001/0.000  |  0.260/0.355
      low : 0.225/0.357  |  nan/nan  |  0.148/0.273
                  spike  |         drop  |   collective

HD Source-Modelle trainiert/geladen und gespeichert.

#Moment

In [15]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Setup
# ══════════════════════════════════════════════════════════════
!pip install -q git+https://github.com/moment-timeseries-foundation-model/moment.git

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for momentfm (pyproject.toml) ... done

In [16]:
import torch
from momentfm import MOMENTPipeline

MOMENT_MODEL_NAME = "AutonLab/MOMENT-1-base"
MOMENT_BATCH_SIZE = 64

# MOMENT bekommt dieselbe Window-Size wie der Oracle (24)
# und dieselben Score-Features (n_lends, n_returns)
# Die Zeitfeatures geben wir MOMENT NICHT — es bekommt nur Demand,
# weil es ein Foundation Model ist, das Zeitfeatures nicht braucht/erwartet.
MOMENT_SCORE_FEATURES = cfg.ae_score_features  # ["n_lends", "n_returns"]

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
print("Model :", MOMENT_MODEL_NAME)
print("Score-Features:", MOMENT_SCORE_FEATURES)
print("Window:", cfg.ae_window_size)

Device: cuda
Model : AutonLab/MOMENT-1-base
Score-Features: ['n_lends', 'n_returns']
Window: 24

In [17]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Model + Scoring Helpers
# ══════════════════════════════════════════════════════════════

def load_moment_model(model_name=MOMENT_MODEL_NAME, device=device):
    model = MOMENTPipeline.from_pretrained(
        model_name,
        model_kwargs={"task_name": "reconstruction"}
    )
    model.init()
    model = model.to(device)
    model.eval()
    return model


def moment_reconstruction_scores(model, X_all_9feat, score_feature_indices,
                                  batch_size=MOMENT_BATCH_SIZE, device=device):
    """
    Fairer Vergleich: Nutzt dieselben X_all Fenster wie der Oracle (9 Features, 24 Steps).
    Extrahiert nur die Score-Features (n_lends, n_returns), schickt jede einzeln
    als univariate Reihe durch MOMENT, und mittelt den Last-Step-MSE über Channels.

    So sieht MOMENT exakt dieselben Daten und dasselbe Test-Set wie AE/FC.

    Args:
        model: MOMENT model
        X_all_9feat: [N, 24, 9] — dieselben Fenster wie Oracle
        score_feature_indices: Indizes von n_lends, n_returns in ae_features
        batch_size: Batch-Größe
        device: cuda/cpu

    Returns:
        scores: [N] — Last-Step-MSE gemittelt über Channels
    """
    n = X_all_9feat.shape[0]
    n_channels = len(score_feature_indices)
    scores_sum = np.zeros(n, dtype=np.float64)

    with torch.no_grad():
        for ch_pos, feat_idx in enumerate(score_feature_indices):
            ch_scores = []
            for i in range(0, n, batch_size):
                # Extrahiere einen Demand-Channel aus dem 9-Feature-Fenster
                xb = X_all_9feat[i:i+batch_size, :, feat_idx]       # [B, T]
                xb_t = torch.tensor(
                    xb[:, None, :], dtype=torch.float32, device=device
                )  # [B, 1, T]
                input_mask = torch.ones(
                    (xb_t.shape[0], xb_t.shape[-1]),
                    dtype=torch.long, device=device
                )

                out = model(x_enc=xb_t, input_mask=input_mask)
                xhat = out.reconstruction.detach().cpu().numpy()[:, 0, :]  # [B, T]

                # Last-Step-MSE — identisch zum Oracle AE Scoring
                err_last = ((xb - xhat) ** 2)[:, -1]
                ch_scores.append(err_last.astype(np.float64))

            scores_sum += np.concatenate(ch_scores)

    return (scores_sum / n_channels).astype(np.float32)

In [ ]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Zero-Shot on MA (gleiche Daten wie Oracle)
# ══════════════════════════════════════════════════════════════

# Score-Feature-Indizes in ae_features bestimmen
score_feat_idx = [ae_features.index(f) for f in MOMENT_SCORE_FEATURES]
print(f"Score-Features: {MOMENT_SCORE_FEATURES}")
print(f"Indizes in ae_features: {score_feat_idx}")

# Sanity Check: gleiche Daten wie Oracle
print(f"\nOracle X_all shape: {ma_data['X_all'].shape}")
print(f"Oracle meta  shape: {ma_data['meta_all'].shape}")
print(f"Test-Punkte Oracle: {(ma_data['meta_all']['split_eval'] == 'test').sum()}")

# --- Zero-Shot ---
moment_zs_model = load_moment_model()

# Nutze exakt ma_data["X_all"] — dieselben Fenster wie der Oracle
moment_zs_meta = ma_data["meta_all"].copy()
moment_zs_meta["score_moment_raw"] = moment_reconstruction_scores(
    moment_zs_model,
    ma_data["X_all"],             # <-- gleiche Daten wie Oracle
    score_feat_idx,
    batch_size=MOMENT_BATCH_SIZE,
    device=device
)

# Z-Norm identisch wie bei Oracle (Hour × Station)
moment_zs_meta = znorm_score_by_hour_station(
    moment_zs_meta,
    raw_score_col="score_moment_raw",
    val_start=train_end_ma,
    test_start=val_end_ma,
    new_col="score_moment_znorm_hs"
)

# Evaluation auf exakt demselben Test-Set
moment_zs_results = evaluate_v17b(
    moment_zs_meta,
    score_col="score_moment_znorm_hs",
    experiment_name="MA_MOMENT_ZeroShot",
    val_start=train_end_ma,
    test_start=val_end_ma
)

Score-Features: ['n_lends', 'n_returns']
Indizes in ae_features: [0, 1]

Oracle X_all shape: (1981139, 24, 9)
Oracle meta  shape: (1981139, 78)
Test-Punkte Oracle: 367992

config.json:   0%|          | 0.00/949 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/454M [00:00<?, ?B/s]

  [MA_MOMENT_ZeroShot]
    Anomaly Rate: 0.0136 (1.36%)
      point_spike    : n= 4988, rate=0.0136
    Threshold: 7.093250
    TEST PR-AUC=0.4711, F1=0.5038, Prec=0.5705, Recall=0.4511
    Per-Type PR-AUC:
      point_spike    : 0.4711

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.427/0.435
      mid : 0.530/0.514
      low : 0.525/0.586
                  spike  |         drop  |   collective

In [ ]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Fine-Tune Helpers
# ══════════════════════════════════════════════════════════════
from torch.utils.data import DataLoader, TensorDataset

MOMENT_FT_EPOCHS = 5
MOMENT_FT_BATCH_SIZE = 32
MOMENT_FT_LR = 1e-4
MOMENT_FT_HEAD_ONLY = True
MOMENT_FT_MAX_TRAIN_WINDOWS = None


def maybe_subsample(X, max_n=None, seed=42):
    if (max_n is None) or (len(X) <= max_n):
        return X
    rng = np.random.RandomState(seed)
    idx = rng.choice(len(X), size=max_n, replace=False)
    return X[idx]


def make_moment_loaders_from_oracle_data(X_train_9feat, X_val_9feat,
                                          score_feat_idx, batch_size):
    """
    Extrahiert Score-Features aus den 9-Feature-Oracle-Fenstern
    und baut DataLoader für MOMENT Fine-Tune.
    Shape: [N, T, 9] -> [N, T, 2] (nur n_lends, n_returns)
    """
    X_train_demand = X_train_9feat[:, :, score_feat_idx].astype(np.float32)
    X_val_demand   = X_val_9feat[:, :, score_feat_idx].astype(np.float32)

    train_ds = TensorDataset(torch.from_numpy(X_train_demand))
    val_ds   = TensorDataset(torch.from_numpy(X_val_demand))

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False, drop_last=False)

    return train_loader, val_loader


def set_trainable_head_only(model):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.head.parameters():
        p.requires_grad = True


def set_trainable_all(model):
    for p in model.parameters():
        p.requires_grad = True


def fine_tune_moment_reconstruction(
    model,
    train_loader,
    val_loader,
    epochs=MOMENT_FT_EPOCHS,
    lr=MOMENT_FT_LR,
    head_only=MOMENT_FT_HEAD_ONLY,
    save_path=None,
):
    """
    Fine-Tune MOMENT auf Rekonstruktion OHNE Masking.
    Ziel: Modell lernt normales Demand-Pattern zu rekonstruieren,
    Anomalien erzeugen dann höheren Rekonstruktionsfehler.
    """
    if head_only:
        set_trainable_head_only(model)
        print("Fine-Tune Mode: HEAD ONLY")
    else:
        set_trainable_all(model)
        print("Fine-Tune Mode: FULL MODEL")

    optimizer = torch.optim.Adam(
        [p for p in model.parameters() if p.requires_grad], lr=lr
    )
    criterion = torch.nn.MSELoss()

    best_val = np.inf
    best_state = None
    history = []

    for epoch in range(1, epochs + 1):
        model.train()
        train_losses = []

        for (batch_x,) in train_loader:
            # batch_x: [B, T, C] -> pro Channel univariat [B*C, 1, T]
            B, T, C = batch_x.shape
            batch_x = batch_x.to(device)
            x_flat = batch_x.permute(0, 2, 1).reshape(B * C, 1, T)  # [B*C, 1, T]
            input_mask = torch.ones(
                (x_flat.shape[0], T), dtype=torch.long, device=device
            )

            # Kein Masking — reines Rekonstruktionstraining
            output = model(x_enc=x_flat, input_mask=input_mask)
            loss = criterion(output.reconstruction, x_flat)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())

        model.eval()
        val_losses = []
        with torch.no_grad():
            for (batch_x,) in val_loader:
                B, T, C = batch_x.shape
                batch_x = batch_x.to(device)
                x_flat = batch_x.permute(0, 2, 1).reshape(B * C, 1, T)
                input_mask = torch.ones(
                    (x_flat.shape[0], T), dtype=torch.long, device=device
                )
                output = model(x_enc=x_flat, input_mask=input_mask)
                loss = criterion(output.reconstruction, x_flat)
                val_losses.append(loss.item())

        train_loss = float(np.mean(train_losses))
        val_loss   = float(np.mean(val_losses))
        history.append({"epoch": epoch, "train_loss": train_loss, "val_loss": val_loss})
        improved = " ✓" if val_loss < best_val else ""
        print(f"  Epoch {epoch:02d} | train={train_loss:.6f} | val={val_loss:.6f}{improved}")

        if val_loss < best_val:
            best_val = val_loss
            best_state = {k: v.detach().cpu().clone()
                          for k, v in model.state_dict().items()}

    if best_state is not None:
        model.load_state_dict(best_state)

    if save_path is not None:
        torch.save(model.state_dict(), save_path)
        print(f"  Saved: {save_path}")

    return model, pd.DataFrame(history)

In [ ]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Fine-Tune on MA train-normal, evaluate on MA
# ══════════════════════════════════════════════════════════════

# Nicht mehr auf x_All wie zero shot

# Training nutzt weiterhin Train-Normal-Fenster (die braucht MOMENT zum Lernen)
X_train_ft = maybe_subsample(ma_data["X_train"], MOMENT_FT_MAX_TRAIN_WINDOWS, seed=42)
X_val_ft   = ma_data["X_val_clean"]

print(f"FT train windows: {X_train_ft.shape}")
print(f"FT val windows  : {X_val_ft.shape}")

train_loader, val_loader = make_moment_loaders_from_oracle_data(
    X_train_ft, X_val_ft, score_feat_idx,
    batch_size=MOMENT_FT_BATCH_SIZE
)

moment_ft_model = load_moment_model()

moment_ft_model, moment_ft_history = fine_tune_moment_reconstruction(
    moment_ft_model,
    train_loader=train_loader,
    val_loader=val_loader,
    epochs=MOMENT_FT_EPOCHS,
    lr=MOMENT_FT_LR,
    head_only=MOMENT_FT_HEAD_ONLY,
    save_path=f"{MODELS_DIR}/ma_moment_ft.pt"
)

# Scoring nur auf Val+Test (gleicher Subset wie Zero-Shot)
moment_ft_meta = meta_valtest.drop(
    columns=[c for c in meta_valtest.columns if "moment" in c],
    errors="ignore"
).copy()

moment_ft_meta["score_moment_ft_raw"] = moment_reconstruction_scores(
    moment_ft_model,
    X_valtest,
    score_feat_idx,
    batch_size=MOMENT_BATCH_SIZE,
    device=device
)

moment_ft_meta = znorm_score_by_hour_station(
    moment_ft_meta,
    raw_score_col="score_moment_ft_raw",
    val_start=train_end_ma,
    test_start=val_end_ma,
    new_col="score_moment_ft_znorm_hs"
)

moment_ft_results = evaluate_v17b(
    moment_ft_meta,
    score_col="score_moment_ft_znorm_hs",
    experiment_name="MA_MOMENT_FineTune",
    val_start=train_end_ma,
    test_start=val_end_ma
)

print("\n--- Fine-Tune History ---")
print(moment_ft_history.to_string(index=False))

In [ ]:
# ══════════════════════════════════════════════════════════════
# MOMENT — Vergleich (alle auf exakt demselben Test-Set)
# ══════════════════════════════════════════════════════════════
rows = []

if "oracle_results" in globals():
    if "FC_Oracle" in oracle_results:
        r = oracle_results["FC_Oracle"]
        rows.append({
            "Experiment": r["experiment"],
            "Paradigma": "Forecast",
            "Training": "100% MA Train",
            "PR-AUC": r.get("test_pr_auc"),
            "F1": r.get("test_f1"),
            "Precision": r.get("test_prec"),
            "Recall": r.get("test_recall"),
        })
    if "AE_Oracle" in oracle_results:
        r = oracle_results["AE_Oracle"]
        rows.append({
            "Experiment": r["experiment"],
            "Paradigma": "Reconstruction",
            "Training": "100% MA Train",
            "PR-AUC": r.get("test_pr_auc"),
            "F1": r.get("test_f1"),
            "Precision": r.get("test_prec"),
            "Recall": r.get("test_recall"),
        })

rows.append({
    "Experiment": moment_zs_results["experiment"],
    "Paradigma": "Reconstruction",
    "Training": "Zero-Shot (pretrained)",
    "PR-AUC": moment_zs_results.get("test_pr_auc"),
    "F1": moment_zs_results.get("test_f1"),
    "Precision": moment_zs_results.get("test_prec"),
    "Recall": moment_zs_results.get("test_recall"),
})

rows.append({
    "Experiment": moment_ft_results["experiment"],
    "Paradigma": "Reconstruction",
    "Training": "FT Head on MA Train",
    "PR-AUC": moment_ft_results.get("test_pr_auc"),
    "F1": moment_ft_results.get("test_f1"),
    "Precision": moment_ft_results.get("test_prec"),
    "Recall": moment_ft_results.get("test_recall"),
})

comparison_df = pd.DataFrame(rows).sort_values("PR-AUC", ascending=False).reset_index(drop=True)
print(comparison_df.to_string(index=True))

# Hinweis zur Interpretation
print("\n" + "="*70)
print("INTERPRETATION:")
print("  • FC-Oracle vs MOMENT: Unterschiedliches Paradigma (Forecast vs Reconstruction).")
print("    FC sieht die Anomalie NICHT im Input → fairer nur als obere Schranke.")
print("  • AE-Oracle vs MOMENT: Gleiches Paradigma (Reconstruction, Last-Step-MSE).")
print("    → Direkter, fairer Vergleich. Gleiche Daten, gleiche Evaluation.")
print("  • MOMENT ZS vs FT: Bringt domänenspezifisches Fine-Tuning etwas?")
print("="*70)

---
## Multi-City Oracle + MOMENT Loop (für Modellfixierung und spätere Gewichtung)

Dieser Block erweitert V20d um mehrere Zielstädte.  
Er speichert:

- **Summary-Metriken** je Stadt und Modell
- **Fenster-/Sample-Level Scores** je Stadt und Modell
- **Thresholds / Metadaten** für spätere demand-gewichtete Auswertungen

Der Block verändert **nicht** das Modell selbst, sondern macht die Auswertung über mehrere Städte reproduzierbar.

In [19]:

# ══════════════════════════════════════════════════════════════
# MC-1 — City Discovery + Multi-City Config
# ══════════════════════════════════════════════════════════════
import re
from pathlib import Path

MULTICITY_RESULTS_DIR = f"{RESULTS_DIR}/multicity"
MULTICITY_PRED_DIR    = f"{MULTICITY_RESULTS_DIR}/predictions"
MULTICITY_SUMMARY_DIR = f"{MULTICITY_RESULTS_DIR}/summary"
MULTICITY_MODEL_DIR   = f"{MULTICITY_RESULTS_DIR}/models"

os.makedirs(MULTICITY_RESULTS_DIR, exist_ok=True)
os.makedirs(MULTICITY_PRED_DIR, exist_ok=True)
os.makedirs(MULTICITY_SUMMARY_DIR, exist_ok=True)
os.makedirs(MULTICITY_MODEL_DIR, exist_ok=True)

def city_to_key(city_name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", city_name.lower()).strip("_")

def discover_city_demand_paths(cleaned_base: str):
    demand_root = Path(cleaned_base) / "demand"
    city_map = {}
    if not demand_root.exists():
        print(f"WARNUNG: demand_root nicht gefunden: {demand_root}")
        return city_map

    for city_dir in sorted(demand_root.iterdir()):
        if not city_dir.is_dir():
            continue
        p = city_dir / "demand_cleaned.parquet"
        if p.exists():
            city_map[city_dir.name] = str(p)
    return city_map

DISCOVERED_CITY_DEMAND = discover_city_demand_paths(CLEANED_BASE)

# bisherige CITY_DEMAND-Einträge beibehalten, aber um alle gefundenen Städte erweitern
CITY_DEMAND_ALL = {**DISCOVERED_CITY_DEMAND, **CITY_DEMAND}

print(f"Gefundene Städte: {len(CITY_DEMAND_ALL)}")
print(sorted(CITY_DEMAND_ALL.keys())[:20])

# HIER Zielstädte setzen:
TARGET_CITIES = [
    "Mannheim",
    "Heidelberg",
    "Bochum",
    "Braunschweig",
    "Dortmund",
    "Duisburg",
    "Essen",
    "Marburg",
    "Winsen (Luhe)",

]

TARGET_CITIES = [c for c in TARGET_CITIES if c in CITY_DEMAND_ALL]
print("\nTarget Cities:", TARGET_CITIES)

Gefundene Städte: 17
['Bochum', 'Braunschweig', 'Dortmund', 'Duisburg', 'Essen', 'Freiburg', 'Gießen', 'Heidelberg', 'Kaiserslautern', 'Kassel', 'Leverkusen', 'Ludwigshafen', 'Mannheim', 'Marburg', 'Offenburg', 'Wiesbaden', 'Winsen (Luhe)']

Target Cities: ['Mannheim', 'Heidelberg', 'Bochum', 'Braunschweig', 'Dortmund', 'Duisburg', 'Essen', 'Marburg', 'Winsen (Luhe)']

In [20]:

# ══════════════════════════════════════════════════════════════
# MC-2 — Speicherung für spätere Gewichtung / Re-Scoring
# ══════════════════════════════════════════════════════════════
def save_window_level_scores(meta: pd.DataFrame,
                             city_name: str,
                             model_name: str,
                             out_dir: str,
                             score_cols=None,
                             extra_cols=None):
    """
    Speichert Fenster-/Sample-Level Scores so, dass spätere demand-gewichtete
    Auswertungen OHNE erneutes Training möglich sind.
    """
    score_cols = score_cols or []
    extra_cols = extra_cols or []

    base_cols = [
        "station_id", "hour_ts", "split_eval", "label_eval",
        "synth_label", "synth_type", "demand_regime"
    ]
    cols = [c for c in base_cols + score_cols + extra_cols if c in meta.columns]

    out = meta[cols].copy()
    out["city"] = city_name
    out["city_key"] = city_to_key(city_name)
    out["model"] = model_name

    # nützlich für spätere station-basierte Gewichtung
    station_activity = (
        out.groupby("station_id")
           .agg(
               n_windows=("station_id", "size"),
               n_test_windows=("split_eval", lambda s: int((s == "test").sum())),
               n_test_anom=("synth_label", lambda s: int(((out.loc[s.index, "split_eval"] == "test") & (s == 1)).sum()))
           )
           .reset_index()
    )
    out = out.merge(station_activity, on="station_id", how="left")

    fpath = f"{out_dir}/{city_to_key(city_name)}__{model_name}__window_scores.parquet"
    out.to_parquet(fpath, index=False)
    print(f"Gespeichert: {fpath} | rows={len(out):,}")
    return fpath

def flatten_result_dict(d: dict, city_name: str, model_name: str):
    row = {}
    for k, v in d.items():
        if isinstance(v, pd.DataFrame):
            continue
        row[k] = v
    row["city"] = city_name
    row["city_key"] = city_to_key(city_name)
    row["model"] = model_name
    return row

def save_regime_detail_if_present(result_dict: dict, city_name: str, model_name: str, out_dir: str):
    if "regime_detail" in result_dict and isinstance(result_dict["regime_detail"], pd.DataFrame):
        df = result_dict["regime_detail"].copy()
        df["city"] = city_name
        df["city_key"] = city_to_key(city_name)
        df["model"] = model_name
        fpath = f"{out_dir}/{city_to_key(city_name)}__{model_name}__regime_detail.csv"
        df.to_csv(fpath, index=False)
        return fpath
    return None

def add_station_demand_weight(meta: pd.DataFrame):
    """
    Fügt eine einfache Stationsaktivität hinzu, damit später
    High-/Low-Demand-Gewichtungen direkt berechnet werden können.
    """
    meta = meta.copy()
    demand_col_candidates = ["original_n_lends", "n_lends"]
    demand_col = next((c for c in demand_col_candidates if c in meta.columns), None)

    if demand_col is None:
        # fallback: nur Test-Windows zählen
        stat = meta.groupby("station_id").size().rename("station_activity_raw").reset_index()
    else:
        stat = (
            meta.groupby("station_id")[demand_col]
                .mean()
                .rename("station_activity_raw")
                .reset_index()
        )

    stat["station_activity_log1p"] = np.log1p(stat["station_activity_raw"].clip(lower=0))
    q33 = stat["station_activity_raw"].quantile(0.33)
    q67 = stat["station_activity_raw"].quantile(0.67)
    stat["station_activity_group"] = np.where(
        stat["station_activity_raw"] <= q33, "low",
        np.where(stat["station_activity_raw"] >= q67, "high", "medium")
    )

    meta = meta.merge(stat, on="station_id", how="left")
    return meta

In [25]:
# ══════════════════════════════════════════════════════════════
# X — Scaler + Sequenzen pro Stadt (generisch für Multi-City)
# ══════════════════════════════════════════════════════════════
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

ae_features = cfg.ae_features
score_features = cfg.ae_score_features
context_steps = cfg.ae_window_size - 1   # z. B. 23

def build_sequences_for_city(
    df_clean,
    df_inj,
    train_end,
    val_end,
    city_name,
    scaler_ext=None
):
    """
    Generische Sequenz-Erstellung pro Stadt.

    Parameter
    ----------
    df_clean : pd.DataFrame
        Clean-Daten der Stadt.
    df_inj : pd.DataFrame
        Injizierte Daten der Stadt.
    train_end : pd.Timestamp
        Split-Grenze Train/Val.
    val_end : pd.Timestamp
        Split-Grenze Val/Test.
    city_name : str
        Name der Stadt für Logging.
    scaler_ext : sklearn-Scaler | None
        Optional externer Scaler, z. B. für Transfer.
        Wenn None, wird der Scaler auf den Train-Daten dieser Stadt gefittet.

    Returns
    -------
    dict mit:
        X_all, meta_all, scaler,
        X_train, X_val_clean,
        train_normal_mask, val_normal_mask,
        train_end, val_end
    """

    # ----------------------------------------------------------
    # 1) Daten vorbereiten
    # ----------------------------------------------------------
    df_c = (
        df_clean.copy()
        .sort_values(["station_id", "hour_ts"])
        .reset_index(drop=True)
    )

    df_inj_s = (
        df_inj.copy()
        .sort_values(["station_id", "hour_ts"])
        .reset_index(drop=True)
    )

    # ----------------------------------------------------------
    # 2) Zeitstempel harmonisieren: alles UTC tz-aware
    #    -> verhindert tz-naive vs tz-aware Vergleichsfehler
    # ----------------------------------------------------------
    df_c["hour_ts"] = pd.to_datetime(df_c["hour_ts"], utc=True)
    df_inj_s["hour_ts"] = pd.to_datetime(df_inj_s["hour_ts"], utc=True)
    train_end = pd.to_datetime(train_end, utc=True)
    val_end   = pd.to_datetime(val_end, utc=True)

    # ----------------------------------------------------------
    # 3) NA-Handling auf Feature-Spalten
    # ----------------------------------------------------------
    df_c = df_c.dropna(subset=ae_features)
    df_inj_s = df_inj_s.dropna(subset=ae_features)

    # ----------------------------------------------------------
    # 4) Scaler fitten oder extern übernehmen
    # ----------------------------------------------------------
    train_mask_sc = df_c["hour_ts"] < train_end

    if scaler_ext is None:
        scaler = StandardScaler()
        scaler.fit(df_c.loc[train_mask_sc, ae_features])
        print(f"  [{city_name}] Scaler gefittet auf {train_mask_sc.sum():,} Train-Zeilen")
    else:
        scaler = scaler_ext
        print(f"  [{city_name}] Externer Scaler verwendet")

    # ----------------------------------------------------------
    # 5) Injizierte Daten skalieren
    # ----------------------------------------------------------
    df_inj_scaled = df_inj_s.copy()
    df_inj_scaled.loc[:, ae_features] = scaler.transform(df_inj_s[ae_features])

    # Relevante Metadaten erhalten
    meta_cols_to_keep = [
        "synth_label",
        "synth_type",
        "original_n_lends",
        "original_n_returns",
        "demand_regime",
        "label_eval",
        "station_id",
        "hour_ts",
        "n_lends",
        "n_returns",
    ]
    for col in meta_cols_to_keep:
        if col in df_inj_s.columns:
            df_inj_scaled[col] = df_inj_s[col].values

    # ----------------------------------------------------------
    # 6) Sequenzen bauen
    # ----------------------------------------------------------
    X_all, meta_all = make_sequences_with_window_labels(
        df_inj_scaled,
        feature_cols=ae_features,
        window_size=cfg.ae_window_size,
        synth_label_col="synth_label",
        synth_type_col="synth_type",
        require_contiguous=cfg.require_contiguous,
        agg_minutes=cfg.aggregation_minutes
    )

    # Falls hour_ts aus der Sequenzfunktion zurückkommt, ebenfalls harmonisieren
    if "hour_ts" in meta_all.columns:
        meta_all["hour_ts"] = pd.to_datetime(meta_all["hour_ts"], utc=True)

    # ----------------------------------------------------------
    # 7) Eval-Splits setzen
    # ----------------------------------------------------------
    meta_all["split_eval"] = np.where(
        meta_all["hour_ts"] < train_end, "train",
        np.where(meta_all["hour_ts"] < val_end, "val", "test")
    )

    print(f"  [{city_name}] Sequenzen: {X_all.shape}")
    print(f"  [{city_name}] Split: {meta_all['split_eval'].value_counts().to_dict()}")

    # ----------------------------------------------------------
    # 8) Nur normale Fenster für Train / Val-Clean
    # ----------------------------------------------------------
    train_normal = (
        (meta_all["split_eval"] == "train") &
        (meta_all["label_eval"] == "normal")
    )

    val_normal = (
        (meta_all["split_eval"] == "val") &
        (meta_all["synth_label"] == 0) &
        (meta_all["label_eval"] == "normal")
    )

    X_train = X_all[train_normal.values]
    X_val_c = X_all[val_normal.values]

    print(f"  [{city_name}] X_train (normal): {X_train.shape}, X_val (normal): {X_val_c.shape}")

    return {
        "X_all": X_all,
        "meta_all": meta_all,
        "scaler": scaler,
        "X_train": X_train,
        "X_val_clean": X_val_c,
        "train_normal_mask": train_normal,
        "val_normal_mask": val_normal,
        "train_end": train_end,
        "val_end": val_end,
    }

In [31]:
# ══════════════════════════════════════════════════════════════
# MC-ORACLE — Exakte V20d-Funktionsbasis für Oracle/Multi-City
# ══════════════════════════════════════════════════════════════

ANOM_TYPES = ["point_spike"]  # V20d: only spikes
REGIMES    = ["high", "mid", "low"]

# -------------------------------------------------------------
# 6 — Model Builders (AE + Forecaster)
# -------------------------------------------------------------
def build_lstm_autoencoder(
    n_input_features: int,
    window_size: int,
    latent_dim: int = 32,
    n_layers: int = 2,
    dropout: float = 0.1,
    bidirectional: bool = False,
    n_output_features: Optional[int] = None,
) -> keras.Model:
    n_output_features = n_output_features or n_input_features
    inputs = keras.Input(shape=(window_size, n_input_features), name="encoder_input")
    x = inputs
    for i in range(n_layers):
        return_sequences = (i < n_layers - 1)
        lstm = layers.LSTM(
            latent_dim, return_sequences=return_sequences,
            dropout=dropout, name=f"encoder_lstm_{i+1}"
        )
        x = layers.Bidirectional(lstm, name=f"encoder_bi_{i+1}")(x) if bidirectional else lstm(x)
    latent = x
    x = layers.RepeatVector(window_size, name="repeat_vector")(latent)
    for i in range(n_layers):
        lstm = layers.LSTM(
            latent_dim, return_sequences=True,
            dropout=dropout, name=f"decoder_lstm_{i+1}"
        )
        x = layers.Bidirectional(lstm, name=f"decoder_bi_{i+1}")(x) if bidirectional else lstm(x)
    outputs = layers.TimeDistributed(
        layers.Dense(n_output_features), name="output_dense"
    )(x)
    return keras.Model(inputs, outputs, name="lstm_autoencoder")


def build_lstm_forecaster(
    n_input_features: int,
    n_output_features: int,
    context_steps: int = 23,
    latent_dim: int = 32,
    n_layers: int = 2,
    dropout: float = 0.1,
) -> keras.Model:
    inputs = keras.Input(shape=(context_steps, n_input_features), name="forecast_input")
    x = inputs
    for i in range(n_layers):
        return_sequences = (i < n_layers - 1)
        x = layers.LSTM(
            latent_dim, return_sequences=return_sequences,
            dropout=dropout, name=f"forecast_lstm_{i+1}"
        )(x)
    outputs = layers.Dense(n_output_features, name="forecast_output")(x)
    return keras.Model(inputs, outputs, name="lstm_forecaster")


def train_model_generic(model, X_train, Y_train, X_val, Y_val,
                        epochs, lr, batch_size, early_stop, verbose=1):
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr, clipnorm=1.0),
        loss="mse"
    )
    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=early_stop,
            restore_best_weights=True, verbose=1
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=4, verbose=1
        )
    ]
    history = model.fit(
        X_train, Y_train,
        validation_data=(X_val, Y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=verbose
    )
    return model, history


# -------------------------------------------------------------
# 7 — Scoring Helpers (AE + Forecaster)
# -------------------------------------------------------------
def predict_in_batches(model, X, batch_size=2048):
    preds = []
    for i in range(0, len(X), batch_size):
        preds.append(model.predict(X[i:i + batch_size], verbose=0))
    return np.concatenate(preds, axis=0) if preds else np.empty((0, 0, 0), dtype=np.float32)


def compute_reconstruction_scores(X, X_hat, input_features, score_features,
                                  mode="last_step_mean"):
    score_idx = [input_features.index(c) for c in score_features]
    err = (X - X_hat) ** 2
    err_score = err[:, :, score_idx]
    if mode == "last_step_mean":
        return err_score[:, -1, :].mean(axis=1)
    elif mode == "window_mean":
        return err_score.mean(axis=(1, 2))
    elif mode == "max_over_features":
        return err_score[:, -1, :].max(axis=1)
    else:
        raise ValueError(f"Unbekannter mode: {mode}")


def compute_forecast_scores(model, X_input, X_actual_last_step, score_features,
                            ae_features, mode="directional"):
    X_pred = predict_in_batches(model, X_input, batch_size=2048)
    score_idx = [ae_features.index(f) for f in score_features]
    X_actual = X_actual_last_step[:, score_idx]
    err = (X_pred - X_actual) ** 2
    if mode == "mean":
        return err.mean(axis=1)
    elif mode == "max":
        return err.max(axis=1)
    elif mode == "directional":
        abs_err = np.abs(X_pred - X_actual)
        denom = np.maximum(np.maximum(np.abs(X_actual), np.abs(X_pred)), 1e-6)
        rel_err = abs_err / denom
        return 0.5 * abs_err.mean(axis=1) + 0.5 * rel_err.mean(axis=1)
    else:
        raise ValueError(f"Unbekannter mode: {mode}")


# -------------------------------------------------------------
# 8 — Z-Normalisierung (Hour + Hour×Station)
# -------------------------------------------------------------
def znorm_score_by_hour(meta_df, raw_score_col, val_start, test_start,
                        new_col="score_znorm_hour"):
    meta = meta_df.copy()
    val_normal = (
        (meta["hour_ts"] >= val_start) &
        (meta["hour_ts"] < test_start) &
        (meta["synth_label"] == 0)
    )
    hour_col = meta["hour_ts"].dt.hour
    mu_per_hour = {}
    std_per_hour = {}
    for h in range(24):
        vals = meta.loc[val_normal & (hour_col == h), raw_score_col].dropna()
        mu_per_hour[h]  = vals.mean() if len(vals) > 0 else 0.0
        std_per_hour[h] = vals.std()  if len(vals) > 1 else 1.0

    hours = hour_col.values
    raw   = meta[raw_score_col].values
    znorm = np.zeros_like(raw)
    for i in range(len(raw)):
        h = hours[i]
        znorm[i] = (raw[i] - mu_per_hour[h]) / max(std_per_hour[h], 1e-8)
    meta[new_col] = znorm
    return meta, mu_per_hour, std_per_hour


def znorm_score_by_hour_station(meta_df, raw_score_col, val_start, test_start,
                                new_col="score_znorm_hour_station"):
    meta = meta_df.copy()
    val_normal = (
        (meta["hour_ts"] >= val_start) &
        (meta["hour_ts"] < test_start) &
        (meta["synth_label"] == 0)
    )
    hour_col = meta["hour_ts"].dt.hour
    meta["_hour_tmp"] = hour_col

    stats = (
        meta[val_normal]
        .groupby(["station_id", "_hour_tmp"])[raw_score_col]
        .agg(["mean", "std", "count"])
        .reset_index()
    )
    global_stats = (
        meta[val_normal]
        .groupby("_hour_tmp")[raw_score_col]
        .agg(["mean", "std"])
        .reset_index()
        .rename(columns={"mean": "g_mean", "std": "g_std"})
    )
    stats = stats.merge(global_stats, on="_hour_tmp", how="left")
    stats["use_mean"] = np.where(stats["count"] >= 10, stats["mean"], stats["g_mean"])
    stats["use_std"]  = np.where(stats["count"] >= 10, stats["std"],  stats["g_std"])
    stats["use_std"]  = stats["use_std"].clip(lower=1e-8)

    meta = meta.merge(
        stats[["station_id", "_hour_tmp", "use_mean", "use_std"]],
        on=["station_id", "_hour_tmp"], how="left"
    )
    meta["use_mean"] = meta["use_mean"].fillna(0.0)
    meta["use_std"]  = meta["use_std"].fillna(1.0).clip(lower=1e-8)
    meta[new_col] = (meta[raw_score_col] - meta["use_mean"]) / meta["use_std"]
    meta = meta.drop(columns=["_hour_tmp", "use_mean", "use_std"])
    return meta


# -------------------------------------------------------------
# 11 — V17b Unified Evaluation
# -------------------------------------------------------------
def evaluate_v17b(
    meta: pd.DataFrame,
    score_col: str,
    experiment_name: str,
    val_start: pd.Timestamp,
    test_start: pd.Timestamp,
    verbose: bool = True
) -> Dict:
    meta = meta.copy()
    meta["split_eval"] = np.where(
        meta["hour_ts"] < val_start, "train",
        np.where(meta["hour_ts"] < test_start, "val", "test")
    )

    val_m  = meta[meta["split_eval"] == "val"].copy()
    test_m = meta[meta["split_eval"] == "test"].copy()

    if len(val_m) == 0 or len(test_m) == 0:
        print(f"  [{experiment_name}] WARNUNG: Keine VAL/TEST-Daten!")
        return {}

    results = {"experiment": experiment_name, "n_val": len(val_m), "n_test": len(test_m)}

    # --- Anomaly Rates ---
    n_test_total = len(test_m)
    n_test_anom  = (test_m["synth_label"] == 1).sum()
    results["anomaly_rate_total"] = n_test_anom / n_test_total

    for atype in ANOM_TYPES:
        n_t = (test_m["synth_type"] == atype).sum()
        results[f"rate_{atype}"] = n_t / n_test_total
        results[f"n_{atype}"] = int(n_t)

    # --- VAL: Threshold bestimmen ---
    y_val = val_m["synth_label"].astype(int).values
    s_val = val_m[score_col].values

    threshold = None
    if len(np.unique(y_val)) > 1:
        prec_v, rec_v, thr_v = precision_recall_curve(y_val, s_val)
        results["val_pr_auc"] = average_precision_score(y_val, s_val)
        if len(thr_v) > 0:
            f1_v = 2 * prec_v[:-1] * rec_v[:-1] / (prec_v[:-1] + rec_v[:-1] + 1e-12)
            best_idx = np.argmax(f1_v)
            threshold = float(thr_v[best_idx])
            results["val_best_f1"] = float(f1_v[best_idx])
            results["val_threshold"] = threshold

    if threshold is None:
        val_norm = val_m[val_m["synth_label"] == 0][score_col]
        if len(val_norm) > 0:
            threshold = float(val_norm.quantile(0.99))
        else:
            threshold = float(test_m[score_col].quantile(0.99))
        results["val_threshold"] = threshold
        results["threshold_source"] = "fallback_99pct"

    # --- TEST: Global Metriken ---
    y_test = test_m["synth_label"].astype(int).values
    s_test = test_m[score_col].values
    p_test = (s_test >= threshold).astype(int)

    if len(np.unique(y_test)) > 1:
        results["test_pr_auc"]  = average_precision_score(y_test, s_test)
        results["test_roc_auc"] = roc_auc_score(y_test, s_test)
        results["test_f1"]      = f1_score(y_test, p_test, zero_division=0)
        results["test_prec"]    = precision_score(y_test, p_test, zero_division=0)
        results["test_recall"]  = recall_score(y_test, p_test, zero_division=0)

    # --- TEST: Per-Type ---
    for atype in ANOM_TYPES:
        type_mask = test_m["synth_type"] == atype
        normal_mask = test_m["synth_label"] == 0
        sub = test_m[type_mask | normal_mask].copy()
        n_anom = int(type_mask.sum())

        if n_anom > 0 and len(sub) > 0:
            y_t = (sub["synth_type"] == atype).astype(int).values
            y_s = sub[score_col].values
            if len(set(y_t)) > 1:
                results[f"pr_{atype}"] = average_precision_score(y_t, y_s)
            type_seqs = test_m[type_mask]
            detected = (type_seqs[score_col] >= threshold).sum()
            results[f"dr_{atype}"] = detected / len(type_seqs) if len(type_seqs) > 0 else 0.0
        else:
            results[f"pr_{atype}"] = None
            results[f"dr_{atype}"] = None

    # --- TEST: Per-Type x Per-Regime ---
    regime_rows = []
    for atype in ANOM_TYPES:
        for regime in REGIMES:
            rm = test_m["demand_regime"] == regime
            tm = test_m["synth_type"] == atype
            nm = test_m["synth_label"] == 0
            n_a = int((rm & tm).sum())
            n_n = int((rm & nm).sum())
            pr, f1_val, dr = None, None, None
            if n_a > 0 and n_n > 0:
                sub = test_m[(rm & tm) | (rm & nm)]
                y_t = (sub["synth_type"] == atype).astype(int).values
                y_s = sub[score_col].values
                pr = average_precision_score(y_t, y_s) if len(set(y_t)) > 1 else None
                p_sub = (y_s >= threshold).astype(int)
                f1_val = f1_score(y_t, p_sub, zero_division=0)
                detected = (test_m[rm & tm][score_col] >= threshold).sum()
                dr = detected / n_a
            regime_rows.append({
                "type": atype, "regime": regime,
                "n_anom": n_a, "pr_auc": pr, "f1": f1_val, "dr": dr
            })
    results["regime_detail"] = pd.DataFrame(regime_rows)

    if verbose:
        print(f"\n  [{experiment_name}]")
        print(f"    Anomaly Rate: {results['anomaly_rate_total']:.4f} ({results['anomaly_rate_total']*100:.2f}%)")
        for at in ANOM_TYPES:
            print(f"      {at:15s}: n={results[f'n_{at}']:5d}, rate={results[f'rate_{at}']:.4f}")
        print(f"    Threshold: {threshold:.6f}")
        print(f"    TEST PR-AUC={results.get('test_pr_auc', 'N/A'):.4f}, "
              f"F1={results.get('test_f1', 'N/A'):.4f}, "
              f"Prec={results.get('test_prec', 'N/A'):.4f}, "
              f"Recall={results.get('test_recall', 'N/A'):.4f}")
        print(f"    Per-Type PR-AUC:")
        for at in ANOM_TYPES:
            v = results.get(f'pr_{at}')
            print(f"      {at:15s}: {v:.4f}" if v is not None else f"      {at:15s}: N/A")
        print(f"\n    Type × Regime Matrix (PR-AUC / F1):")
        rd = results["regime_detail"]
        for regime in REGIMES:
            vals = []
            for atype in ANOM_TYPES:
                row = rd[(rd["type"] == atype) & (rd["regime"] == regime)].iloc[0]
                pr_s = f"{row['pr_auc']:.3f}" if row['pr_auc'] is not None else "  N/A"
                f1_s = f"{row['f1']:.3f}" if row['f1'] is not None else "  N/A"
                vals.append(f"{pr_s}/{f1_s}")
            print(f"      {regime:4s}: " + "  |  ".join(vals))
        print(f"            {'spike':>11s}  |  {'drop':>11s}  |  {'collective':>11s}")

    return results


# -------------------------------------------------------------
# 15 — Oracle Experiment
# -------------------------------------------------------------
def run_oracle_experiment(city_data, cfg, city_name, models_dir,
                          fc_model_preloaded=None, ae_model_preloaded=None):
    """Train or load both FC and AE on full city training data, then evaluate."""
    X_train = city_data["X_train"]
    X_val_c = city_data["X_val_clean"]
    X_all   = city_data["X_all"]
    meta    = city_data["meta_all"].copy()
    train_end = city_data["train_end"]
    val_end   = city_data["val_end"]

    score_idx = [ae_features.index(f) for f in score_features]
    results = {}

    # --- Forecaster ---
    if fc_model_preloaded is not None:
        print(f"\n  [{city_name}] Verwende vorgeladenen Forecaster.")
        fc_model = fc_model_preloaded
    else:
        print(f"\n  [{city_name}] Training Forecaster (Oracle)...")
        fc_model = build_lstm_forecaster(
            n_input_features=len(ae_features),
            n_output_features=len(score_features),
            context_steps=context_steps,
            latent_dim=cfg.ae_latent_dim,
            n_layers=2,
            dropout=cfg.ae_dropout,
        )

        X_fc_train = X_train[:, :context_steps, :]
        Y_fc_train = X_train[:, -1, :][:, score_idx]
        X_fc_val   = X_val_c[:, :context_steps, :]
        Y_fc_val   = X_val_c[:, -1, :][:, score_idx]

        fc_model, _ = train_model_generic(
            fc_model, X_fc_train, Y_fc_train, X_fc_val, Y_fc_val,
            epochs=cfg.ae_epochs, lr=cfg.ae_lr,
            batch_size=cfg.ae_batch_size, early_stop=cfg.ae_early_stop,
            verbose=0
        )
        fc_model.save(f"{models_dir}/{city_name.lower()}_oracle_forecaster.keras")
        print(f"  [{city_name}] Forecaster gespeichert.")

    X_fc_input = X_all[:, :context_steps, :]
    X_actual_last = X_all[:, -1, :]
    meta["score_fc_raw"] = compute_forecast_scores(
        fc_model, X_fc_input, X_actual_last,
        score_features, ae_features, mode="directional"
    )
    meta = znorm_score_by_hour_station(
        meta, "score_fc_raw", train_end, val_end,
        new_col="score_fc_znorm_hs"
    )
    results["FC_Oracle"] = evaluate_v17b(
        meta, "score_fc_znorm_hs", f"{city_name}_Oracle_FC",
        val_start=train_end, test_start=val_end
    )

    # --- Autoencoder ---
    if ae_model_preloaded is not None:
        print(f"\n  [{city_name}] Verwende vorgeladenen Autoencoder.")
        ae_model = ae_model_preloaded
    else:
        print(f"\n  [{city_name}] Training Autoencoder (Oracle)...")
        ae_model = build_lstm_autoencoder(
            n_input_features=len(ae_features),
            window_size=cfg.ae_window_size,
            latent_dim=cfg.ae_latent_dim,
            n_layers=cfg.ae_layers,
            dropout=cfg.ae_dropout,
            bidirectional=cfg.use_bidirectional,
        )

        ae_model, _ = train_model_generic(
            ae_model, X_train, X_train, X_val_c, X_val_c,
            epochs=cfg.ae_epochs, lr=cfg.ae_lr,
            batch_size=cfg.ae_batch_size, early_stop=cfg.ae_early_stop,
            verbose=0
        )
        ae_model.save(f"{models_dir}/{city_name.lower()}_oracle_autoencoder.keras")
        print(f"  [{city_name}] Autoencoder gespeichert.")

    X_hat = predict_in_batches(ae_model, X_all)
    meta["score_ae_raw"] = compute_reconstruction_scores(
        X_all, X_hat, ae_features, score_features, mode="last_step_mean"
    )
    meta = znorm_score_by_hour_station(
        meta, "score_ae_raw", train_end, val_end,
        new_col="score_ae_znorm_hs"
    )
    results["AE_Oracle"] = evaluate_v17b(
        meta, "score_ae_znorm_hs", f"{city_name}_Oracle_AE",
        val_start=train_end, test_start=val_end
    )

    return results, fc_model, ae_model, meta

In [26]:
# ══════════════════════════════════════════════════════════════
# MC-3 — Mehrere Städte laden, injecten, Sequenzen bauen
# ══════════════════════════════════════════════════════════════
multi_city_data = {}
multi_city_frames = {}

for i, city_name in enumerate(TARGET_CITIES, start=1):
    print("\n" + "="*90)
    print(f"[{i}/{len(TARGET_CITIES)}] CITY PIPELINE: {city_name}")
    print("="*90)

    df_city, profile_city, train_end_city, val_end_city = prepare_city_data(
        CITY_DEMAND_ALL[city_name], geo_path, station_names_path, cfg, city_name
    )

    df_city_inj = inject_synthetic_anomalies_v17b(
        df_city,
        inject_start=train_end_city,
        injection_rate=cfg.injection_rate,
        seed=cfg.injection_seed + i,
        verbose=True
    )

    city_data = build_sequences_for_city(
        df_clean=df_city,
        df_inj=df_city_inj,
        train_end=train_end_city,
        val_end=val_end_city,
        city_name=city_name,
        scaler_ext=None
    )

    # Aktivitätsinfo für spätere Gewichtung
    city_data["meta_all"] = add_station_demand_weight(city_data["meta_all"])

    multi_city_data[city_name] = city_data
    multi_city_frames[city_name] = {
        "df_clean": df_city,
        "df_inj": df_city_inj,
        "profile": profile_city,
        "train_end": train_end_city,
        "val_end": val_end_city,
    }

print("\nFertig. Geladene Städte:", list(multi_city_data.keys()))

==========================================================================================
[1/9] CITY PIPELINE: Mannheim
==========================================================================================

======================================================================
  DATEN-PIPELINE: Mannheim
======================================================================
  Roh: 2,547,242 Zeilen, 123 Stationen
  Zeitraum: 2023-03-31 bis 2026-02-02

  [1] Aggregation...
      Shape: (1036182, 22)
  [2] Gap-Fill...
      1,036,182 -> 2,297,523 (+1,261,341)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Mannheim): 88
  Regime: {'mid': 31, 'high': 31, 'low': 31}
  Zeitraum: 2023-03-31 bis 2026-02-02 (1040 Tage)
  Split: Train < 2025-02-25, Val < 2025-07-30, Test ab 2025-07-30
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 2122687, 'grauzone_low': 46485, 'grauzone_high': 32007, 'anomal_high': 5640, 'anomal_low': 631}
    Anomalie-Rate: 0.0028 (0.28%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  748,728
    Injizierte Punkte:     11,230 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested=11230  injected=11230

    Effective rates (of inject region):
      point_spike      1.500%
  [Mannheim] Scaler gefittet auf 1,458,722 Train-Zeilen
  [Mannheim] Sequenzen: (1981139, 24, 9)
  [Mannheim] Split: {'train': 1306467, 'test': 367992, 'val': 306680}
  [Mannheim] X_train (normal): (1261111, 24, 9), X_val (normal): (288212, 24, 9)

==========================================================================================
[2/9] CITY PIPELINE: Heidelberg
==========================================================================================

======================================================================
  DATEN-PIPELINE: Heidelberg
======================================================================
  Roh: 1,873,100 Zeilen, 70 Stationen
  Zeitraum: 2023-03-31 bis 2026-02-02

  [1] Aggregation...
      Shape: (717202, 22)
  [2] Gap-Fill...
      717,202 -> 1,368,502 (+651,300)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Heidelberg): 58
  Regime: {'high': 24, 'low': 24, 'mid': 23}
  Zeitraum: 2023-03-31 bis 2026-02-02 (1040 Tage)
  Split: Train < 2025-02-25, Val < 2025-07-30, Test ab 2025-07-30
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 1612576, 'grauzone_low': 34895, 'grauzone_high': 23872, 'anomal_high': 4921, 'anomal_low': 679}
    Anomalie-Rate: 0.0033 (0.33%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  561,901
    Injizierte Punkte:     8,428 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 8428  injected= 8428

    Effective rates (of inject region):
      point_spike      1.500%
  [Heidelberg] Scaler gefittet auf 1,115,042 Train-Zeilen
  [Heidelberg] Sequenzen: (1063300, 24, 9)
  [Heidelberg] Split: {'train': 696373, 'test': 197782, 'val': 169145}
  [Heidelberg] X_train (normal): (671998, 24, 9), X_val (normal): (160055, 24, 9)

==========================================================================================
[3/9] CITY PIPELINE: Bochum
==========================================================================================

======================================================================
  DATEN-PIPELINE: Bochum
======================================================================
  Roh: 195,168 Zeilen, 95 Stationen
  Zeitraum: 2025-04-15 bis 2026-02-02

  [1] Aggregation...
      Shape: (126787, 22)
  [2] Gap-Fill...
      126,787 -> 656,996 (+530,209)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Bochum): 62
  Regime: {'low': 21, 'high': 21, 'mid': 20}
  Zeitraum: 2025-04-15 bis 2026-02-02 (294 Tage)
  Split: Train < 2025-10-29, Val < 2025-12-12, Test ab 2025-12-12
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 417553, 'grauzone_high': 9042, 'grauzone_low': 8489, 'anomal_high': 917, 'anomal_low': 53}
    Anomalie-Rate: 0.0022 (0.22%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  143,868
    Injizierte Punkte:     2,158 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 2158  injected= 2158

    Effective rates (of inject region):
      point_spike      1.500%
  [Bochum] Scaler gefittet auf 292,186 Train-Zeilen
  [Bochum] Sequenzen: (434628, 24, 9)
  [Bochum] Split: {'train': 290760, 'test': 78396, 'val': 65472}
  [Bochum] X_train (normal): (279557, 24, 9), X_val (normal): (61582, 24, 9)

==========================================================================================
[4/9] CITY PIPELINE: Braunschweig
==========================================================================================

======================================================================
  DATEN-PIPELINE: Braunschweig
======================================================================
  Roh: 397,269 Zeilen, 159 Stationen
  Zeitraum: 2025-02-03 bis 2026-02-02

  [1] Aggregation...
      Shape: (227493, 22)
  [2] Gap-Fill...
      227,493 -> 984,904 (+757,411)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Braunschweig): 88
  Regime: {'low': 32, 'high': 32, 'mid': 31}
  Zeitraum: 2025-02-03 bis 2026-02-02 (365 Tage)
  Split: Train < 2025-10-05, Val < 2025-11-29, Test ab 2025-11-29
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 678247, 'grauzone_low': 18032, 'grauzone_high': 14160, 'anomal_high': 1126, 'anomal_low': 181}
    Anomalie-Rate: 0.0018 (0.18%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  273,652
    Injizierte Punkte:     4,104 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 4104  injected= 4104

    Effective rates (of inject region):
      point_spike      1.500%
  [Braunschweig] Scaler gefittet auf 438,094 Train-Zeilen
  [Braunschweig] Sequenzen: (595091, 24, 9)
  [Braunschweig] Split: {'train': 361877, 'test': 126861, 'val': 106353}
  [Braunschweig] X_train (normal): (347841, 24, 9), X_val (normal): (98820, 24, 9)

==========================================================================================
[5/9] CITY PIPELINE: Dortmund
==========================================================================================

======================================================================
  DATEN-PIPELINE: Dortmund
======================================================================
  Roh: 334,022 Zeilen, 100 Stationen
  Zeitraum: 2025-04-15 bis 2026-02-02

  [1] Aggregation...
      Shape: (191594, 22)
  [2] Gap-Fill...
      191,594 -> 680,355 (+488,761)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Dortmund): 78
  Regime: {'low': 26, 'high': 26, 'mid': 26}
  Zeitraum: 2025-04-15 bis 2026-02-02 (294 Tage)
  Split: Train < 2025-10-29, Val < 2025-12-12, Test ab 2025-12-12
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 528301, 'grauzone_high': 10156, 'grauzone_low': 8976, 'anomal_high': 1154, 'anomal_low': 51}
    Anomalie-Rate: 0.0022 (0.22%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  181,045
    Injizierte Punkte:     2,715 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 2715  injected= 2715

    Effective rates (of inject region):
      point_spike      1.500%
  [Dortmund] Scaler gefittet auf 367,593 Train-Zeilen
  [Dortmund] Sequenzen: (546844, 24, 9)
  [Dortmund] Split: {'train': 365799, 'test': 98677, 'val': 82368}
  [Dortmund] X_train (normal): (353104, 24, 9), X_val (normal): (78312, 24, 9)

==========================================================================================
[6/9] CITY PIPELINE: Duisburg
==========================================================================================

======================================================================
  DATEN-PIPELINE: Duisburg
======================================================================
  Roh: 246,265 Zeilen, 58 Stationen
  Zeitraum: 2025-04-15 bis 2026-02-02

  [1] Aggregation...
      Shape: (116486, 22)
  [2] Gap-Fill...
      116,486 -> 357,180 (+240,694)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Duisburg): 43
  Regime: {'mid': 15, 'low': 14, 'high': 14}
  Zeitraum: 2025-04-15 bis 2026-02-02 (294 Tage)
  Split: Train < 2025-10-29, Val < 2025-12-12, Test ab 2025-12-12
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 282184, 'grauzone_low': 5237, 'grauzone_high': 4718, 'anomal_high': 673, 'anomal_low': 46}
    Anomalie-Rate: 0.0025 (0.25%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  92,818
    Injizierte Punkte:     1,392 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 1392  injected= 1392

    Effective rates (of inject region):
      point_spike      1.500%
  [Duisburg] Scaler gefittet auf 200,040 Train-Zeilen
  [Duisburg] Sequenzen: (291869, 24, 9)
  [Duisburg] Split: {'train': 199051, 'test': 50578, 'val': 42240}
  [Duisburg] X_train (normal): (192301, 24, 9), X_val (normal): (40111, 24, 9)

==========================================================================================
[7/9] CITY PIPELINE: Essen
==========================================================================================

======================================================================
  DATEN-PIPELINE: Essen
======================================================================
  Roh: 145,190 Zeilen, 92 Stationen
  Zeitraum: 2025-04-15 bis 2026-02-02

  [1] Aggregation...
      Shape: (102663, 22)
  [2] Gap-Fill...
      102,663 -> 587,766 (+485,103)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Essen): 56
  Regime: {'low': 20, 'mid': 20, 'high': 20}
  Zeitraum: 2025-04-15 bis 2026-02-02 (294 Tage)
  Split: Train < 2025-10-29, Val < 2025-12-12, Test ab 2025-12-12
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 402986, 'grauzone_high': 9997, 'grauzone_low': 7698, 'anomal_high': 707, 'anomal_low': 30}
    Anomalie-Rate: 0.0017 (0.17%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  138,768
    Injizierte Punkte:     2,081 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 2081  injected= 2081

    Effective rates (of inject region):
      point_spike      1.500%
  [Essen] Scaler gefittet auf 282,650 Train-Zeilen
  [Essen] Sequenzen: (363998, 24, 9)
  [Essen] Split: {'train': 243790, 'test': 65296, 'val': 54912}
  [Essen] X_train (normal): (234001, 24, 9), X_val (normal): (51602, 24, 9)

==========================================================================================
[8/9] CITY PIPELINE: Marburg
==========================================================================================

======================================================================
  DATEN-PIPELINE: Marburg
======================================================================
  Roh: 1,826,429 Zeilen, 60 Stationen
  Zeitraum: 2023-03-31 bis 2026-02-02

  [1] Aggregation...
      Shape: (657687, 22)
  [2] Gap-Fill...
      657,687 -> 1,269,640 (+611,953)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Marburg): 50
  Regime: {'mid': 22, 'low': 21, 'high': 21}
  Zeitraum: 2023-03-31 bis 2026-02-02 (1040 Tage)
  Split: Train < 2025-02-25, Val < 2025-07-30, Test ab 2025-07-30
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 1444770, 'grauzone_low': 33101, 'grauzone_high': 22450, 'anomal_high': 3731, 'anomal_low': 729}
    Anomalie-Rate: 0.0030 (0.30%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  501,906
    Injizierte Punkte:     7,528 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 7528  injected= 7528

    Effective rates (of inject region):
      point_spike      1.500%
  [Marburg] Scaler gefittet auf 1,002,875 Train-Zeilen
  [Marburg] Sequenzen: (966914, 24, 9)
  [Marburg] Split: {'train': 637795, 'test': 179519, 'val': 149600}
  [Marburg] X_train (normal): (615615, 24, 9), X_val (normal): (140393, 24, 9)

==========================================================================================
[9/9] CITY PIPELINE: Winsen (Luhe)
==========================================================================================

======================================================================
  DATEN-PIPELINE: Winsen (Luhe)
======================================================================
  Roh: 156,273 Zeilen, 21 Stationen
  Zeitraum: 2023-04-01 bis 2026-02-02

  [1] Aggregation...
      Shape: (107192, 22)
  [2] Gap-Fill...
      107,192 -> 505,989 (+398,797)
  [3] Stationen, Regime, Splits...
  Aktive Stationen (Winsen (Luhe)): 16
  Regime: {'mid': 6, 'high': 5, 'low': 5}
  Zeitraum: 2023-04-01 bis 2026-02-02 (1039 Tage)
  Split: Train < 2025-02-25, Val < 2025-07-30, Test ab 2025-07-30
  [4] Statistische Scoring-Pipeline...
  [1/5] Kontext-Keys...
  [2/5] Rolling z-Scores...
  [3/5] Poisson-Tail-Scores...
  [4/5] ECDF-Kalibrierung...
  [5/5] Labels...
  Label-Verteilung:
    {'normal': 379704, 'grauzone_high': 9581, 'grauzone_low': 8703, 'anomal_high': 259, 'anomal_low': 69}
    Anomalie-Rate: 0.0008 (0.08%)

  Synthetic Injection (V17b — ohne Contextuals):
    Inject-Zeilen gesamt:  131,608
    Injizierte Punkte:     1,974 (1.50%)

    Requested vs Actually Injected:
      point_spike      requested= 1974  injected= 1974

    Effective rates (of inject region):
      point_spike      1.500%
  [Winsen (Luhe)] Scaler gefittet auf 266,708 Train-Zeilen
  [Winsen (Luhe)] Sequenzen: (397948, 24, 9)
  [Winsen (Luhe)] Split: {'train': 266340, 'test': 71768, 'val': 59840}
  [Winsen (Luhe)] X_train (normal): (254641, 24, 9), X_val (normal): (56265, 24, 9)

Fertig. Geladene Städte: ['Mannheim', 'Heidelberg', 'Bochum', 'Braunschweig', 'Dortmund', 'Duisburg', 'Essen', 'Marburg', 'Winsen (Luhe)']

In [28]:
# ══════════════════════════════════════════════════════════════
# MC-X — Oracle Experiment pro Stadt (generisch)
# ══════════════════════════════════════════════════════════════
import os
import json
import numpy as np
import pandas as pd
from tensorflow import keras

def run_oracle_experiment(
    city_data,
    cfg,
    city_name,
    models_dir,
    fc_model_preloaded=None,
    ae_model_preloaded=None,
    save_models=True,
    verbose=True
):
    """
    Führt das Oracle-Experiment für genau eine Stadt aus.

    Erwartet in city_data:
        - X_all
        - meta_all
        - X_train
        - X_val_clean

    Nutzt:
        - train_forecaster(...)
        - train_autoencoder(...)
        - score_forecaster_windows(...)
        - score_autoencoder_windows(...)
        - evaluate_predictions(...)   # falls vorhanden
        oder berechnet zumindest Rohscores + Labels
    """
    os.makedirs(models_dir, exist_ok=True)

    X_all = city_data["X_all"]
    meta_all = city_data["meta_all"].copy()
    X_train = city_data["X_train"]
    X_val_clean = city_data["X_val_clean"]

    # ----------------------------------------------------------
    # Split-Masken
    # ----------------------------------------------------------
    test_mask = meta_all["split_eval"] == "test"
    y_test = meta_all.loc[test_mask, "synth_label"].astype(int).values

    # ----------------------------------------------------------
    # Modelle laden oder trainieren
    # ----------------------------------------------------------
    fc_model = fc_model_preloaded
    ae_model = ae_model_preloaded

    fc_path = os.path.join(models_dir, f"{city_name.lower()}_oracle_forecaster.keras")
    ae_path = os.path.join(models_dir, f"{city_name.lower()}_oracle_autoencoder.keras")

    # ---------- Forecaster ----------
    if fc_model is None:
        if verbose:
            print(f"[{city_name}] Trainiere Oracle Forecaster ...")
        fc_model, fc_hist = train_forecaster(
            X_train=X_train,
            X_val=X_val_clean,
            cfg=cfg,
            city_name=city_name
        )
        if save_models:
            fc_model.save(fc_path)
            if verbose:
                print(f"[{city_name}] FC gespeichert → {fc_path}")
    else:
        fc_hist = None
        if verbose:
            print(f"[{city_name}] Oracle Forecaster geladen")

    # ---------- Autoencoder ----------
    if ae_model is None:
        if verbose:
            print(f"[{city_name}] Trainiere Oracle Autoencoder ...")
        ae_model, ae_hist = train_autoencoder(
            X_train=X_train,
            X_val=X_val_clean,
            cfg=cfg,
            city_name=city_name
        )
        if save_models:
            ae_model.save(ae_path)
            if verbose:
                print(f"[{city_name}] AE gespeichert → {ae_path}")
    else:
        ae_hist = None
        if verbose:
            print(f"[{city_name}] Oracle Autoencoder geladen")

    # ----------------------------------------------------------
    # Scoring auf allen Fenstern
    # ----------------------------------------------------------
    if verbose:
        print(f"[{city_name}] Berechne Scores ...")

    fc_scores_all = score_forecaster_windows(fc_model, X_all, cfg=cfg)
    ae_scores_all = score_autoencoder_windows(ae_model, X_all, cfg=cfg)

    # Nur Test
    fc_scores_test = np.asarray(fc_scores_all)[test_mask.values]
    ae_scores_test = np.asarray(ae_scores_all)[test_mask.values]

    meta_test = meta_all.loc[test_mask].copy()
    meta_test["y_true"] = y_test
    meta_test["fc_score"] = fc_scores_test
    meta_test["ae_score"] = ae_scores_test

    # ----------------------------------------------------------
    # Auswertung
    # ----------------------------------------------------------
    results = []

    # Falls es im Notebook schon eine Standard-Eval-Funktion gibt, nutze sie
    if "evaluate_predictions" in globals():
        try:
            fc_eval = evaluate_predictions(
                y_true=y_test,
                scores=fc_scores_test,
                model_name="forecaster",
                city_name=city_name
            )
            fc_row = {"city": city_name, "setting": "oracle", "model": "forecaster"}
            if isinstance(fc_eval, dict):
                fc_row.update(fc_eval)
            results.append(fc_row)
        except Exception as e:
            print(f"[{city_name}] Warnung FC-Eval: {e}")

        try:
            ae_eval = evaluate_predictions(
                y_true=y_test,
                scores=ae_scores_test,
                model_name="autoencoder",
                city_name=city_name
            )
            ae_row = {"city": city_name, "setting": "oracle", "model": "autoencoder"}
            if isinstance(ae_eval, dict):
                ae_row.update(ae_eval)
            results.append(ae_row)
        except Exception as e:
            print(f"[{city_name}] Warnung AE-Eval: {e}")

    # Fallback: wenigstens Rohsummary
    if len(results) == 0:
        results = [
            {
                "city": city_name,
                "setting": "oracle",
                "model": "forecaster",
                "n_test": int(test_mask.sum()),
                "n_anom_test": int(y_test.sum())
            },
            {
                "city": city_name,
                "setting": "oracle",
                "model": "autoencoder",
                "n_test": int(test_mask.sum()),
                "n_anom_test": int(y_test.sum())
            }
        ]

    results_df = pd.DataFrame(results)

    meta_bundle = {
        "meta_all": meta_all,
        "meta_test": meta_test,
        "fc_history": fc_hist.history if fc_hist is not None and hasattr(fc_hist, "history") else None,
        "ae_history": ae_hist.history if ae_hist is not None and hasattr(ae_hist, "history") else None,
        "fc_model_path": fc_path,
        "ae_model_path": ae_path,
    }

    return results_df, fc_model, ae_model, meta_bundle

In [32]:

# ══════════════════════════════════════════════════════════════
# MC-4 — Multi-City Oracle (FC + AE) mit Speicherung
# ══════════════════════════════════════════════════════════════
from tensorflow import keras

def try_load_city_models_full(models_dir, city_name):
    city_key = city_to_key(city_name)
    fc_path = os.path.join(models_dir, f"{city_key}_oracle_forecaster.keras")
    ae_path = os.path.join(models_dir, f"{city_key}_oracle_autoencoder.keras")

    fc_model = keras.models.load_model(fc_path, compile=False) if os.path.exists(fc_path) else None
    ae_model = keras.models.load_model(ae_path, compile=False) if os.path.exists(ae_path) else None

    print(f"[{city_name}] FC:", "geladen" if fc_model is not None else "nicht gefunden", "→", fc_path)
    print(f"[{city_name}] AE:", "geladen" if ae_model is not None else "nicht gefunden", "→", ae_path)
    return fc_model, ae_model, fc_path, ae_path

oracle_summary_rows = []
oracle_regime_paths = []
oracle_score_paths = []
oracle_meta_by_city = {}

for city_name, city_data in multi_city_data.items():
    print("\n" + "="*90)
    print(f"ORACLE LOOP: {city_name}")
    print("="*90)

    fc_loaded, ae_loaded, _, _ = try_load_city_models_full(MULTICITY_MODEL_DIR, city_name)

    oracle_results_city, fc_model_city, ae_model_city, meta_city = run_oracle_experiment(
        city_data, cfg, city_name, MULTICITY_MODEL_DIR,
        fc_model_preloaded=fc_loaded,
        ae_model_preloaded=ae_loaded,
    )

    meta_city = add_station_demand_weight(meta_city)
    oracle_meta_by_city[city_name] = meta_city.copy()

    # FC
    if "score_fc_znorm_hs" in meta_city.columns and "FC_Oracle" in oracle_results_city:
        oracle_summary_rows.append(flatten_result_dict(oracle_results_city["FC_Oracle"], city_name, "FC_Oracle"))
        oracle_score_paths.append(
            save_window_level_scores(
                meta_city, city_name, "FC_Oracle", MULTICITY_PRED_DIR,
                score_cols=["score_fc_raw", "score_fc_znorm_hs"],
                extra_cols=["station_activity_raw", "station_activity_log1p", "station_activity_group"]
            )
        )
        p = save_regime_detail_if_present(oracle_results_city["FC_Oracle"], city_name, "FC_Oracle", MULTICITY_SUMMARY_DIR)
        if p is not None:
            oracle_regime_paths.append(p)

    # AE
    if "score_ae_znorm_hs" in meta_city.columns and "AE_Oracle" in oracle_results_city:
        oracle_summary_rows.append(flatten_result_dict(oracle_results_city["AE_Oracle"], city_name, "AE_Oracle"))
        oracle_score_paths.append(
            save_window_level_scores(
                meta_city, city_name, "AE_Oracle", MULTICITY_PRED_DIR,
                score_cols=["score_ae_raw", "score_ae_znorm_hs"],
                extra_cols=["station_activity_raw", "station_activity_log1p", "station_activity_group"]
            )
        )
        p = save_regime_detail_if_present(oracle_results_city["AE_Oracle"], city_name, "AE_Oracle", MULTICITY_SUMMARY_DIR)
        if p is not None:
            oracle_regime_paths.append(p)

oracle_summary_df = pd.DataFrame(oracle_summary_rows)
oracle_summary_path = f"{MULTICITY_SUMMARY_DIR}/oracle_summary.csv"
oracle_summary_df.to_csv(oracle_summary_path, index=False)

print("\nOracle Summary:")
display(oracle_summary_df.sort_values(["model", "test_pr_auc"], ascending=[True, False]))
print(f"\nOracle Summary gespeichert unter: {oracle_summary_path}")

==========================================================================================
ORACLE LOOP: Mannheim
==========================================================================================
[Mannheim] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/mannheim_oracle_forecaster.keras
[Mannheim] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/mannheim_oracle_autoencoder.keras

  [Mannheim] Training Forecaster (Oracle)...

Epoch 36: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 49: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Restoring model weights from the end of the best epoch: 50.
  [Mannheim] Forecaster gespeichert.

  [Mannheim_Oracle_FC]
    Anomaly Rate: 0.0136 (1.36%)
      point_spike    : n= 4988, rate=0.0136
    Threshold: 4.511058
    TEST PR-AUC=0.4986, F1=0.5486, Prec=0.5551, Recall=0.5423
    Per-Type PR-AUC:
      point_spike    : 0.4986

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.502/0.515
      mid : 0.553/0.566
      low : 0.511/0.571
                  spike  |         drop  |   collective

  [Mannheim] Training Autoencoder (Oracle)...

Epoch 42: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 50.
  [Mannheim] Autoencoder gespeichert.

  [Mannheim_Oracle_AE]
    Anomaly Rate: 0.0136 (1.36%)
      point_spike    : n= 4988, rate=0.0136
    Threshold: 6.747976
    TEST PR-AUC=0.4247, F1=0.4725, Prec=0.5285, Recall=0.4272
    Per-Type PR-AUC:
      point_spike    : 0.4247

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.429/0.433
      mid : 0.459/0.477
      low : 0.434/0.524
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/mannheim__FC_Oracle__window_scores.parquet | rows=1,981,139
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/mannheim__AE_Oracle__window_scores.parquet | rows=1,981,139

==========================================================================================
ORACLE LOOP: Heidelberg
==========================================================================================
[Heidelberg] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/heidelberg_oracle_forecaster.keras
[Heidelberg] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/heidelberg_oracle_autoencoder.keras

  [Heidelberg] Training Forecaster (Oracle)...

Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 37: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 41: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 33.
  [Heidelberg] Forecaster gespeichert.

  [Heidelberg_Oracle_FC]
    Anomaly Rate: 0.0140 (1.40%)
      point_spike    : n= 2772, rate=0.0140
    Threshold: 4.614532
    TEST PR-AUC=0.4238, F1=0.4949, Prec=0.4747, Recall=0.5170
    Per-Type PR-AUC:
      point_spike    : 0.4238

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.422/0.476
      mid : 0.477/0.497
      low : 0.412/0.512
                  spike  |         drop  |   collective

  [Heidelberg] Training Autoencoder (Oracle)...
Restoring model weights from the end of the best epoch: 50.
  [Heidelberg] Autoencoder gespeichert.

  [Heidelberg_Oracle_AE]
    Anomaly Rate: 0.0140 (1.40%)
      point_spike    : n= 2772, rate=0.0140
    Threshold: 6.245953
    TEST PR-AUC=0.3662, F1=0.4439, Prec=0.4395, Recall=0.4484
    Per-Type PR-AUC:
      point_spike    : 0.3662

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.378/0.439
      mid : 0.422/0.454
      low : 0.323/0.439
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/heidelberg__FC_Oracle__window_scores.parquet | rows=1,063,300
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/heidelberg__AE_Oracle__window_scores.parquet | rows=1,063,300

==========================================================================================
ORACLE LOOP: Bochum
==========================================================================================
[Bochum] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/bochum_oracle_forecaster.keras
[Bochum] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/bochum_oracle_autoencoder.keras

  [Bochum] Training Forecaster (Oracle)...

Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 30: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 34: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 34: early stopping
Restoring model weights from the end of the best epoch: 26.
  [Bochum] Forecaster gespeichert.

  [Bochum_Oracle_FC]
    Anomaly Rate: 0.0120 (1.20%)
      point_spike    : n=  938, rate=0.0120
    Threshold: 6.459233
    TEST PR-AUC=0.5163, F1=0.6193, Prec=0.5834, Recall=0.6599
    Per-Type PR-AUC:
      point_spike    : 0.5163

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.617/0.608
      mid : 0.540/0.648
      low : 0.477/0.605
                  spike  |         drop  |   collective

  [Bochum] Training Autoencoder (Oracle)...

Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 9.
  [Bochum] Autoencoder gespeichert.

  [Bochum_Oracle_AE]
    Anomaly Rate: 0.0120 (1.20%)
      point_spike    : n=  938, rate=0.0120
    Threshold: 6.500254
    TEST PR-AUC=0.5121, F1=0.6199, Prec=0.5133, Recall=0.7825
    Per-Type PR-AUC:
      point_spike    : 0.5121

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.576/0.675
      mid : 0.551/0.596
      low : 0.489/0.531
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/bochum__FC_Oracle__window_scores.parquet | rows=434,628
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/bochum__AE_Oracle__window_scores.parquet | rows=434,628

==========================================================================================
ORACLE LOOP: Braunschweig
==========================================================================================
[Braunschweig] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/braunschweig_oracle_forecaster.keras
[Braunschweig] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/braunschweig_oracle_autoencoder.keras

  [Braunschweig] Training Forecaster (Oracle)...

Epoch 29: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 33: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 33: early stopping
Restoring model weights from the end of the best epoch: 25.
  [Braunschweig] Forecaster gespeichert.

  [Braunschweig_Oracle_FC]
    Anomaly Rate: 0.0122 (1.22%)
      point_spike    : n= 1546, rate=0.0122
    Threshold: 5.736843
    TEST PR-AUC=0.6075, F1=0.6246, Prec=0.6256, Recall=0.6235
    Per-Type PR-AUC:
      point_spike    : 0.6075

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.613/0.528
      mid : 0.679/0.700
      low : 0.679/0.646
                  spike  |         drop  |   collective

  [Braunschweig] Training Autoencoder (Oracle)...

Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 19: early stopping
Restoring model weights from the end of the best epoch: 11.
  [Braunschweig] Autoencoder gespeichert.

  [Braunschweig_Oracle_AE]
    Anomaly Rate: 0.0122 (1.22%)
      point_spike    : n= 1546, rate=0.0122
    Threshold: 7.280339
    TEST PR-AUC=0.6051, F1=0.6165, Prec=0.5851, Recall=0.6514
    Per-Type PR-AUC:
      point_spike    : 0.6051

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.598/0.554
      mid : 0.675/0.680
      low : 0.657/0.616
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/braunschweig__FC_Oracle__window_scores.parquet | rows=595,091
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/braunschweig__AE_Oracle__window_scores.parquet | rows=595,091

==========================================================================================
ORACLE LOOP: Dortmund
==========================================================================================
[Dortmund] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/dortmund_oracle_forecaster.keras
[Dortmund] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/dortmund_oracle_autoencoder.keras

  [Dortmund] Training Forecaster (Oracle)...

Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 29: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 21.
  [Dortmund] Forecaster gespeichert.

  [Dortmund_Oracle_FC]
    Anomaly Rate: 0.0131 (1.31%)
      point_spike    : n= 1295, rate=0.0131
    Threshold: 6.271795
    TEST PR-AUC=0.6029, F1=0.6504, Prec=0.6317, Recall=0.6703
    Per-Type PR-AUC:
      point_spike    : 0.6029

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.676/0.626
      mid : 0.667/0.708
      low : 0.576/0.612
                  spike  |         drop  |   collective

  [Dortmund] Training Autoencoder (Oracle)...

Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 5.
  [Dortmund] Autoencoder gespeichert.

  [Dortmund_Oracle_AE]
    Anomaly Rate: 0.0131 (1.31%)
      point_spike    : n= 1295, rate=0.0131
    Threshold: 6.516618
    TEST PR-AUC=0.6241, F1=0.6541, Prec=0.5733, Recall=0.7614
    Per-Type PR-AUC:
      point_spike    : 0.6241

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.658/0.659
      mid : 0.669/0.664
      low : 0.649/0.625
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/dortmund__FC_Oracle__window_scores.parquet | rows=546,844
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/dortmund__AE_Oracle__window_scores.parquet | rows=546,844

==========================================================================================
ORACLE LOOP: Duisburg
==========================================================================================
[Duisburg] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/duisburg_oracle_forecaster.keras
[Duisburg] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/duisburg_oracle_autoencoder.keras

  [Duisburg] Training Forecaster (Oracle)...

Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 29: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 21.
  [Duisburg] Forecaster gespeichert.

  [Duisburg_Oracle_FC]
    Anomaly Rate: 0.0125 (1.25%)
      point_spike    : n=  634, rate=0.0125
    Threshold: 5.061151
    TEST PR-AUC=0.5372, F1=0.5721, Prec=0.6071, Recall=0.5410
    Per-Type PR-AUC:
      point_spike    : 0.5372

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.723/0.520
      mid : 0.676/0.713
      low : 0.430/0.476
                  spike  |         drop  |   collective

  [Duisburg] Training Autoencoder (Oracle)...

Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 19: early stopping
Restoring model weights from the end of the best epoch: 11.
  [Duisburg] Autoencoder gespeichert.

  [Duisburg_Oracle_AE]
    Anomaly Rate: 0.0125 (1.25%)
      point_spike    : n=  634, rate=0.0125
    Threshold: 6.497209
    TEST PR-AUC=0.5216, F1=0.5708, Prec=0.5721, Recall=0.5694
    Per-Type PR-AUC:
      point_spike    : 0.5216

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.660/0.548
      mid : 0.661/0.691
      low : 0.467/0.437
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/duisburg__FC_Oracle__window_scores.parquet | rows=291,869
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/duisburg__AE_Oracle__window_scores.parquet | rows=291,869

==========================================================================================
ORACLE LOOP: Essen
==========================================================================================
[Essen] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/essen_oracle_forecaster.keras
[Essen] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/essen_oracle_autoencoder.keras

  [Essen] Training Forecaster (Oracle)...

Epoch 32: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 36: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 40: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 32.
  [Essen] Forecaster gespeichert.

  [Essen_Oracle_FC]
    Anomaly Rate: 0.0129 (1.29%)
      point_spike    : n=  842, rate=0.0129
    Threshold: 6.484629
    TEST PR-AUC=0.6513, F1=0.6847, Prec=0.6939, Recall=0.6758
    Per-Type PR-AUC:
      point_spike    : 0.6513

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.659/0.613
      mid : 0.828/0.828
      low : 0.652/0.657
                  spike  |         drop  |   collective

  [Essen] Training Autoencoder (Oracle)...

Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 9.
  [Essen] Autoencoder gespeichert.

  [Essen_Oracle_AE]
    Anomaly Rate: 0.0129 (1.29%)
      point_spike    : n=  842, rate=0.0129
    Threshold: 6.536080
    TEST PR-AUC=0.6174, F1=0.6591, Prec=0.5832, Recall=0.7577
    Per-Type PR-AUC:
      point_spike    : 0.6174

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.626/0.658
      mid : 0.779/0.746
      low : 0.614/0.548
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/essen__FC_Oracle__window_scores.parquet | rows=363,998
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/essen__AE_Oracle__window_scores.parquet | rows=363,998

==========================================================================================
ORACLE LOOP: Marburg
==========================================================================================
[Marburg] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/marburg_oracle_forecaster.keras
[Marburg] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/marburg_oracle_autoencoder.keras

  [Marburg] Training Forecaster (Oracle)...

Epoch 45: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 50.
  [Marburg] Forecaster gespeichert.

  [Marburg_Oracle_FC]
    Anomaly Rate: 0.0137 (1.37%)
      point_spike    : n= 2466, rate=0.0137
    Threshold: 4.474802
    TEST PR-AUC=0.4789, F1=0.5285, Prec=0.5739, Recall=0.4899
    Per-Type PR-AUC:
      point_spike    : 0.4789

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.523/0.532
      mid : 0.481/0.513
      low : 0.465/0.542
                  spike  |         drop  |   collective

  [Marburg] Training Autoencoder (Oracle)...

Epoch 47: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 43.
  [Marburg] Autoencoder gespeichert.

  [Marburg_Oracle_AE]
    Anomaly Rate: 0.0137 (1.37%)
      point_spike    : n= 2466, rate=0.0137
    Threshold: 7.017307
    TEST PR-AUC=0.4323, F1=0.4602, Prec=0.5732, Recall=0.3844
    Per-Type PR-AUC:
      point_spike    : 0.4323

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.463/0.452
      mid : 0.444/0.462
      low : 0.401/0.471
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/marburg__FC_Oracle__window_scores.parquet | rows=966,914
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/marburg__AE_Oracle__window_scores.parquet | rows=966,914

==========================================================================================
ORACLE LOOP: Winsen (Luhe)
==========================================================================================
[Winsen (Luhe)] FC: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/winsen_luhe_oracle_forecaster.keras
[Winsen (Luhe)] AE: nicht gefunden → /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/models/winsen_luhe_oracle_autoencoder.keras

  [Winsen (Luhe)] Training Forecaster (Oracle)...

Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 21: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 31: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 35: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 27.
  [Winsen (Luhe)] Forecaster gespeichert.

  [Winsen (Luhe)_Oracle_FC]
    Anomaly Rate: 0.0154 (1.54%)
      point_spike    : n= 1103, rate=0.0154
    Threshold: 6.057621
    TEST PR-AUC=0.6889, F1=0.6756, Prec=0.6296, Recall=0.7289
    Per-Type PR-AUC:
      point_spike    : 0.6889

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.722/0.656
      mid : 0.764/0.729
      low : 0.644/0.590
                  spike  |         drop  |   collective

  [Winsen (Luhe)] Training Autoencoder (Oracle)...
Restoring model weights from the end of the best epoch: 50.
  [Winsen (Luhe)] Autoencoder gespeichert.

  [Winsen (Luhe)_Oracle_AE]
    Anomaly Rate: 0.0154 (1.54%)
      point_spike    : n= 1103, rate=0.0154
    Threshold: 8.284116
    TEST PR-AUC=0.6514, F1=0.6559, Prec=0.6037, Recall=0.7180
    Per-Type PR-AUC:
      point_spike    : 0.6514

    Type × Regime Matrix (PR-AUC / F1):
      high: 0.658/0.633
      mid : 0.736/0.704
      low : 0.569/0.591
                  spike  |         drop  |   collective
Gespeichert: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/predictions/winsen_luhe__FC_Oracle__window_scores.parquet | rows=397,948

,experiment,n_val,n_test,anomaly_rate_total,rate_point_spike,n_point_spike,val_pr_auc,val_best_f1,val_threshold,test_pr_auc,test_roc_auc,test_f1,test_prec,test_recall,pr_point_spike,dr_point_spike,city,city_key,model
17,Winsen (Luhe)_Oracle_AE,59840,71768,0.015369,0.015369,1103,0.824354,0.729649,8.284116,0.651449,0.989313,0.655901,0.603659,0.718042,0.651449,0.718042,Winsen (Luhe),winsen_luhe,AE_Oracle
9,Dortmund_Oracle_AE,82368,98677,0.013124,0.013124,1295,0.875205,0.884963,6.516618,0.624054,0.978139,0.654063,0.573256,0.761390,0.624054,0.761390,Dortmund,dortmund,AE_Oracle
13,Essen_Oracle_AE,54912,65296,0.012895,0.012895,842,0.819326,0.844714,6.536080,0.617377,0.982973,0.659091,0.583181,0.757720,0.617377,0.757720,Essen,essen,AE_Oracle
7,Braunschweig_Oracle_AE,106353,126861,0.012187,0.012187,1546,0.804223,0.810026,7.280339,0.605102,0.984811,0.616468,0.585125,0.651358,0.605102,0.651358,Braunschweig,braunschweig,AE_Oracle
11,Duisburg_Oracle_AE,42240,50578,0.012535,0.012535,634,0.785034,0.800633,6.497209,0.521605,0.972658,0.570751,0.572108,0.569401,0.521605,0.569401,Duisburg,duisburg,AE_Oracle
5,Bochum_Oracle_AE,65472,78396,0.011965,0.011965,938,0.848812,0.871937,6.500254,0.512149,0.981480,0.619932,0.513287,0.782516,0.512149,0.782516,Bochum,bochum,AE_Oracle
15,Marburg_Oracle_AE,149600,179519,0.013737,0.013737,2466,0.583739,0.546440,7.017307,0.432330,0.958512,0.460194,0.573156,0.384428,0.432330,0.384428,Marburg,marburg,AE_Oracle
1,Mannheim_Oracle_AE,306680,367992,0.013555,0.013555,4988,0.589364,0.534661,6.747976,0.424727,0.962734,0.472506,0.528522,0.427225,0.424727,0.427225,Mannheim,mannheim,AE_Oracle
3,Heidelberg_Oracle_AE,169145,197782,0.014015,0.014015,2772,0.556038,0.503895,6.245953,0.366151,0.961288,0.443929,0.439533,0.448413,0.366151,0.448413,Heidelberg,heidelberg,AE_Oracle
16,Winsen (Luhe)_Oracle_FC,59840,71768,0.015369,0.015369,1103,0.815857,0.736842,6.057621,0.688936,0.988274,0.675630,0.629601,0.728921,0.688936,0.728921,Winsen (Luhe),winsen_luhe,FC_Oracle
12,Essen_Oracle_FC,54912,65296,0.012895,0.012895,842,0.818638,0.782356,6.484629,0.651303,0.989635,0.684717,0.693902,0.675772,0.651303,0.675772,Essen,essen,FC_Oracle
6,Braunschweig_Oracle_FC,106353,126861,0.012187,0.012187,1546,0.804813,0.730781,5.736843,0.607523,0.986998,0.624555,0.625568,0.623545,0.607523,0.623545,Braunschweig,braunschweig,FC_Oracle
8,Dortmund_Oracle_FC,82368,98677,0.013124,0.013124,1295,0.851176,0.794045,6.271795,0.602882,0.987596,0.650431,0.631732,0.670270,0.602882,0.670270,Dortmund,dortmund,FC_Oracle
10,Duisburg_Oracle_FC,42240,50578,0.012535,0.012535,634,0.772557,0.702158,5.061151,0.537244,0.982484,0.572143,0.607080,0.541009,0.537244,0.541009,Duisburg,duisburg,FC_Oracle
4,Bochum_Oracle_FC,65472,78396,0.011965,0.011965,938,0.836586,0.796652,6.459233,0.516348,0.987920,0.619310,0.583412,0.659915,0.516348,0.659915,Bochum,bochum,FC_Oracle
0,Mannheim_Oracle_FC,306680,367992,0.013555,0.013555,4988,0.627837,0.594938,4.511058,0.498586,0.969972,0.548626,0.555100,0.542302,0.498586,0.542302,Mannheim,mannheim,FC_Oracle
14,Marburg_Oracle_FC,149600,179519,0.013737,0.013737,2466,0.623094,0.595983,4.474802,0.478934,0.965872,0.528550,0.573872,0.489862,0.478934,0.489862,Marburg,marburg,FC_Oracle
2,Heidelberg_Oracle_FC,169145,197782,0.014015,0.014015,2772,0.586053,0.555250,4.614532,0.423788,0.964285,0.494906,0.474660,0.516955,0.423788,0.516955,Heidelberg,heidelberg,FC_Oracle

Oracle Summary gespeichert unter: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/summary/oracle_summary.csv

In [35]:
# ══════════════════════════════════════════════════════════════
# ORACLE POST-HOC — Helper Functions (kompakt)
# Stationsliste + schmale gewichtete Metriken
# ══════════════════════════════════════════════════════════════
import os
import numpy as np
import pandas as pd

from sklearn.metrics import (
    average_precision_score,
    f1_score,
    precision_recall_curve
)

MODEL_SCORE_COLS = {
    "FC_Oracle": "score_fc_znorm_hs",
    "AE_Oracle": "score_ae_znorm_hs",
}

GROUP_WEIGHT_MAP = {
    "low": 1.0,
    "mid": 2.0,
    "medium": 2.0,
    "high": 3.0
}

MIN_STATION_ANOM = 1
MIN_STATION_NEG  = 1


# -------------------------------------------------------------
# kleine Helfer
# -------------------------------------------------------------
def _safe_ap(y_true, y_score, sample_weight=None):
    y_true = np.asarray(y_true).astype(int)
    y_score = np.asarray(y_score, dtype=float)
    if len(np.unique(y_true)) < 2:
        return np.nan
    return float(average_precision_score(y_true, y_score, sample_weight=sample_weight))


def _best_f1_from_scores(y_true, y_score):
    y_true = np.asarray(y_true).astype(int)
    y_score = np.asarray(y_score, dtype=float)

    if len(np.unique(y_true)) < 2:
        return np.nan, np.nan

    prec, rec, thr = precision_recall_curve(y_true, y_score)
    f1 = 2 * prec * rec / np.clip(prec + rec, 1e-12, None)

    # precision_recall_curve gibt einen Punkt mehr als thresholds zurück
    if len(thr) == 0:
        return np.nan, np.nan

    f1_thr = f1[:-1]
    best_idx = int(np.nanargmax(f1_thr))
    return float(f1_thr[best_idx]), float(thr[best_idx])


def _infer_station_name(station_df: pd.DataFrame) -> str:
    candidate_cols = [
        "station_name",
        "name",
        "station_title",
        "station_label",
        "station"
    ]
    for c in candidate_cols:
        if c in station_df.columns and station_df[c].notna().any():
            vals = station_df[c].dropna().astype(str)
            if len(vals) > 0:
                return vals.mode().iloc[0]
    return ""


def _infer_station_group(station_df: pd.DataFrame) -> str:
    for c in ["station_activity_group", "demand_regime", "regime"]:
        if c in station_df.columns and station_df[c].notna().any():
            vals = station_df[c].dropna().astype(str)
            if len(vals) > 0:
                v = vals.mode().iloc[0]
                if v == "medium":
                    return "mid"
                return v
    return "unknown"


def _infer_station_activity_raw(station_df: pd.DataFrame) -> float:
    if "station_activity_raw" in station_df.columns and station_df["station_activity_raw"].notna().any():
        return float(station_df["station_activity_raw"].dropna().iloc[0])

    # fallback über Demand-Spalten
    demand_candidates = [
        "original_total_demand", "total_demand",
        "original_n_lends", "n_lends"
    ]
    for c in demand_candidates:
        if c in station_df.columns and station_df[c].notna().any():
            return float(station_df[c].mean())

    return 1.0


# -------------------------------------------------------------
# 1) Stationsliste pro Netzwerk/Run
# -------------------------------------------------------------
def build_station_test_table(test_df: pd.DataFrame, score_col: str) -> pd.DataFrame:
    """
    Pro Station:
    - station_name
    - station_id
    - test_pr_auc
    - test_f1 (bestes F1 aus Testkurve, rein deskriptiv)
    """
    rows = []

    for station_id, g in test_df.groupby("station_id"):
        y = g["synth_label"].astype(int).values
        s = g[score_col].astype(float).values

        n_pos = int((y == 1).sum())
        n_neg = int((y == 0).sum())

        if n_pos < MIN_STATION_ANOM or n_neg < MIN_STATION_NEG:
            pr_auc = np.nan
            best_f1 = np.nan
        else:
            pr_auc = _safe_ap(y, s)
            best_f1, _ = _best_f1_from_scores(y, s)

        rows.append({
            "station_name": _infer_station_name(g),
            "station_id": station_id,
            "test_pr_auc": pr_auc,
            "test_f1": best_f1,
            "n_test_windows": len(g),
            "n_test_anom": n_pos,
            "station_group": _infer_station_group(g),
            "station_activity_raw": _infer_station_activity_raw(g),
        })

    out = pd.DataFrame(rows)

    if len(out) == 0:
        return out

    out["group_weight"] = out["station_group"].map(GROUP_WEIGHT_MAP).fillna(1.0)
    out["sqrt_activity_weight"] = np.sqrt(out["station_activity_raw"].clip(lower=0) + 1e-12)

    out = out.sort_values(
        ["test_pr_auc", "test_f1", "n_test_anom", "n_test_windows"],
        ascending=[False, False, False, False]
    ).reset_index(drop=True)

    return out[[
        "station_name",
        "station_id",
        "test_pr_auc",
        "test_f1",
        "n_test_windows",
        "n_test_anom",
        "station_group",
        "station_activity_raw",
        "group_weight",
        "sqrt_activity_weight"
    ]]


# -------------------------------------------------------------
# 2) Schmale Run-Metrik-Tabelle
# -------------------------------------------------------------
def compute_compact_weighted_metrics(
    test_df: pd.DataFrame,
    score_col: str,
    station_table: pd.DataFrame
) -> dict:
    """
    Kompakte Metriken pro Run:
    - micro_pr_auc
    - macro_station_pr_auc
    - weighted_macro_station_pr_auc_group
    - weighted_macro_station_pr_auc_sqrt_activity
    """
    y = test_df["synth_label"].astype(int).values
    s = test_df[score_col].astype(float).values

    valid_station_df = station_table.dropna(subset=["test_pr_auc"]).copy()

    out = {
        "n_test_windows": int(len(test_df)),
        "n_test_anom": int((y == 1).sum()),
        "n_valid_stations": int(len(valid_station_df)),
        "micro_pr_auc": _safe_ap(y, s),
    }

    if len(valid_station_df) > 0:
        pr = valid_station_df["test_pr_auc"].astype(float).values
        gw = valid_station_df["group_weight"].astype(float).values
        aw = valid_station_df["sqrt_activity_weight"].astype(float).values

        out["macro_station_pr_auc"] = float(np.mean(pr))
        out["weighted_macro_pr_auc_group"] = float(np.average(pr, weights=gw))
        out["weighted_macro_pr_auc_sqrt_activity"] = float(np.average(pr, weights=aw))
    else:
        out["macro_station_pr_auc"] = np.nan
        out["weighted_macro_pr_auc_group"] = np.nan
        out["weighted_macro_pr_auc_sqrt_activity"] = np.nan

    return out

In [36]:
# ══════════════════════════════════════════════════════════════
# ORACLE POST-HOC — Ausführung (kompakt)
# Stationslisten + schmale Metrik-Tabelle
# ══════════════════════════════════════════════════════════════

oracle_station_tables = {}   # key: (city_name, model_name) -> station_table
oracle_compact_rows = []

for city_name, meta_city in oracle_meta_by_city.items():
    print("\n" + "="*100)
    print(f"POST-HOC ORACLE ANALYSIS: {city_name}")
    print("="*100)

    test_df = meta_city.loc[meta_city["split_eval"] == "test"].copy()

    if len(test_df) == 0:
        print("Keine TEST-Daten gefunden, übersprungen.")
        continue

    for model_name, score_col in MODEL_SCORE_COLS.items():
        if score_col not in test_df.columns:
            print(f"[{city_name} | {model_name}] Score-Spalte fehlt: {score_col}")
            continue

        # 1) Stationsliste erzeugen
        station_table = build_station_test_table(test_df, score_col=score_col)
        oracle_station_tables[(city_name, model_name)] = station_table

        print(f"\n[{city_name} | {model_name}] Stationsliste (sortiert nach test_pr_auc)")
        display(
            station_table[[
                "station_name",
                "station_id",
                "test_pr_auc",
                "test_f1"
            ]]
        )

        # 2) Kompakte gewichtete Run-Metriken
        compact_metrics = compute_compact_weighted_metrics(
            test_df=test_df,
            score_col=score_col,
            station_table=station_table
        )

        compact_metrics.update({
            "city": city_name,
            "city_key": city_to_key(city_name) if "city_to_key" in globals() else city_name.lower().replace(" ", "_"),
            "model": model_name
        })

        oracle_compact_rows.append(compact_metrics)

# -------------------------------------------------------------
# Kompakte Ergebnis-Tabelle
# -------------------------------------------------------------
oracle_compact_metrics_df = pd.DataFrame(oracle_compact_rows)

desired_cols = [
    "city",
    "model",
    "n_valid_stations",
    "micro_pr_auc",
    "macro_station_pr_auc",
    "weighted_macro_pr_auc_group",
    "weighted_macro_pr_auc_sqrt_activity",
    "n_test_anom"
]
desired_cols = [c for c in desired_cols if c in oracle_compact_metrics_df.columns]

oracle_compact_metrics_df = oracle_compact_metrics_df[desired_cols].sort_values(
    ["model", "weighted_macro_pr_auc_sqrt_activity"],
    ascending=[True, False]
).reset_index(drop=True)

print("\n" + "="*100)
print("ORACLE — KOMPAKTE METRIK-TABELLE")
print("="*100)
display(oracle_compact_metrics_df)

# -------------------------------------------------------------
# Optional speichern
# -------------------------------------------------------------
oracle_station_dir = f"{MULTICITY_SUMMARY_DIR}/oracle_station_tables"
os.makedirs(oracle_station_dir, exist_ok=True)

for (city_name, model_name), df_ in oracle_station_tables.items():
    city_key = city_to_key(city_name) if "city_to_key" in globals() else city_name.lower().replace(" ", "_")
    out_path = f"{oracle_station_dir}/{city_key}__{model_name}__stations.csv"
    df_[["station_name", "station_id", "test_pr_auc", "test_f1"]].to_csv(out_path, index=False)

oracle_compact_metrics_path = f"{MULTICITY_SUMMARY_DIR}/oracle_compact_metrics.csv"
oracle_compact_metrics_df.to_csv(oracle_compact_metrics_path, index=False)

print(f"\nStationslisten gespeichert unter: {oracle_station_dir}")
print(f"Kompakte Metrik-Tabelle gespeichert unter: {oracle_compact_metrics_path}")

====================================================================================================
POST-HOC ORACLE ANALYSIS: Mannheim
====================================================================================================

[Mannheim | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

                            station_name station_id  test_pr_auc   test_f1
0                            Turleyplatz   29794323     0.855396  0.851064
1                   Seckenheim - Rathaus  378596121     0.811727  0.816327
2             Oststadt - Beethovenstraße   28455055     0.791221  0.719101
3              Oststadt - Augusta Anlage  195402059     0.786552  0.750000
4           Neckarstadt-West – Marchivum   30612240     0.731647  0.731034
..                                   ...        ...          ...       ...
77                Roche - Oppauer Straße   57585616     0.366441  0.535714
78            Lindenhof - Jugendherberge     121376     0.341677  0.468750
79    Lindenhof - Hanns-Glückstein-Park    28450242     0.316281  0.411765
80  Feudenheim - St. Peter & Paul Kirche  378595589     0.299289  0.437500
81   DHBW Mannheim - Campus Coblitzallee    4726808     0.251203  0.397351

[82 rows x 4 columns]

[Mannheim | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

                            station_name station_id  test_pr_auc   test_f1
0              Herzogenried - Sandgewann   24559076     0.870472  0.842105
1                            Turleyplatz   29794323     0.774876  0.764706
2                   Seckenheim - Rathaus  378596121     0.749533  0.740741
3              Oststadt - Augusta Anlage  195402059     0.698719  0.686567
4             Oststadt - Beethovenstraße   28455055     0.669334  0.680412
..                                   ...        ...          ...       ...
77  Franklin -  George-Washington-Straße   38930150     0.291421  0.500000
78                Roche - Oppauer Straße   57585616     0.259652  0.440678
79    Lindenhof - Hanns-Glückstein-Park    28450242     0.240374  0.339181
80   DHBW Mannheim - Campus Coblitzallee    4726808     0.188082  0.333333
81  Feudenheim - St. Peter & Paul Kirche  378595589     0.188059  0.368421

[82 rows x 4 columns]

====================================================================================================
POST-HOC ORACLE ANALYSIS: Heidelberg
====================================================================================================

[Heidelberg | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,Dischingerstraße,27195756,0.869834,0.833333
1,INF - Hörsaal Physik,276806387,0.770833,0.800000
2,INF - Kopfklinik/NCT,276805865,0.687054,0.682081
3,Eppelheimer Straße,7472124,0.658819,0.732673
4,Bergheim - Altes Hallenbad,661043,0.652716,0.625000
5,Neuenheim – Kußmaulstraße,121359,0.645389,0.598540
6,Ziegelhausen – Neckarschule,339523,0.629165,0.684685
7,Altstadt - Friedrich-Ebert Platz,681922,0.626206,0.666667
8,Handschuhsheim - Im Weiher,167365390,0.593854,0.635294
9,MTV - Kulturzentrum Karlstorbahnhof 1,167361578,0.589438,0.671875
10,Hauptbahnhof Bahnstadt,27700413,0.585394,0.689655
11,Altstadt - Theaterstraße,732725,0.568609,0.590909
12,Altstadt - Marstall,732726,0.549932,0.591716
13,Altstadt - Neckarmünzplatz,681918,0.549676,0.611111
14,Handschuhsheim - Steubenstraße,260512725,0.542390,0.535519
15,S-Bahnhof Schlierbach/Ziegelhausen,339519,0.537995,0.613333
16,Altstadt – Stadthalle,121363,0.526610,0.577181
17,Neuenheim - Alte PH / Keplerstraße,7447271,0.524913,0.577778
18,Holbeinring,8828563,0.521096,0.572491
19,MTV - Rheinstraße,59657356,0.516157,0.683544
20,Wieblingen - Berufsschulen / SRH,139363232,0.513048,0.666667
21,Langer Anger,36673075,0.493760,0.576000
22,INF - Cafe Botanik,276806882,0.479330,0.540816
23,S-Bahnhof Weststadt/Südstadt,121354,0.463901,0.502242
24,Weststadt - Gaisbergstraße,37539484,0.461289,0.484848
25,Kirchheim - Geschwister-Scholl-Schule,167361814,0.453615,0.573099
26,Emil-Maier-Straße,79155467,0.453240,0.560748
27,Weststadt - Blumenstraße,78599753,0.419026,0.461538
28,Altstadt - Plöck,59656724,0.415479,0.493927
29,Bergheim - rnv Betriebshof Bergheimerstr.,661047,0.407519,0.494737
30,Rhein-Neckar-Kreis / Kurfürstenanlage,4287542,0.405502,0.531073
31,Bergheim - Kurfürstenanlage,661038,0.397136,0.525424
32,Sportzentrum Süd,1814955,0.396710,0.555556
33,Kirchheim – Rathaus,339522,0.377187,0.459259
34,Wieblingen Mitte,497198,0.356709,0.477064
35,SNP-Dome,59657530,0.350051,0.470588
36,MTV - Kulturzentrum Karlstorbahnhof 2,397838281,0.343961,0.500000
37,S-Bahnhof Pfaffengrund/Wieblingen,20555131,0.331978,0.407186
38,Rohrbach – Markt,339517,0.330905,0.457143
39,Marktplatz / Pfaffengrund,59655887,0.326846,0.527473
40,Bahnstadt Halle 02,495832,0.321390,0.486842
41,Altstadt – Universitätsplatz,121361,0.314120,0.436364
42,Handschuhsheim – Hans-Thoma-Platz,344831,0.307870,0.426087
43,Neuenheim – Neckarwiese,121368,0.281928,0.378601
44,Neuenheim - Alte PH / Quinckestraße,79153997,0.250493,0.400000

[Heidelberg | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,Dischingerstraße,27195756,0.716952,0.761905
1,Neuenheim – Kußmaulstraße,121359,0.612610,0.608108
2,Bergheim - Altes Hallenbad,661043,0.607500,0.575000
3,INF - Kopfklinik/NCT,276805865,0.593556,0.555556
4,INF - Hörsaal Physik,276806387,0.590278,0.750000
5,Eppelheimer Straße,7472124,0.552050,0.709091
6,Altstadt - Friedrich-Ebert Platz,681922,0.548140,0.593750
7,Holbeinring,8828563,0.525651,0.556017
8,Hauptbahnhof Bahnstadt,27700413,0.521157,0.661871
9,Altstadt - Theaterstraße,732725,0.510492,0.522613
10,Ziegelhausen – Neckarschule,339523,0.496932,0.574468
11,MTV - Kulturzentrum Karlstorbahnhof 1,167361578,0.496335,0.539130
12,Handschuhsheim - Im Weiher,167365390,0.481614,0.547619
13,Altstadt - Neckarmünzplatz,681918,0.474017,0.547945
14,Neuenheim - Alte PH / Keplerstraße,7447271,0.471150,0.525253
15,Altstadt – Stadthalle,121363,0.470775,0.537313
16,Altstadt - Marstall,732726,0.465555,0.491018
17,INF - Cafe Botanik,276806882,0.447769,0.516129
18,Handschuhsheim - Steubenstraße,260512725,0.439097,0.493333
19,MTV - Rheinstraße,59657356,0.421165,0.593407
20,Langer Anger,36673075,0.420917,0.518519
21,S-Bahnhof Weststadt/Südstadt,121354,0.417891,0.471204
22,Weststadt - Gaisbergstraße,37539484,0.416367,0.490566
23,Wieblingen - Berufsschulen / SRH,139363232,0.412706,0.576271
24,Altstadt - Plöck,59656724,0.401897,0.467290
25,Weststadt - Blumenstraße,78599753,0.398568,0.436019
26,Emil-Maier-Straße,79155467,0.389864,0.484848
27,Bergheim - rnv Betriebshof Bergheimerstr.,661047,0.389733,0.495798
28,S-Bahnhof Schlierbach/Ziegelhausen,339519,0.368805,0.524590
29,Bergheim - Kurfürstenanlage,661038,0.358314,0.476821
30,Sportzentrum Süd,1814955,0.352205,0.493506
31,Rhein-Neckar-Kreis / Kurfürstenanlage,4287542,0.326287,0.446809
32,Kirchheim - Geschwister-Scholl-Schule,167361814,0.319082,0.448087
33,Bahnstadt Halle 02,495832,0.318133,0.389831
34,S-Bahnhof Pfaffengrund/Wieblingen,20555131,0.305001,0.363636
35,Altstadt – Universitätsplatz,121361,0.304895,0.400000
36,MTV - Kulturzentrum Karlstorbahnhof 2,397838281,0.302956,0.412698
37,Handschuhsheim – Hans-Thoma-Platz,344831,0.284218,0.410256
38,Rohrbach – Markt,339517,0.278318,0.401914
39,Kirchheim – Rathaus,339522,0.260491,0.352941
40,Marktplatz / Pfaffengrund,59655887,0.252702,0.478261
41,SNP-Dome,59657530,0.248315,0.361905
42,Wieblingen Mitte,497198,0.224156,0.358974
43,Neuenheim – Neckarwiese,121368,0.216235,0.331878
44,Neuenheim - Alte PH / Quinckestraße,79153997,0.191831,0.261438

====================================================================================================
POST-HOC ORACLE ANALYSIS: Bochum
====================================================================================================

[Bochum | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,AKAFÖ Hegge-Kolleg,275719,0.990909,0.952381
1,GLS,33713152,0.944851,0.903226
2,RUB Audimax / Mensa,253546,0.944444,0.909091
3,Oskar-Hoffmann-Str. / U35,312057,0.930586,0.851064
4,Markstr. / U35,312069,0.928430,0.880000
...,...,...,...,...
57,RUB ID,253543,0.375999,0.526316
58,Ruhr Congress Bochum,194685,0.365108,0.500000
59,RUB HZO Ost,194671,0.347248,0.526316
60,Buscheyplatz,212871,0.336496,0.320000
61,Hochschule für Gesundheit / Veranstaltungszentrum,390878,0.220217,0.375000

[Bochum | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,RUB Audimax / Mensa,253546,1.000000,1.000000
1,AKAFÖ Hegge-Kolleg,275719,0.990909,0.952381
2,Friedrich-von-Hardenberg Haus,344808,0.950000,0.888889
3,Markstr. / U35,312069,0.875484,0.857143
4,AKAFÖ Stiepeler Str.,269283,0.873639,0.933333
...,...,...,...,...
57,Ruhr Congress Bochum,194685,0.395833,0.470588
58,Buscheyplatz,212871,0.338422,0.352941
59,RUB P36,253534,0.331494,0.600000
60,RUB HZO Ost,194671,0.324954,0.500000
61,Hochschule für Gesundheit / Veranstaltungszentrum,390878,0.209623,0.400000

====================================================================================================
POST-HOC ORACLE ANALYSIS: Braunschweig
====================================================================================================

[Braunschweig | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

              station_name station_id  test_pr_auc   test_f1
0   Georg-Westermann-Allee  529257580     0.995238  0.965517
1    Ringgleis/Kreuzstraße  529259429     0.984160  0.956522
2            Pfingststraße  529283263     0.980909  0.952381
3   Johannes-Selenka-Platz  529263170     0.976358  0.930233
4               Hochstraße  529262102     0.966667  0.909091
..                     ...        ...          ...       ...
76                 Mensa 1   29853821     0.463313  0.509804
77             Jakobstraße  537237366     0.418838  0.521739
78   Institut für Stahlbau  529293384     0.262158  0.447761
79             Donauknoten  162305906     0.185148  0.375000
80         Bürger-Badepark   29853775          NaN       NaN

[81 rows x 4 columns]

[Braunschweig | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

              station_name station_id  test_pr_auc   test_f1
0            Pfingststraße  529283263     0.969798  0.952381
1   Georg-Westermann-Allee  529257580     0.964396  0.923077
2    Ringgleis/Kreuzstraße  529259429     0.959540  0.900000
3   Johannes-Selenka-Platz  529263170     0.950028  0.909091
4    Fakultät Maschinenbau  529292840     0.931559  0.909091
..                     ...        ...          ...       ...
76             Jakobstraße  537237366     0.393140  0.516129
77             Am Magnitor  537235471     0.347907  0.470588
78   Institut für Stahlbau  529293384     0.337855  0.512821
79             Donauknoten  162305906     0.133514  0.272727
80         Bürger-Badepark   29853775          NaN       NaN

[81 rows x 4 columns]

====================================================================================================
POST-HOC ORACLE ANALYSIS: Dortmund
====================================================================================================

[Dortmund | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

                           station_name station_id  test_pr_auc   test_f1
0                            Kronenburg     194704     1.000000  1.000000
1               Dorstfeld Süd S-Bahnhof   14543375     1.000000  1.000000
2                           Kuithanstr.     118419     0.978632  0.960000
3                Bergmann Stehbierhalle      50396     0.976543  0.947368
4   Steigenberger Hotel / Berswordtstr.     122697     0.975069  0.956522
..                                  ...        ...          ...       ...
73                       Otto-Hahn-Str.     113572     0.373810  0.571429
74               Nortkirchenstraße/Wilo    1073051     0.303011  0.461538
75                          Rombergpark    1073064     0.289773  0.400000
76            Phoenix See / Hörder Burg     113555          NaN       NaN
77                      Speicherstrasse  222893302          NaN       NaN

[78 rows x 4 columns]

[Dortmund | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

                      station_name station_id  test_pr_auc   test_f1
0                       Kronenburg     194704     1.000000  1.000000
1          Dorstfeld Süd S-Bahnhof   14543375     1.000000  1.000000
2             Karl-Liebknecht-Str.      50392     1.000000  1.000000
3                   Barop Parkhaus    7161443     0.983333  0.947368
4   Heiliger Weg / Kronprinzenstr.     117829     0.983333  0.947368
..                             ...        ...          ...       ...
73                Max-Ophüls-Platz     113565     0.388411  0.500000
74                  Westfalenhalle      50395     0.365553  0.571429
75                     Rombergpark    1073064     0.245548  0.400000
76       Phoenix See / Hörder Burg     113555          NaN       NaN
77                 Speicherstrasse  222893302          NaN       NaN

[78 rows x 4 columns]

====================================================================================================
POST-HOC ORACLE ANALYSIS: Duisburg
====================================================================================================

[Duisburg | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,Tausendfensterhaus,191057,0.917228,0.857143
1,Bahnhof Schlenk,319644,0.916667,0.857143
2,Rathaus / Kuhstr.,50412,0.902037,0.809524
3,Innenhafen Nord,191060,0.896730,0.800000
4,Explorado,50406,0.892857,0.833333
5,Forum,50402,0.892263,0.857143
6,GEBAG Quartier Neudorf-Nord,36678994,0.870100,0.825397
7,Wohnheim Schemkesweg,304811269,0.866705,0.819672
8,Dellplatz,50401,0.854607,0.800000
9,LIDL Koloniestraße,102438092,0.854359,0.818182
10,Schwanentor,50410,0.853099,0.756757
11,Rathaus / Burgplatz,106222,0.829248,0.750000
12,Duisburg Hauptbahnhof Osteingang,50404,0.814748,0.803571
13,Stadttheater,50411,0.802193,0.777778
14,Sternbuschweg,16740115,0.789727,0.780488
15,KAUFLAND Auf der Höhe,102438671,0.766667,0.800000
16,Bocksbarttrasse,338464,0.758312,0.840000
17,Ruhrorter Straße/Wohnheim,803768,0.749371,0.745763
18,UDE – AStA Keller Duisburg,16737728,0.749008,0.823529
19,Wohnheim Heinrich-Lersch-Str. 36-38,304811032,0.741092,0.701299
20,Kammerstr. / Wohnheim,803752,0.719644,0.731707
21,Duisburg Hauptbahnhof Verknüpfungshalle Ost,137831,0.700668,0.705882
22,Sonnenwall BZA Mitte,191059,0.684992,0.727273
23,Am Blumenkampshof,10852778,0.683205,0.695652
24,Duissern,191058,0.680701,0.750000
25,Neudorfer Markt,137832,0.672870,0.869565
26,Brückenplatz,16742147,0.668480,0.666667
27,Uni-Nord Lotharstr.,137835,0.640288,0.612903
28,Duisburg Hauptbahnhof Haupteingang,50403,0.633582,0.675325
29,Yitzhak-Rabin-Platz,50415,0.580159,0.800000
30,Rheinpark,16742211,0.500000,0.666667
31,Lehmbruckmuseum,50407,0.496510,0.761905
32,Uni Lotharstr. / Walramsweg,159858,0.491958,0.526316
33,Duisburg Hauptbahnhof Verknüpfungshalle West,50414,0.459591,0.571429
34,Friedrichsplatz,137836,0.416667,0.666667
35,GEBAG Quartier Neuenkamp,36679026,0.370448,0.571429
36,Jugendherberge / MSV Stadion,200830,0.285897,0.461538
37,Klinikum Duisburg,319645,0.277778,0.444444
38,Wolfsee,16737873,NaN,NaN
39,Hüttenwerk / Eingang Landschaftspark,50417,NaN,NaN

[Duisburg | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

,station_name,station_id,test_pr_auc,test_f1
0,Bahnhof Schlenk,319644,0.916667,0.857143
1,Forum,50402,0.884208,0.846154
2,UDE – AStA Keller Duisburg,16737728,0.882143,0.800000
3,Rathaus / Kuhstr.,50412,0.859196,0.772727
4,Bocksbarttrasse,338464,0.857042,0.888889
5,Neudorfer Markt,137832,0.847103,0.840000
6,Tausendfensterhaus,191057,0.838360,0.761905
7,GEBAG Quartier Neudorf-Nord,36678994,0.831919,0.806452
8,Innenhafen Nord,191060,0.813243,0.857143
9,Wohnheim Schemkesweg,304811269,0.812953,0.730159
10,Sternbuschweg,16740115,0.803790,0.750000
11,Rathaus / Burgplatz,106222,0.801515,0.769231
12,Stadttheater,50411,0.770589,0.727273
13,Explorado,50406,0.761565,0.800000
14,Duisburg Hauptbahnhof Osteingang,50404,0.760392,0.754717
15,LIDL Koloniestraße,102438092,0.759207,0.785714
16,Friedrichsplatz,137836,0.750000,0.666667
17,Wohnheim Heinrich-Lersch-Str. 36-38,304811032,0.746333,0.731707
18,KAUFLAND Auf der Höhe,102438671,0.738095,0.800000
19,Schwanentor,50410,0.729067,0.733333
20,Am Blumenkampshof,10852778,0.713179,0.761905
21,Dellplatz,50401,0.696416,0.666667
22,Uni-Nord Lotharstr.,137835,0.680443,0.628571
23,Sonnenwall BZA Mitte,191059,0.639549,0.666667
24,Yitzhak-Rabin-Platz,50415,0.621825,0.857143
25,Brückenplatz,16742147,0.620945,0.640000
26,Ruhrorter Straße/Wohnheim,803768,0.613823,0.606742
27,Duisburg Hauptbahnhof Verknüpfungshalle Ost,137831,0.600214,0.658228
28,Duissern,191058,0.588741,0.666667
29,Kammerstr. / Wohnheim,803752,0.578996,0.649351
30,Lehmbruckmuseum,50407,0.577205,0.727273
31,Duisburg Hauptbahnhof Haupteingang,50403,0.576460,0.692308
32,Klinikum Duisburg,319645,0.466667,0.666667
33,Duisburg Hauptbahnhof Verknüpfungshalle West,50414,0.384424,0.488889
34,Uni Lotharstr. / Walramsweg,159858,0.341619,0.454545
35,Rheinpark,16742211,0.333333,0.500000
36,GEBAG Quartier Neuenkamp,36679026,0.332011,0.461538
37,Jugendherberge / MSV Stadion,200830,0.225047,0.444444
38,Wolfsee,16737873,NaN,NaN
39,Hüttenwerk / Eingang Landschaftspark,50417,NaN,NaN

====================================================================================================
POST-HOC ORACLE ANALYSIS: Essen
====================================================================================================

[Essen | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

                       station_name station_id  test_pr_auc   test_f1
0                       Klarastraße     331814     1.000000  1.000000
1                        Martinstr.     147007     0.992063  0.971429
2                    Breslauer Str.     113468     0.983333  0.974359
3            LIDL Katzenbruchstraße  102436782     0.975000  0.933333
4                  Gemarkenstr. 50b  140538328     0.957651  0.956522
5                    Corneliastraße    6626759     0.955124  0.941176
6                        Vereinstr.     147001     0.946257  0.888889
7                      Westviertel      803721     0.939561  0.857143
8                      Paulinenstr.     113460     0.938738  0.880000
9                         GNS Essen  147313545     0.935611  0.880000
10                   Ruhrbahn Essen    6626842     0.934207  0.916667
11             Rüttenscheider Platz     331815     0.924851  0.875000
12                      Uniklinikum      50428     0.909354  0.933333
13             UDE Leimkugelstrasse   20376879     0.894600  0.900000
14                  Messe Ost/Gruga      50426     0.892857  0.857143
15                Frohnhauser Platz     115213     0.878580  0.836364
16                   Werden Bahnhof      50432     0.873413  0.923077
17                    Menzelstr. 24  140539210     0.860503  0.928571
18                      Röntgenstr.     146996     0.807540  0.800000
19    Essen Hauptbahnhof Südausgang      79845     0.806508  0.747826
20                      Universität     146999     0.801307  0.794118
21                   Berliner Platz      50419     0.792041  0.731707
22            Essen Borbeck Bahnhof     113463     0.782993  0.800000
23                 Viehofer Str. 41      50422     0.780950  0.842105
24                   Versorgungsamt     120371     0.780087  0.769231
25               Altenessen Bahnhof     113471     0.774488  0.880000
26                     Girardethaus     147009     0.773712  0.857143
27                Rheinischer Platz     803725     0.769215  0.785714
28                  Hirschlandplatz      50424     0.764784  0.880000
29                 Essen Südbahnhof      50443     0.751267  0.814815
30             Rüttenscheider Stern      50425     0.733069  0.807018
31                    Niederfeldsee   23618518     0.724363  0.700000
32                 Universitätsstr.      50438     0.719492  0.742857
33                    Kopstadtplatz      50421     0.717708  0.800000
34   Essen Hauptbahnhof Nordausgang      50445     0.705914  0.679612
35                     Schützenbahn   14586316     0.702782  0.745098
36                 Universität/AStA     803733     0.698837  0.666667
37  Mobilstation Kronprinzenstrasse     448939     0.690188  0.782609
38                    Gemarkenplatz      50427     0.687626  0.679245
39                Essen Westbahnhof      79849     0.682046  0.727273
40                      Allbau GmbH  127960617     0.666667  0.666667
41             Kleine Lenbachstraße    6626788     0.662784  0.842105
42                   Gervinusstraße     115216     0.661467  0.785714
43   I. Dellbrügge / Kettwiger Str.     305618     0.635714  0.800000
44                     Philharmonie      50423     0.616805  0.695652
45           Rüttenscheider Str. 38  140539993     0.612385  0.695652
46                     Isenbergstr.     147006     0.579005  0.702703
47                           RWE AG  140540301     0.554109  0.727273
48         Mobilstation Florastraße     147012     0.496616  0.571429
49         Mobilstation Landgericht    3579979     0.470204  0.761905
50              Hügel / Regattahaus      50435     0.469286  0.769231
51                       Univiertel     803731     0.431469  0.631579

[Essen | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

                       station_name station_id  test_pr_auc   test_f1
0                        Martinstr.     147007     0.989899  0.971429
1                  Gemarkenstr. 50b  140538328     0.980451  0.954545
2                    Breslauer Str.     113468     0.961628  0.974359
3            LIDL Katzenbruchstraße  102436782     0.950284  0.875000
4                        Vereinstr.     147001     0.945998  0.880000
5                    Ruhrbahn Essen    6626842     0.927632  0.900000
6              Rüttenscheider Platz     331815     0.914931  0.875000
7                      Westviertel      803721     0.910485  0.833333
8                         GNS Essen  147313545     0.907305  0.846154
9                   Messe Ost/Gruga      50426     0.875000  0.857143
10                   Werden Bahnhof      50432     0.873413  0.923077
11                    Menzelstr. 24  140539210     0.865264  0.962963
12             UDE Leimkugelstrasse   20376879     0.849838  0.900000
13                   Corneliastraße    6626759     0.837167  0.941176
14             Kleine Lenbachstraße    6626788     0.833879  0.941176
15                     Paulinenstr.     113460     0.829634  0.880000
16                      Universität     146999     0.815508  0.805970
17                      Röntgenstr.     146996     0.786111  0.800000
18                     Girardethaus     147009     0.784667  0.814815
19                      Uniklinikum      50428     0.780952  0.769231
20                 Viehofer Str. 41      50422     0.779389  0.857143
21   I. Dellbrügge / Kettwiger Str.     305618     0.759722  0.800000
22                   Berliner Platz      50419     0.757597  0.750000
23                Rheinischer Platz     803725     0.751594  0.774194
24               Altenessen Bahnhof     113471     0.750582  0.916667
25                Frohnhauser Platz     115213     0.747047  0.848485
26                 Essen Südbahnhof      50443     0.744715  0.785714
27    Essen Hauptbahnhof Südausgang      79845     0.741422  0.650407
28                  Hirschlandplatz      50424     0.711183  0.846154
29                      Klarastraße     331814     0.710000  0.909091
30                     Schützenbahn   14586316     0.702575  0.784314
31                 Universitätsstr.      50438     0.698536  0.727273
32                   Versorgungsamt     120371     0.681006  0.727273
33                           RWE AG  140540301     0.672735  0.682927
34                 Universität/AStA     803733     0.669748  0.647059
35             Rüttenscheider Stern      50425     0.661396  0.692308
36           Rüttenscheider Str. 38  140539993     0.651409  0.800000
37                    Kopstadtplatz      50421     0.634810  0.777778
38                   Gervinusstraße     115216     0.631204  0.720000
39                Essen Westbahnhof      79849     0.630797  0.708333
40   Essen Hauptbahnhof Nordausgang      50445     0.624864  0.589744
41                    Gemarkenplatz      50427     0.623065  0.610169
42                     Philharmonie      50423     0.620803  0.648649
43            Essen Borbeck Bahnhof     113463     0.604396  0.666667
44  Mobilstation Kronprinzenstrasse     448939     0.567268  0.642857
45                    Niederfeldsee   23618518     0.544139  0.631579
46                     Isenbergstr.     147006     0.535961  0.689655
47              Hügel / Regattahaus      50435     0.485952  0.769231
48         Mobilstation Landgericht    3579979     0.483651  0.761905
49         Mobilstation Florastraße     147012     0.473967  0.588235
50                       Univiertel     803731     0.455977  0.631579
51                      Allbau GmbH  127960617     0.411111  0.666667

====================================================================================================
POST-HOC ORACLE ANALYSIS: Marburg
====================================================================================================

[Marburg | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

                             station_name station_id  test_pr_auc   test_f1
0                       Wehrda Bürgerhaus    4774572     0.889656  0.838710
1                      Ockershäuser Allee   39482836     0.859004  0.813559
2                        Ginseldorfer Weg    4774464     0.730533  0.688742
3                    Südbahnhof Westseite    4774549     0.696422  0.653659
4                          Bismarckstraße  194830689     0.686656  0.744186
5      Universitätsstraße/Bibliothek Jura    4774567     0.685283  0.683230
6               Elisabeth-Blochmann-Platz    4774360     0.663926  0.660000
7                           Wilhelmsplatz    4774574     0.632391  0.658385
8             Hebronberg/ Wehrdaer Straße  194826996     0.615301  0.682171
9                        Alte Universität  143843398     0.611270  0.581818
10                Kreisverwaltung Marburg  367728862     0.607506  0.615385
11                         Am Schülerpark    5220935     0.606535  0.647619
12                                    ZOB  143842773     0.605972  0.652174
13                         Friedrichplatz   13391482     0.605220  0.610687
14   Adolf-Reichwein-Schule/ Abendschulen  148824174     0.600927  0.571429
15           Am Krekel/Stadtwerke Marburg    4774235     0.596935  0.684932
16                  Georg-Gaßmann-Stadion    4774459     0.577390  0.575916
17             Frankfurter Straße/Theater    4774452     0.570887  0.587571
18                             Uferstraße   39482783     0.562457  0.561644
19                   An den Siechengärten    4774277     0.560674  0.623377
20            Neue Universitätsbibliothek    6666288     0.558948  0.609524
21              Ketzerbach/Zwischenhausen   13391528     0.552934  0.539474
22                             Südbahnhof    4774543     0.548141  0.597403
23                              Trojedamm  143843534     0.542784  0.544118
24                    Ernst-Lemmer-Straße  146902992     0.541848  0.632911
25                           Hauptbahnhof    4774470     0.520459  0.537736
26                   Leopold-Lucas-Straße  194831489     0.512115  0.552846
27                              Stadtbüro    4774539     0.506637  0.584906
28  Schlosserstraße/ Neue Kasseler Straße  194829274     0.474728  0.520325
29                         Ortenbergplatz    4774485     0.468022  0.551020
30                        Elisabethbrücke  143842973     0.437086  0.569767
31                                Audimax    4774475     0.432981  0.518519
32                          Brunnenstraße    4774337     0.422002  0.530612
33                       Day Night Sports   62902963     0.404468  0.477419
34                tegut / Kaufpark Wehrda  500107110     0.333714  0.393162
35                               Anatomie   14235672     0.296817  0.390625
36  Interkulturelle Gärten/ Am Richtsberg   13391461     0.296101  0.427184
37                                Aquamar    4774527     0.293102  0.349515
38                    Universitätsstadion    4774562     0.248880  0.363636
39                Philosophische Fakultät    4774503     0.202242  0.311377

[Marburg | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

                             station_name station_id  test_pr_auc   test_f1
0                      Ockershäuser Allee   39482836     0.789311  0.743802
1                       Wehrda Bürgerhaus    4774572     0.774309  0.774194
2                          Bismarckstraße  194830689     0.694386  0.701299
3                    Südbahnhof Westseite    4774549     0.662283  0.649351
4      Universitätsstraße/Bibliothek Jura    4774567     0.647250  0.642424
5               Elisabeth-Blochmann-Platz    4774360     0.643684  0.635071
6    Adolf-Reichwein-Schule/ Abendschulen  148824174     0.591545  0.577778
7                        Ginseldorfer Weg    4774464     0.587878  0.593103
8                          Am Schülerpark    5220935     0.581344  0.574468
9                           Wilhelmsplatz    4774574     0.572097  0.567742
10                       Alte Universität  143843398     0.567676  0.547170
11                         Friedrichplatz   13391482     0.560238  0.588235
12            Hebronberg/ Wehrdaer Straße  194826996     0.535209  0.587413
13                   An den Siechengärten    4774277     0.533453  0.554054
14             Frankfurter Straße/Theater    4774452     0.523343  0.524272
15                  Georg-Gaßmann-Stadion    4774459     0.510353  0.511364
16                             Südbahnhof    4774543     0.510218  0.562963
17                              Trojedamm  143843534     0.509824  0.526316
18           Am Krekel/Stadtwerke Marburg    4774235     0.502055  0.594595
19            Neue Universitätsbibliothek    6666288     0.496003  0.574074
20                                    ZOB  143842773     0.488498  0.598930
21                             Uferstraße   39482783     0.471154  0.504854
22              Ketzerbach/Zwischenhausen   13391528     0.459288  0.448276
23                Kreisverwaltung Marburg  367728862     0.457004  0.520000
24                   Leopold-Lucas-Straße  194831489     0.444478  0.491525
25                         Ortenbergplatz    4774485     0.435409  0.520000
26                        Elisabethbrücke  143842973     0.425084  0.573171
27                           Hauptbahnhof    4774470     0.422189  0.460000
28                              Stadtbüro    4774539     0.420873  0.517241
29  Schlosserstraße/ Neue Kasseler Straße  194829274     0.404827  0.510949
30                    Ernst-Lemmer-Straße  146902992     0.392627  0.515152
31                               Anatomie   14235672     0.381058  0.466667
32                                Audimax    4774475     0.376034  0.493151
33                          Brunnenstraße    4774337     0.325564  0.440678
34                       Day Night Sports   62902963     0.324944  0.417910
35                tegut / Kaufpark Wehrda  500107110     0.256910  0.333333
36                                Aquamar    4774527     0.256849  0.329897
37                    Universitätsstadion    4774562     0.236921  0.375940
38  Interkulturelle Gärten/ Am Richtsberg   13391461     0.224954  0.329114
39                Philosophische Fakultät    4774503     0.156732  0.240000

====================================================================================================
POST-HOC ORACLE ANALYSIS: Winsen (Luhe)
====================================================================================================

[Winsen (Luhe) | FC_Oracle] Stationsliste (sortiert nach test_pr_auc)

                station_name station_id  test_pr_auc   test_f1
0          Kapelle St. Georg   87641918     0.962257  0.950000
1                 Stadthalle   87642769     0.901252  0.838710
2   Albert-Schweitzer-Straße  162363388     0.873226  0.792208
3           Von-Somnitz-Ring   87642200     0.871471  0.813333
4                    Bleiche  149877579     0.835847  0.797468
5                  Deichstr.   87642883     0.830552  0.788618
6     Schlossplatz / Rathaus   87642371     0.782195  0.754717
7              Eckermannstr.   87640674     0.752585  0.733333
8           An der Kleinbahn  149876031     0.744878  0.687783
9                  Die Insel   87642602     0.700022  0.688000
10    Astrid Lindgren Straße  108135072     0.698227  0.754098
11                  Luhepark   87642035     0.689837  0.662857
12         Schirwindter Str.   87643153     0.608562  0.723404
13         Feuerwehr Luhdorf   87640448     0.563971  0.684932
14                   Bahnhof   87638190     0.560929  0.571429
15               Krankenhaus   87638952     0.471438  0.615385

[Winsen (Luhe) | AE_Oracle] Stationsliste (sortiert nach test_pr_auc)

                station_name station_id  test_pr_auc   test_f1
0          Kapelle St. Georg   87641918     0.959881  0.923077
1           Von-Somnitz-Ring   87642200     0.877119  0.805556
2   Albert-Schweitzer-Straße  162363388     0.858303  0.811429
3                 Stadthalle   87642769     0.831282  0.813559
4     Schlossplatz / Rathaus   87642371     0.809912  0.757576
5                  Deichstr.   87642883     0.808184  0.764912
6              Eckermannstr.   87640674     0.790193  0.748718
7                    Bleiche  149877579     0.754092  0.770270
8           An der Kleinbahn  149876031     0.680232  0.645418
9                  Die Insel   87642602     0.671268  0.688000
10                  Luhepark   87642035     0.618048  0.612500
11    Astrid Lindgren Straße  108135072     0.598782  0.718232
12         Schirwindter Str.   87643153     0.500822  0.615385
13         Feuerwehr Luhdorf   87640448     0.480154  0.619718
14                   Bahnhof   87638190     0.465140  0.516517
15               Krankenhaus   87638952     0.413767  0.555556

====================================================================================================
ORACLE — KOMPAKTE METRIK-TABELLE
====================================================================================================

,city,model,n_valid_stations,micro_pr_auc,macro_station_pr_auc,weighted_macro_pr_auc_group,weighted_macro_pr_auc_sqrt_activity,n_test_anom
0,Essen,AE_Oracle,52,0.617377,0.733436,0.731956,0.729984,842
1,Dortmund,AE_Oracle,76,0.624054,0.729490,0.723881,0.719298,1295
2,Winsen (Luhe),AE_Oracle,16,0.651449,0.694824,0.703037,0.689101,1103
3,Braunschweig,AE_Oracle,80,0.605102,0.695048,0.683774,0.685333,1546
4,Duisburg,AE_Oracle,38,0.521605,0.677744,0.679875,0.683678,634
5,Bochum,AE_Oracle,62,0.512149,0.627268,0.625340,0.628507,938
6,Marburg,AE_Oracle,40,0.432330,0.478846,0.478522,0.484752,2466
7,Mannheim,AE_Oracle,82,0.424727,0.480244,0.472130,0.474285,4988
8,Heidelberg,AE_Oracle,45,0.366151,0.413393,0.415235,0.412429,2772
9,Essen,FC_Oracle,52,0.651303,0.771060,0.769867,0.767844,842
10,Winsen (Luhe),FC_Oracle,16,0.688936,0.740453,0.746396,0.735995,1103
11,Dortmund,FC_Oracle,76,0.602882,0.720946,0.729065,0.724747,1295
12,Duisburg,FC_Oracle,38,0.537244,0.702117,0.714959,0.722742,634
13,Braunschweig,FC_Oracle,80,0.607523,0.725529,0.709533,0.711125,1546
14,Bochum,FC_Oracle,62,0.516348,0.647917,0.657088,0.656709,938
15,Mannheim,FC_Oracle,82,0.498586,0.567548,0.555481,0.558378,4988
16,Marburg,FC_Oracle,40,0.478934,0.538974,0.533504,0.540951,2466
17,Heidelberg,FC_Oracle,45,0.423788,0.484424,0.476474,0.474466,2772

Stationslisten gespeichert unter: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/summary/oracle_station_tables
Kompakte Metrik-Tabelle gespeichert unter: /content/drive/MyDrive/BA_Colab/data/v20d_spike_only/multicity/summary/oracle_compact_metrics.csv
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:

# ══════════════════════════════════════════════════════════════
# MC-5 — Multi-City MOMENT (Zero-Shot + Fine-Tune) mit Speicherung
# ══════════════════════════════════════════════════════════════
score_feat_idx = [ae_features.index(f) for f in MOMENT_SCORE_FEATURES]
moment_summary_rows = []
moment_histories = {}
moment_score_paths = []

def run_moment_city(city_name: str, city_data: dict, model_dir: str):
    train_end = city_data["train_end"]
    val_end   = city_data["val_end"]

    # ----- Zero-Shot -----
    print(f"\n[{city_name}] MOMENT Zero-Shot")
    zs_model = load_moment_model()
    zs_meta = city_data["meta_all"].copy()
    zs_meta["score_moment_raw"] = moment_reconstruction_scores(
        zs_model,
        city_data["X_all"],
        score_feat_idx,
        batch_size=MOMENT_BATCH_SIZE,
        device=device
    )
    zs_meta = znorm_score_by_hour_station(
        zs_meta,
        raw_score_col="score_moment_raw",
        val_start=train_end,
        test_start=val_end,
        new_col="score_moment_znorm_hs"
    )
    zs_meta = add_station_demand_weight(zs_meta)
    zs_res = evaluate_v17b(
        zs_meta,
        score_col="score_moment_znorm_hs",
        experiment_name=f"{city_name}_MOMENT_ZeroShot",
        val_start=train_end,
        test_start=val_end
    )

    # ----- Fine-Tune -----
    print(f"\n[{city_name}] MOMENT Fine-Tune")
    X_train_ft = maybe_subsample(city_data["X_train"], MOMENT_FT_MAX_TRAIN_WINDOWS, seed=42)
    X_val_ft   = city_data["X_val_clean"]

    train_loader, val_loader = make_moment_loaders_from_oracle_data(
        X_train_ft, X_val_ft, score_feat_idx,
        batch_size=MOMENT_FT_BATCH_SIZE
    )

    ft_model = load_moment_model()
    city_key = city_to_key(city_name)
    ft_model, ft_history = fine_tune_moment_reconstruction(
        ft_model,
        train_loader=train_loader,
        val_loader=val_loader,
        epochs=MOMENT_FT_EPOCHS,
        lr=MOMENT_FT_LR,
        head_only=MOMENT_FT_HEAD_ONLY,
        save_path=f"{model_dir}/{city_key}_moment_ft.pt"
    )

    mask_valtest = city_data["meta_all"]["split_eval"].isin(["val", "test"]).values
    X_valtest = city_data["X_all"][mask_valtest]
    meta_valtest = city_data["meta_all"].loc[mask_valtest].copy()

    ft_meta = meta_valtest.copy()
    ft_meta["score_moment_ft_raw"] = moment_reconstruction_scores(
        ft_model,
        X_valtest,
        score_feat_idx,
        batch_size=MOMENT_BATCH_SIZE,
        device=device
    )
    ft_meta = znorm_score_by_hour_station(
        ft_meta,
        raw_score_col="score_moment_ft_raw",
        val_start=train_end,
        test_start=val_end,
        new_col="score_moment_ft_znorm_hs"
    )
    ft_meta = add_station_demand_weight(ft_meta)
    ft_res = evaluate_v17b(
        ft_meta,
        score_col="score_moment_ft_znorm_hs",
        experiment_name=f"{city_name}_MOMENT_FineTune",
        val_start=train_end,
        test_start=val_end
    )

    return zs_res, zs_meta, ft_res, ft_meta, ft_history

for city_name, city_data in multi_city_data.items():
    print("\n" + "="*90)
    print(f"MOMENT LOOP: {city_name}")
    print("="*90)

    zs_res, zs_meta, ft_res, ft_meta, ft_history = run_moment_city(
        city_name, city_data, MULTICITY_MODEL_DIR
    )
    moment_histories[city_name] = ft_history

    moment_summary_rows.append(flatten_result_dict(zs_res, city_name, "MOMENT_ZeroShot"))
    moment_summary_rows.append(flatten_result_dict(ft_res, city_name, "MOMENT_FineTune"))

    moment_score_paths.append(
        save_window_level_scores(
            zs_meta, city_name, "MOMENT_ZeroShot", MULTICITY_PRED_DIR,
            score_cols=["score_moment_raw", "score_moment_znorm_hs"],
            extra_cols=["station_activity_raw", "station_activity_log1p", "station_activity_group"]
        )
    )
    moment_score_paths.append(
        save_window_level_scores(
            ft_meta, city_name, "MOMENT_FineTune", MULTICITY_PRED_DIR,
            score_cols=["score_moment_ft_raw", "score_moment_ft_znorm_hs"],
            extra_cols=["station_activity_raw", "station_activity_log1p", "station_activity_group"]
        )
    )

    p = save_regime_detail_if_present(zs_res, city_name, "MOMENT_ZeroShot", MULTICITY_SUMMARY_DIR)
    if p is not None:
        oracle_regime_paths.append(p)
    p = save_regime_detail_if_present(ft_res, city_name, "MOMENT_FineTune", MULTICITY_SUMMARY_DIR)
    if p is not None:
        oracle_regime_paths.append(p)

moment_summary_df = pd.DataFrame(moment_summary_rows)
moment_summary_path = f"{MULTICITY_SUMMARY_DIR}/moment_summary.csv"
moment_summary_df.to_csv(moment_summary_path, index=False)

print("\nMOMENT Summary:")
display(moment_summary_df.sort_values(["model", "test_pr_auc"], ascending=[True, False]))
print(f"\nMOMENT Summary gespeichert unter: {moment_summary_path}")

In [ ]:

# ══════════════════════════════════════════════════════════════
# MC-6 — Gesamtvergleich + Check für spätere Gewichtung
# ══════════════════════════════════════════════════════════════
all_summary_df = pd.concat(
    [oracle_summary_df, moment_summary_df],
    ignore_index=True
).sort_values(["city", "test_pr_auc"], ascending=[True, False]).reset_index(drop=True)

all_summary_path = f"{MULTICITY_SUMMARY_DIR}/all_models_summary.csv"
all_summary_df.to_csv(all_summary_path, index=False)

print("Gesamtsummary:")
display(all_summary_df[[
    "city", "model", "experiment", "test_pr_auc", "test_f1", "test_prec", "test_recall"
]].sort_values(["city", "test_pr_auc"], ascending=[True, False]))

# Quick Check: Sind die prediction files für spätere Gewichtung vorhanden?
prediction_files = sorted([p for p in os.listdir(MULTICITY_PRED_DIR) if p.endswith(".parquet")])
print(f"\nPrediction-Files: {len(prediction_files)}")
for p in prediction_files[:20]:
    print(" -", p)

print(f"\nAll Summary gespeichert unter: {all_summary_path}")